"""ActivoWeb CRUD endpoints — generated by scripts/new_entity.py."""

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db
from app.api.deps_ownership import require_ownership
from app.core.response import success
from app.models.user import User
from app.models.activo_web import ActivoWeb
from app.schemas.activo_web import ActivoWebCreate, ActivoWebRead, ActivoWebUpdate
from app.services.activo_web_service import activo_web_svc

router = APIRouter()


@router.get("")
async def list_activo_webs(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List activo_webs owned by the current user."""
    items = await activo_web_svc.list(db, filters={"user_id": current_user.id})
    return success([ActivoWebRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_activo_web(
    entity: ActivoWeb = Depends(require_ownership(activo_web_svc)),
):
    """Get a single owned activo_web by ID (404 if not owned)."""
    return success(ActivoWebRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_activo_web(
    entity_in: ActivoWebCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new activo_web for the current user."""
    entity = await activo_web_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(ActivoWebRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_activo_web(
    entity_in: ActivoWebUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: ActivoWeb = Depends(require_ownership(activo_web_svc)),
):
    """Partially update an owned activo_web (404 if not owned)."""
    updated = await activo_web_svc.update(
        db, entity.id, entity_in, scope={"user_id": current_user.id}
    )
    return success(ActivoWebRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_activo_web(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: ActivoWeb = Depends(require_ownership(activo_web_svc)),
):
    """Delete an owned activo_web (404 if not owned)."""
    await activo_web_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "ActivoWeb deleted"})
