"""AplicacionMovil CRUD endpoints — generated by scripts/new_entity.py."""

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db
from app.api.deps_ownership import require_ownership
from app.core.response import success
from app.models.aplicacion_movil import AplicacionMovil
from app.models.user import User
from app.schemas.aplicacion_movil import AplicacionMovilCreate, AplicacionMovilRead, AplicacionMovilUpdate
from app.services.aplicacion_movil_service import aplicacion_movil_svc

router = APIRouter()


@router.get("")
async def list_aplicacion_movils(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List aplicacion_movils owned by the current user."""
    items = await aplicacion_movil_svc.list(db, filters={"user_id": current_user.id})
    return success([AplicacionMovilRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_aplicacion_movil(
    entity: AplicacionMovil = Depends(require_ownership(aplicacion_movil_svc)),
):
    """Get a single owned aplicacion_movil by ID (404 if not owned)."""
    return success(AplicacionMovilRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_aplicacion_movil(
    entity_in: AplicacionMovilCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new aplicacion_movil for the current user."""
    entity = await aplicacion_movil_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(AplicacionMovilRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_aplicacion_movil(
    entity_in: AplicacionMovilUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: AplicacionMovil = Depends(require_ownership(aplicacion_movil_svc)),
):
    """Partially update an owned aplicacion_movil (404 if not owned)."""
    updated = await aplicacion_movil_svc.update(db, entity.id, entity_in, scope={"user_id": current_user.id})
    return success(AplicacionMovilRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_aplicacion_movil(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: AplicacionMovil = Depends(require_ownership(aplicacion_movil_svc)),
):
    """Delete an owned aplicacion_movil (404 if not owned)."""
    await aplicacion_movil_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "AplicacionMovil deleted"})
