"""Celula CRUD endpoints — generated by scripts/new_entity.py."""

from __future__ import annotations

import csv
import hashlib
from io import StringIO

from fastapi import APIRouter, Depends, File, UploadFile
from fastapi.responses import Response
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_db, require_permission
from app.api.deps_ownership import require_ownership
from app.core.catalog_csv import celula_row, celula_template_body, read_csv_dict_rows
from app.core.permissions import P
from app.core.response import success
from app.models.celula import Celula
from app.models.user import User
from app.schemas.celula import CelulaCreate, CelulaRead, CelulaUpdate
from app.services.audit_service import record as audit_record
from app.services.celula_service import celula_svc
from app.services.organizacion_service import organizacion_svc

router = APIRouter()


@router.get("/export.csv")
async def export_celulas_csv(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.VIEW)),
):
    items = await celula_svc.list(db, filters={"user_id": current_user.id})
    buf = StringIO()
    writer = csv.writer(buf)
    writer.writerow(["id", "nombre", "tipo", "descripcion", "organizacion_id"])
    for r in items:
        writer.writerow([str(r.id), r.nombre, r.tipo, r.descripcion or "", str(r.organizacion_id)])
    body = buf.getvalue()
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    await audit_record(
        db,
        action="celula.export_csv",
        entity_type="celula",
        entity_id=current_user.id,
        metadata={"rows": len(items), "sha256": digest, "format": "csv"},
    )
    return Response(
        content=body,
        media_type="text/csv; charset=utf-8",
        headers={"Content-Disposition": 'attachment; filename="celulas.csv"'},
    )


@router.get("/import-template.csv")
async def download_celula_import_template(
    _db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.CREATE)),
):
    body = celula_template_body()
    return Response(
        content=body,
        media_type="text/csv; charset=utf-8",
        headers={"Content-Disposition": 'attachment; filename="celulas_import_template.csv"'},
    )


@router.post("/import")
async def import_celulas_csv(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.CREATE)),
    file: UploadFile = File(..., description="CSV con cabecera (ver import-template)"),
):
    raw = await file.read()
    digest = hashlib.sha256(raw).hexdigest()
    text = raw.decode("utf-8-sig")
    rows = read_csv_dict_rows(text)
    err_list: list[dict] = []
    created = 0

    for line_no, d in enumerate(rows, start=2):
        parsed, perr = celula_row(d, row=line_no)
        if perr is not None:
            err_list.append({"row": line_no, "message": perr})
            continue
        assert parsed is not None
        org = await organizacion_svc.get(
            db, parsed.organizacion_id, scope={"user_id": current_user.id}
        )
        if not org:
            err_list.append({"row": line_no, "message": "organizacion_id inexistente o sin acceso"})
            continue
        if not parsed.nombre.strip() or not parsed.tipo.strip():
            err_list.append({"row": line_no, "message": "nombre y tipo obligatorios"})
            continue
        await celula_svc.create(db, parsed, extra={"user_id": current_user.id})
        created += 1

    await audit_record(
        db,
        action="celula.import_csv",
        entity_type="celula",
        entity_id=current_user.id,
        metadata={
            "rows_in_file": len(rows),
            "created": created,
            "row_errors": len(err_list),
            "sha256": digest,
            "format": "csv",
        },
    )
    meta: dict = {"import_row_errors": len(err_list), "sha256": digest}
    if err_list:
        meta["import_errors"] = err_list
    return success({"created": created, "errors": err_list}, meta=meta)


@router.get("")
async def list_celulas(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.VIEW)),
):
    """List celulas owned by the current user."""
    items = await celula_svc.list(db, filters={"user_id": current_user.id})
    return success([CelulaRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_celula(
    _: User = Depends(require_permission(P.CATALOGS.VIEW)),
    entity: Celula = Depends(require_ownership(celula_svc)),
):
    """Get a single owned celula by ID (404 if not owned)."""
    return success(CelulaRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_celula(
    entity_in: CelulaCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.CREATE)),
):
    """Create a new celula for the current user."""
    entity = await celula_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(CelulaRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_celula(
    entity_in: CelulaUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.EDIT)),
    entity: Celula = Depends(require_ownership(celula_svc)),
):
    """Partially update an owned celula (404 if not owned)."""
    updated = await celula_svc.update(db, entity.id, entity_in, scope={"user_id": current_user.id})
    return success(CelulaRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_celula(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.DELETE)),
    entity: Celula = Depends(require_ownership(celula_svc)),
):
    """Delete an owned celula (404 if not owned)."""
    await celula_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "Celula deleted"})
