"""Celula CRUD endpoints — generated by scripts/new_entity.py."""

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db
from app.api.deps_ownership import require_ownership
from app.core.response import success
from app.models.user import User
from app.models.celula import Celula
from app.schemas.celula import CelulaCreate, CelulaRead, CelulaUpdate
from app.services.celula_service import celula_svc

router = APIRouter()


@router.get("")
async def list_celulas(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List celulas owned by the current user."""
    items = await celula_svc.list(db, filters={"user_id": current_user.id})
    return success([CelulaRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_celula(
    entity: Celula = Depends(require_ownership(celula_svc)),
):
    """Get a single owned celula by ID (404 if not owned)."""
    return success(CelulaRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_celula(
    entity_in: CelulaCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new celula for the current user."""
    entity = await celula_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(CelulaRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_celula(
    entity_in: CelulaUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: Celula = Depends(require_ownership(celula_svc)),
):
    """Partially update an owned celula (404 if not owned)."""
    updated = await celula_svc.update(
        db, entity.id, entity_in, scope={"user_id": current_user.id}
    )
    return success(CelulaRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_celula(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: Celula = Depends(require_ownership(celula_svc)),
):
    """Delete an owned celula (404 if not owned)."""
    await celula_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "Celula deleted"})
