"""ControlSourceCode CRUD endpoints — generated by scripts/new_entity.py."""

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db
from app.api.deps_ownership import require_ownership
from app.core.response import success
from app.models.user import User
from app.models.control_source_code import ControlSourceCode
from app.schemas.control_source_code import ControlSourceCodeCreate, ControlSourceCodeRead, ControlSourceCodeUpdate
from app.services.control_source_code_service import control_source_code_svc

router = APIRouter()


@router.get("")
async def list_control_source_codes(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List control_source_codes owned by the current user."""
    items = await control_source_code_svc.list(db, filters={"user_id": current_user.id})
    return success([ControlSourceCodeRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_control_source_code(
    entity: ControlSourceCode = Depends(require_ownership(control_source_code_svc)),
):
    """Get a single owned control_source_code by ID (404 if not owned)."""
    return success(ControlSourceCodeRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_control_source_code(
    entity_in: ControlSourceCodeCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new control_source_code for the current user."""
    entity = await control_source_code_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(ControlSourceCodeRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_control_source_code(
    entity_in: ControlSourceCodeUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: ControlSourceCode = Depends(require_ownership(control_source_code_svc)),
):
    """Partially update an owned control_source_code (404 if not owned)."""
    updated = await control_source_code_svc.update(
        db, entity.id, entity_in, scope={"user_id": current_user.id}
    )
    return success(ControlSourceCodeRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_control_source_code(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: ControlSourceCode = Depends(require_ownership(control_source_code_svc)),
):
    """Delete an owned control_source_code (404 if not owned)."""
    await control_source_code_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "ControlSourceCode deleted"})
