"""ControlSeguridad CRUD endpoints — generated by scripts/new_entity.py."""

from __future__ import annotations

import csv
import hashlib
from io import StringIO

from fastapi import APIRouter, Depends, File, UploadFile
from fastapi.responses import Response
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db, require_permission
from app.api.deps_ownership import require_ownership
from app.core.catalog_csv import control_seguridad_row, control_seguridad_template_body, read_csv_dict_rows
from app.core.permissions import P
from app.core.response import success
from app.models.control_seguridad import ControlSeguridad
from app.models.user import User
from app.schemas.control_seguridad import ControlSeguridadCreate, ControlSeguridadRead, ControlSeguridadUpdate
from app.services.audit_service import record as audit_record
from app.services.control_seguridad_service import control_seguridad_svc

router = APIRouter()


@router.get("/export.csv")
async def export_control_seguridads_csv(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.VIEW)),
):
    items = await control_seguridad_svc.list(db, filters={"user_id": current_user.id})
    buf = StringIO()
    writer = csv.writer(buf)
    writer.writerow(["id", "nombre", "tipo", "descripcion", "obligatorio"])
    for r in items:
        writer.writerow([str(r.id), r.nombre, r.tipo, r.descripcion or "", r.obligatorio])
    body = buf.getvalue()
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    await audit_record(
        db,
        action="control_seguridad.export_csv",
        entity_type="control_seguridad",
        entity_id=current_user.id,
        metadata={"rows": len(items), "sha256": digest, "format": "csv"},
    )
    return Response(
        content=body,
        media_type="text/csv; charset=utf-8",
        headers={"Content-Disposition": 'attachment; filename="controles_seguridad.csv"'},
    )


@router.get("/import-template.csv")
async def download_control_seguridad_import_template(
    _db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.CREATE)),
):
    body = control_seguridad_template_body()
    return Response(
        content=body,
        media_type="text/csv; charset=utf-8",
        headers={"Content-Disposition": 'attachment; filename="controles_seguridad_import_template.csv"'},
    )


@router.post("/import")
async def import_control_seguridads_csv(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.CREATE)),
    file: UploadFile = File(..., description="CSV con cabecera (ver import-template)"),
):
    raw = await file.read()
    digest = hashlib.sha256(raw).hexdigest()
    text = raw.decode("utf-8-sig")
    rows = read_csv_dict_rows(text)
    err_list: list[dict] = []
    created = 0

    for line_no, d in enumerate(rows, start=2):
        parsed, perr = control_seguridad_row(d, row=line_no)
        if perr is not None:
            err_list.append({"row": line_no, "message": perr})
            continue
        assert parsed is not None
        if not parsed.nombre.strip() or not parsed.tipo.strip():
            err_list.append({"row": line_no, "message": "nombre y tipo obligatorios"})
            continue
        await control_seguridad_svc.create(db, parsed, extra={"user_id": current_user.id})
        created += 1

    await audit_record(
        db,
        action="control_seguridad.import_csv",
        entity_type="control_seguridad",
        entity_id=current_user.id,
        metadata={
            "rows_in_file": len(rows),
            "created": created,
            "row_errors": len(err_list),
            "sha256": digest,
            "format": "csv",
        },
    )
    meta: dict = {"import_row_errors": len(err_list), "sha256": digest}
    if err_list:
        meta["import_errors"] = err_list
    return success({"created": created, "errors": err_list}, meta=meta)


@router.get("")
async def list_control_seguridads(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List control_seguridads owned by the current user."""
    items = await control_seguridad_svc.list(db, filters={"user_id": current_user.id})
    return success([ControlSeguridadRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_control_seguridad(
    entity: ControlSeguridad = Depends(require_ownership(control_seguridad_svc)),
):
    """Get a single owned control_seguridad by ID (404 if not owned)."""
    return success(ControlSeguridadRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_control_seguridad(
    entity_in: ControlSeguridadCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new control_seguridad for the current user."""
    entity = await control_seguridad_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(ControlSeguridadRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_control_seguridad(
    entity_in: ControlSeguridadUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: ControlSeguridad = Depends(require_ownership(control_seguridad_svc)),
):
    """Partially update an owned control_seguridad (404 if not owned)."""
    updated = await control_seguridad_svc.update(db, entity.id, entity_in, scope={"user_id": current_user.id})
    return success(ControlSeguridadRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_control_seguridad(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: ControlSeguridad = Depends(require_ownership(control_seguridad_svc)),
):
    """Delete an owned control_seguridad (404 if not owned)."""
    await control_seguridad_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "ControlSeguridad deleted"})
