"""ControlSeguridad CRUD endpoints — generated by scripts/new_entity.py."""

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db
from app.api.deps_ownership import require_ownership
from app.core.response import success
from app.models.control_seguridad import ControlSeguridad
from app.models.user import User
from app.schemas.control_seguridad import ControlSeguridadCreate, ControlSeguridadRead, ControlSeguridadUpdate
from app.services.control_seguridad_service import control_seguridad_svc

router = APIRouter()


@router.get("")
async def list_control_seguridads(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List control_seguridads owned by the current user."""
    items = await control_seguridad_svc.list(db, filters={"user_id": current_user.id})
    return success([ControlSeguridadRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_control_seguridad(
    entity: ControlSeguridad = Depends(require_ownership(control_seguridad_svc)),
):
    """Get a single owned control_seguridad by ID (404 if not owned)."""
    return success(ControlSeguridadRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_control_seguridad(
    entity_in: ControlSeguridadCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new control_seguridad for the current user."""
    entity = await control_seguridad_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(ControlSeguridadRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_control_seguridad(
    entity_in: ControlSeguridadUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: ControlSeguridad = Depends(require_ownership(control_seguridad_svc)),
):
    """Partially update an owned control_seguridad (404 if not owned)."""
    updated = await control_seguridad_svc.update(
        db, entity.id, entity_in, scope={"user_id": current_user.id}
    )
    return success(ControlSeguridadRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_control_seguridad(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: ControlSeguridad = Depends(require_ownership(control_seguridad_svc)),
):
    """Delete an owned control_seguridad (404 if not owned)."""
    await control_seguridad_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "ControlSeguridad deleted"})
