"""EstadoCumplimiento CRUD endpoints — generated by scripts/new_entity.py."""

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db
from app.api.deps_ownership import require_ownership
from app.core.response import success
from app.models.user import User
from app.models.estado_cumplimiento import EstadoCumplimiento
from app.schemas.estado_cumplimiento import EstadoCumplimientoCreate, EstadoCumplimientoRead, EstadoCumplimientoUpdate
from app.services.estado_cumplimiento_service import estado_cumplimiento_svc

router = APIRouter()


@router.get("")
async def list_estado_cumplimientos(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List estado_cumplimientos owned by the current user."""
    items = await estado_cumplimiento_svc.list(db, filters={"user_id": current_user.id})
    return success([EstadoCumplimientoRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_estado_cumplimiento(
    entity: EstadoCumplimiento = Depends(require_ownership(estado_cumplimiento_svc)),
):
    """Get a single owned estado_cumplimiento by ID (404 if not owned)."""
    return success(EstadoCumplimientoRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_estado_cumplimiento(
    entity_in: EstadoCumplimientoCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new estado_cumplimiento for the current user."""
    entity = await estado_cumplimiento_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(EstadoCumplimientoRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_estado_cumplimiento(
    entity_in: EstadoCumplimientoUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: EstadoCumplimiento = Depends(require_ownership(estado_cumplimiento_svc)),
):
    """Partially update an owned estado_cumplimiento (404 if not owned)."""
    updated = await estado_cumplimiento_svc.update(
        db, entity.id, entity_in, scope={"user_id": current_user.id}
    )
    return success(EstadoCumplimientoRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_estado_cumplimiento(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: EstadoCumplimiento = Depends(require_ownership(estado_cumplimiento_svc)),
):
    """Delete an owned estado_cumplimiento (404 if not owned)."""
    await estado_cumplimiento_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "EstadoCumplimiento deleted"})
