"""EvidenciaRegulacion CRUD endpoints — generated by scripts/new_entity.py."""

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db
from app.api.deps_ownership import require_ownership
from app.core.response import success
from app.models.user import User
from app.models.evidencia_regulacion import EvidenciaRegulacion
from app.schemas.evidencia_regulacion import EvidenciaRegulacionCreate, EvidenciaRegulacionRead, EvidenciaRegulacionUpdate
from app.services.evidencia_regulacion_service import evidencia_regulacion_svc

router = APIRouter()


@router.get("")
async def list_evidencia_regulacions(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List evidencia_regulacions owned by the current user."""
    items = await evidencia_regulacion_svc.list(db, filters={"user_id": current_user.id})
    return success([EvidenciaRegulacionRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_evidencia_regulacion(
    entity: EvidenciaRegulacion = Depends(require_ownership(evidencia_regulacion_svc)),
):
    """Get a single owned evidencia_regulacion by ID (404 if not owned)."""
    return success(EvidenciaRegulacionRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_evidencia_regulacion(
    entity_in: EvidenciaRegulacionCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new evidencia_regulacion for the current user."""
    entity = await evidencia_regulacion_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(EvidenciaRegulacionRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_evidencia_regulacion(
    entity_in: EvidenciaRegulacionUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: EvidenciaRegulacion = Depends(require_ownership(evidencia_regulacion_svc)),
):
    """Partially update an owned evidencia_regulacion (404 if not owned)."""
    updated = await evidencia_regulacion_svc.update(
        db, entity.id, entity_in, scope={"user_id": current_user.id}
    )
    return success(EvidenciaRegulacionRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_evidencia_regulacion(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: EvidenciaRegulacion = Depends(require_ownership(evidencia_regulacion_svc)),
):
    """Delete an owned evidencia_regulacion (404 if not owned)."""
    await evidencia_regulacion_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "EvidenciaRegulacion deleted"})
