"""Gerencia CRUD endpoints — generated by scripts/new_entity.py."""

from __future__ import annotations

import csv
import hashlib
from io import StringIO

from fastapi import APIRouter, Depends, File, UploadFile
from fastapi.responses import Response
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_db, require_permission
from app.api.deps_ownership import require_ownership
from app.core.catalog_csv import gerencia_row, gerencia_template_body, read_csv_dict_rows
from app.core.permissions import P
from app.core.response import success
from app.models.gerencia import Gerencia
from app.models.user import User
from app.schemas.gerencia import GerenciaCreate, GerenciaRead, GerenciaUpdate
from app.services.audit_service import record as audit_record
from app.services.gerencia_service import gerencia_svc
from app.services.subdireccion_service import subdireccion_svc

router = APIRouter()


@router.get("/export.csv")
async def export_gerencias_csv(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.VIEW)),
):
    items = await gerencia_svc.list(db, filters={"user_id": current_user.id})
    buf = StringIO()
    writer = csv.writer(buf)
    writer.writerow(["id", "nombre", "descripcion", "subdireccion_id"])
    for r in items:
        writer.writerow([str(r.id), r.nombre, r.descripcion or "", str(r.subdireccion_id)])
    body = buf.getvalue()
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    await audit_record(
        db,
        action="gerencia.export_csv",
        entity_type="gerencia",
        entity_id=current_user.id,
        metadata={"rows": len(items), "sha256": digest, "format": "csv"},
    )
    return Response(
        content=body,
        media_type="text/csv; charset=utf-8",
        headers={"Content-Disposition": 'attachment; filename="gerencias.csv"'},
    )


@router.get("/import-template.csv")
async def download_gerencia_import_template(
    _db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.CREATE)),
):
    body = gerencia_template_body()
    return Response(
        content=body,
        media_type="text/csv; charset=utf-8",
        headers={"Content-Disposition": 'attachment; filename="gerencias_import_template.csv"'},
    )


@router.post("/import")
async def import_gerencias_csv(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.CREATE)),
    file: UploadFile = File(..., description="CSV con cabecera (ver import-template)"),
):
    raw = await file.read()
    digest = hashlib.sha256(raw).hexdigest()
    text = raw.decode("utf-8-sig")
    rows = read_csv_dict_rows(text)
    err_list: list[dict] = []
    created = 0

    for line_no, d in enumerate(rows, start=2):
        parsed, perr = gerencia_row(d, row=line_no)
        if perr is not None:
            err_list.append({"row": line_no, "message": perr})
            continue
        assert parsed is not None
        sub = await subdireccion_svc.get(
            db, parsed.subdireccion_id, scope={"user_id": current_user.id}
        )
        if not sub:
            err_list.append({"row": line_no, "message": "subdireccion_id inexistente o sin acceso"})
            continue
        if not parsed.nombre.strip():
            err_list.append({"row": line_no, "message": "nombre obligatorio"})
            continue
        await gerencia_svc.create(db, parsed, extra={"user_id": current_user.id})
        created += 1

    await audit_record(
        db,
        action="gerencia.import_csv",
        entity_type="gerencia",
        entity_id=current_user.id,
        metadata={
            "rows_in_file": len(rows),
            "created": created,
            "row_errors": len(err_list),
            "sha256": digest,
            "format": "csv",
        },
    )
    meta: dict = {"import_row_errors": len(err_list), "sha256": digest}
    if err_list:
        meta["import_errors"] = err_list
    return success({"created": created, "errors": err_list}, meta=meta)


@router.get("")
async def list_gerencias(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.VIEW)),
):
    """List gerencias owned by the current user."""
    items = await gerencia_svc.list(db, filters={"user_id": current_user.id})
    return success([GerenciaRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_gerencia(
    _: User = Depends(require_permission(P.CATALOGS.VIEW)),
    entity: Gerencia = Depends(require_ownership(gerencia_svc)),
):
    """Get a single owned gerencia by ID (404 if not owned)."""
    return success(GerenciaRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_gerencia(
    entity_in: GerenciaCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.CREATE)),
):
    """Create a new gerencia for the current user."""
    entity = await gerencia_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(GerenciaRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_gerencia(
    entity_in: GerenciaUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.EDIT)),
    entity: Gerencia = Depends(require_ownership(gerencia_svc)),
):
    """Partially update an owned gerencia (404 if not owned)."""
    updated = await gerencia_svc.update(db, entity.id, entity_in, scope={"user_id": current_user.id})
    return success(GerenciaRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_gerencia(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.DELETE)),
    entity: Gerencia = Depends(require_ownership(gerencia_svc)),
):
    """Delete an owned gerencia (404 if not owned)."""
    await gerencia_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "Gerencia deleted"})
