"""Gerencia CRUD endpoints — generated by scripts/new_entity.py."""

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_db, require_permission
from app.api.deps_ownership import require_ownership
from app.core.permissions import P
from app.core.response import success
from app.models.gerencia import Gerencia
from app.models.user import User
from app.schemas.gerencia import GerenciaCreate, GerenciaRead, GerenciaUpdate
from app.services.gerencia_service import gerencia_svc

router = APIRouter()


@router.get("")
async def list_gerencias(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.VIEW)),
):
    """List gerencias owned by the current user."""
    items = await gerencia_svc.list(db, filters={"user_id": current_user.id})
    return success([GerenciaRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_gerencia(
    _: User = Depends(require_permission(P.CATALOGS.VIEW)),
    entity: Gerencia = Depends(require_ownership(gerencia_svc)),
):
    """Get a single owned gerencia by ID (404 if not owned)."""
    return success(GerenciaRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_gerencia(
    entity_in: GerenciaCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.CREATE)),
):
    """Create a new gerencia for the current user."""
    entity = await gerencia_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(GerenciaRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_gerencia(
    entity_in: GerenciaUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.EDIT)),
    entity: Gerencia = Depends(require_ownership(gerencia_svc)),
):
    """Partially update an owned gerencia (404 if not owned)."""
    updated = await gerencia_svc.update(
        db, entity.id, entity_in, scope={"user_id": current_user.id}
    )
    return success(GerenciaRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_gerencia(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.DELETE)),
    entity: Gerencia = Depends(require_ownership(gerencia_svc)),
):
    """Delete an owned gerencia (404 if not owned)."""
    await gerencia_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "Gerencia deleted"})
