"""Iniciativa CRUD endpoints — generated by scripts/new_entity.py."""

from __future__ import annotations

import csv
import hashlib
from io import StringIO

from fastapi import APIRouter, Depends
from fastapi.responses import Response
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db
from app.api.deps_ownership import require_ownership
from app.core.response import success
from app.models.iniciativa import Iniciativa
from app.models.user import User
from app.schemas.iniciativa import IniciativaCreate, IniciativaRead, IniciativaUpdate
from app.services.audit_service import record as audit_record
from app.services.iniciativa_service import iniciativa_svc

router = APIRouter()


@router.get("/export.csv")
async def export_iniciativas_csv(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Exporta iniciativas del usuario a CSV y registra auditoría A7."""
    items = await iniciativa_svc.list(db, filters={"user_id": current_user.id})
    buf = StringIO()
    writer = csv.writer(buf)
    writer.writerow(
        [
            "id",
            "titulo",
            "tipo",
            "estado",
            "fecha_inicio",
            "fecha_fin_estimada",
        ]
    )
    for ini in items:
        writer.writerow(
            [
                str(ini.id),
                ini.titulo,
                ini.tipo,
                ini.estado,
                ini.fecha_inicio.isoformat() if ini.fecha_inicio else "",
                ini.fecha_fin_estimada.isoformat() if ini.fecha_fin_estimada else "",
            ]
        )
    body = buf.getvalue()
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    await audit_record(
        db,
        action="iniciativa.export_csv",
        entity_type="iniciativa",
        entity_id=current_user.id,
        metadata={"rows": len(items), "sha256": digest, "format": "csv"},
    )
    return Response(
        content=body,
        media_type="text/csv; charset=utf-8",
        headers={"Content-Disposition": 'attachment; filename="iniciativas.csv"'},
    )


@router.get("")
async def list_iniciativas(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    page: int = 1,
    page_size: int = 50,
):
    """List iniciativas owned by the current user (paginated)."""
    from sqlalchemy import func, select

    from app.core.response import paginated

    # Enforce pagination limits (S4: Rate limiting)
    page = max(1, page)
    page_size = min(max(1, page_size), 100)  # Cap at 100

    # Get paginated items
    stmt = (
        select(Iniciativa)
        .where(
            Iniciativa.user_id == current_user.id,
            Iniciativa.deleted_at.is_(None),
        )
        .order_by(Iniciativa.created_at.desc())
    )

    # Apply pagination
    stmt = stmt.offset((page - 1) * page_size).limit(page_size)
    result = await db.execute(stmt)
    items = result.scalars().all()

    # Get total count
    count_stmt = select(func.count(Iniciativa.id)).where(
        Iniciativa.user_id == current_user.id,
        Iniciativa.deleted_at.is_(None),
    )
    total_result = await db.execute(count_stmt)
    total = total_result.scalar_one_or_none() or 0

    return paginated(
        [IniciativaRead.model_validate(x).model_dump(mode="json") for x in items],
        page=page,
        page_size=page_size,
        total=total,
    )


@router.get("/{id}")
async def get_iniciativa(
    entity: Iniciativa = Depends(require_ownership(iniciativa_svc)),
):
    """Get a single owned iniciativa by ID (404 if not owned)."""
    return success(IniciativaRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_iniciativa(
    entity_in: IniciativaCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new iniciativa for the current user."""
    entity = await iniciativa_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(IniciativaRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_iniciativa(
    entity_in: IniciativaUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: Iniciativa = Depends(require_ownership(iniciativa_svc)),
):
    """Partially update an owned iniciativa (404 if not owned)."""
    updated = await iniciativa_svc.update(db, entity.id, entity_in, scope={"user_id": current_user.id})
    return success(IniciativaRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_iniciativa(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: Iniciativa = Depends(require_ownership(iniciativa_svc)),
):
    """Delete an owned iniciativa (404 if not owned)."""
    await iniciativa_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "Iniciativa deleted"})
