"""Iniciativa CRUD endpoints — generated by scripts/new_entity.py."""

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db
from app.api.deps_ownership import require_ownership
from app.core.response import success
from app.models.user import User
from app.models.iniciativa import Iniciativa
from app.schemas.iniciativa import IniciativaCreate, IniciativaRead, IniciativaUpdate
from app.services.iniciativa_service import iniciativa_svc

router = APIRouter()


@router.get("")
async def list_iniciativas(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List iniciativas owned by the current user."""
    items = await iniciativa_svc.list(db, filters={"user_id": current_user.id})
    return success([IniciativaRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_iniciativa(
    entity: Iniciativa = Depends(require_ownership(iniciativa_svc)),
):
    """Get a single owned iniciativa by ID (404 if not owned)."""
    return success(IniciativaRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_iniciativa(
    entity_in: IniciativaCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new iniciativa for the current user."""
    entity = await iniciativa_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(IniciativaRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_iniciativa(
    entity_in: IniciativaUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: Iniciativa = Depends(require_ownership(iniciativa_svc)),
):
    """Partially update an owned iniciativa (404 if not owned)."""
    updated = await iniciativa_svc.update(
        db, entity.id, entity_in, scope={"user_id": current_user.id}
    )
    return success(IniciativaRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_iniciativa(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: Iniciativa = Depends(require_ownership(iniciativa_svc)),
):
    """Delete an owned iniciativa (404 if not owned)."""
    await iniciativa_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "Iniciativa deleted"})
