"""OkrRevisionQ CRUD endpoints — generated by scripts/new_entity.py."""

from uuid import UUID

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db, require_permission
from app.api.deps_ownership import require_ownership
from app.core.permissions import P
from app.core.response import success
from app.models.okr_revision_q import OkrRevisionQ
from app.models.user import User
from app.schemas.okr_revision_q import (
    OkrRevisionApprovePayload,
    OkrRevisionEditadoPayload,
    OkrRevisionQCreate,
    OkrRevisionQRead,
    OkrRevisionQUpdate,
    OkrRevisionRejectPayload,
    OkrRevisionSubmitPayload,
)
from app.services.okr_revision_q_service import okr_revision_q_svc
from app.services.okr_workflow_service import approve_revision, reject_revision, submit_revision

router = APIRouter()


@router.get("")
async def list_okr_revision_qs(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List okr_revision_qs owned by the current user."""
    items = await okr_revision_q_svc.list(db, filters={"user_id": current_user.id})
    return success([OkrRevisionQRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_okr_revision_q(
    entity: OkrRevisionQ = Depends(require_ownership(okr_revision_q_svc)),
):
    """Get a single owned okr_revision_q by ID (404 if not owned)."""
    return success(OkrRevisionQRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_okr_revision_q(
    entity_in: OkrRevisionQCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new okr_revision_q for the current user."""
    entity = await okr_revision_q_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(OkrRevisionQRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_okr_revision_q(
    entity_in: OkrRevisionQUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: OkrRevisionQ = Depends(require_ownership(okr_revision_q_svc)),
):
    """Partially update an owned okr_revision_q (404 if not owned)."""
    updated = await okr_revision_q_svc.update(db, entity.id, entity_in, scope={"user_id": current_user.id})
    return success(OkrRevisionQRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_okr_revision_q(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: OkrRevisionQ = Depends(require_ownership(okr_revision_q_svc)),
):
    """Delete an owned okr_revision_q (404 if not owned)."""
    await okr_revision_q_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "OkrRevisionQ deleted"})


@router.post("/{id}/submit")
async def submit_okr_revision_q(
    id: UUID,
    payload: OkrRevisionSubmitPayload,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.PROGRAMS.VIEW)),
):
    revision = await submit_revision(
        db,
        revision_id=id,
        actor=current_user,
        comentario_colaborador=payload.comentario_colaborador,
    )
    return success(
        OkrRevisionQRead.model_validate(revision).model_dump(mode="json"),
        meta={"message": "Revisión enviada"},
    )


@router.post("/{id}/approve")
async def approve_okr_revision_q(
    id: UUID,
    payload: OkrRevisionApprovePayload,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.PROGRAMS.VIEW)),
):
    revision, score = await approve_revision(
        db,
        revision_id=id,
        actor=current_user,
        avance_validado=payload.avance_validado,
        feedback_evaluador=payload.feedback_evaluador,
        mark_as_editado=False,
    )
    return success(
        OkrRevisionQRead.model_validate(revision).model_dump(mode="json"),
        meta={"message": "Revisión aprobada", "score": score},
    )


@router.post("/{id}/edit")
async def edit_okr_revision_q(
    id: UUID,
    payload: OkrRevisionEditadoPayload,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.PROGRAMS.VIEW)),
):
    revision, score = await approve_revision(
        db,
        revision_id=id,
        actor=current_user,
        avance_validado=payload.avance_validado,
        feedback_evaluador=payload.feedback_evaluador,
        mark_as_editado=True,
    )
    return success(
        OkrRevisionQRead.model_validate(revision).model_dump(mode="json"),
        meta={"message": "Revisión editada y validada", "score": score},
    )


@router.post("/{id}/reject")
async def reject_okr_revision_q(
    id: UUID,
    payload: OkrRevisionRejectPayload,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.PROGRAMS.VIEW)),
):
    revision = await reject_revision(
        db,
        revision_id=id,
        actor=current_user,
        feedback_evaluador=payload.feedback_evaluador,
    )
    return success(
        OkrRevisionQRead.model_validate(revision).model_dump(mode="json"),
        meta={"message": "Revisión rechazada"},
    )
