"""OkrCierreQ CRUD endpoints — generated by scripts/new_entity.py."""

from uuid import UUID

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db, require_permission
from app.api.deps_ownership import require_ownership
from app.core.exceptions import BadRequestException
from app.core.permissions import P
from app.core.response import success
from app.models.okr_cierre_q import OkrCierreQ
from app.models.user import User
from app.schemas.okr_cierre_q import (
    OkrCierreQCreate,
    OkrCierreQRead,
    OkrCierreQUpdate,
    OkrCloseQuarterPayload,
)
from app.services.okr_cierre_q_service import okr_cierre_q_svc
from app.services.okr_workflow_service import close_quarter

router = APIRouter()


@router.get("")
async def list_okr_cierre_qs(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List okr_cierre_qs owned by the current user."""
    items = await okr_cierre_q_svc.list(db, filters={"user_id": current_user.id})
    return success([OkrCierreQRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_okr_cierre_q(
    entity: OkrCierreQ = Depends(require_ownership(okr_cierre_q_svc)),
):
    """Get a single owned okr_cierre_q by ID (404 if not owned)."""
    return success(OkrCierreQRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_okr_cierre_q(
    entity_in: OkrCierreQCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new okr_cierre_q for the current user."""
    entity = await okr_cierre_q_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(OkrCierreQRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_okr_cierre_q(
    entity_in: OkrCierreQUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: OkrCierreQ = Depends(require_ownership(okr_cierre_q_svc)),
):
    """Quarter close record is immutable once created."""
    raise BadRequestException("El cierre trimestral es inmutable")


@router.delete("/{id}")
async def delete_okr_cierre_q(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: OkrCierreQ = Depends(require_ownership(okr_cierre_q_svc)),
):
    """Quarter close record is immutable once created."""
    raise BadRequestException("El cierre trimestral es inmutable")


@router.post("/plans/{plan_id}/close")
async def close_okr_quarter(
    plan_id: UUID,
    payload: OkrCloseQuarterPayload,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.PROGRAMS.VIEW)),
):
    cierre, score = await close_quarter(
        db,
        plan_id=plan_id,
        quarter=payload.quarter,
        retroalimentacion_general=payload.retroalimentacion_general,
        actor=current_user,
    )
    return success(
        OkrCierreQRead.model_validate(cierre).model_dump(mode="json"),
        meta={"message": "Trimestre cerrado", "score": score},
    )
