"""OkrPlanAnual CRUD endpoints — generated by scripts/new_entity.py."""

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db
from app.api.deps_ownership import require_ownership
from app.core.response import success
from app.models.user import User
from app.models.okr_plan_anual import OkrPlanAnual
from app.schemas.okr_plan_anual import OkrPlanAnualCreate, OkrPlanAnualRead, OkrPlanAnualUpdate
from app.services.okr_plan_anual_service import okr_plan_anual_svc

router = APIRouter()


@router.get("")
async def list_okr_plan_anuals(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List okr_plan_anuals owned by the current user."""
    items = await okr_plan_anual_svc.list(db, filters={"user_id": current_user.id})
    return success([OkrPlanAnualRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_okr_plan_anual(
    entity: OkrPlanAnual = Depends(require_ownership(okr_plan_anual_svc)),
):
    """Get a single owned okr_plan_anual by ID (404 if not owned)."""
    return success(OkrPlanAnualRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_okr_plan_anual(
    entity_in: OkrPlanAnualCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new okr_plan_anual for the current user."""
    entity = await okr_plan_anual_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(OkrPlanAnualRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_okr_plan_anual(
    entity_in: OkrPlanAnualUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: OkrPlanAnual = Depends(require_ownership(okr_plan_anual_svc)),
):
    """Partially update an owned okr_plan_anual (404 if not owned)."""
    updated = await okr_plan_anual_svc.update(
        db, entity.id, entity_in, scope={"user_id": current_user.id}
    )
    return success(OkrPlanAnualRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_okr_plan_anual(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: OkrPlanAnual = Depends(require_ownership(okr_plan_anual_svc)),
):
    """Delete an owned okr_plan_anual (404 if not owned)."""
    await okr_plan_anual_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "OkrPlanAnual deleted"})
