"""OkrEvidencia CRUD endpoints — generated by scripts/new_entity.py."""

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db
from app.api.deps_ownership import require_ownership
from app.core.response import success
from app.models.okr_evidencia import OkrEvidencia
from app.models.user import User
from app.schemas.okr_evidencia import OkrEvidenciaCreate, OkrEvidenciaRead, OkrEvidenciaUpdate
from app.services.okr_evidencia_service import okr_evidencia_svc

router = APIRouter()


@router.get("")
async def list_okr_evidencias(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List okr_evidencias owned by the current user."""
    items = await okr_evidencia_svc.list(db, filters={"user_id": current_user.id})
    return success([OkrEvidenciaRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_okr_evidencia(
    entity: OkrEvidencia = Depends(require_ownership(okr_evidencia_svc)),
):
    """Get a single owned okr_evidencia by ID (404 if not owned)."""
    return success(OkrEvidenciaRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_okr_evidencia(
    entity_in: OkrEvidenciaCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new okr_evidencia for the current user."""
    entity = await okr_evidencia_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(OkrEvidenciaRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_okr_evidencia(
    entity_in: OkrEvidenciaUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: OkrEvidencia = Depends(require_ownership(okr_evidencia_svc)),
):
    """Partially update an owned okr_evidencia (404 if not owned)."""
    updated = await okr_evidencia_svc.update(
        db, entity.id, entity_in, scope={"user_id": current_user.id}
    )
    return success(OkrEvidenciaRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_okr_evidencia(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: OkrEvidencia = Depends(require_ownership(okr_evidencia_svc)),
):
    """Delete an owned okr_evidencia (404 if not owned)."""
    await okr_evidencia_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "OkrEvidencia deleted"})
