"""Organizacion CRUD endpoints — generated by scripts/new_entity.py."""

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_db, require_permission
from app.api.deps_ownership import require_ownership
from app.core.permissions import P
from app.core.response import success
from app.models.organizacion import Organizacion
from app.models.user import User
from app.schemas.organizacion import OrganizacionCreate, OrganizacionRead, OrganizacionUpdate
from app.services.organizacion_service import organizacion_svc

router = APIRouter()


@router.get("")
async def list_organizacions(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.VIEW)),
):
    """List organizacions owned by the current user."""
    items = await organizacion_svc.list(db, filters={"user_id": current_user.id})
    return success([OrganizacionRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_organizacion(
    _: User = Depends(require_permission(P.CATALOGS.VIEW)),
    entity: Organizacion = Depends(require_ownership(organizacion_svc)),
):
    """Get a single owned organizacion by ID (404 if not owned)."""
    return success(OrganizacionRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_organizacion(
    entity_in: OrganizacionCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.CREATE)),
):
    """Create a new organizacion for the current user."""
    entity = await organizacion_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(OrganizacionRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_organizacion(
    entity_in: OrganizacionUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.EDIT)),
    entity: Organizacion = Depends(require_ownership(organizacion_svc)),
):
    """Partially update an owned organizacion (404 if not owned)."""
    updated = await organizacion_svc.update(
        db, entity.id, entity_in, scope={"user_id": current_user.id}
    )
    return success(OrganizacionRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_organizacion(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.DELETE)),
    entity: Organizacion = Depends(require_ownership(organizacion_svc)),
):
    """Delete an owned organizacion (404 if not owned)."""
    await organizacion_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "Organizacion deleted"})
