"""Organizacion CRUD endpoints — generated by scripts/new_entity.py."""

from __future__ import annotations

import csv
import hashlib
from io import StringIO

from fastapi import APIRouter, Depends, File, UploadFile
from fastapi.responses import Response
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_db, require_permission
from app.api.deps_ownership import require_ownership
from app.core.catalog_csv import organizacion_row, organizacion_template_body, read_csv_dict_rows
from app.core.permissions import P
from app.core.response import success
from app.models.organizacion import Organizacion
from app.models.user import User
from app.schemas.organizacion import OrganizacionCreate, OrganizacionRead, OrganizacionUpdate
from app.services.audit_service import record as audit_record
from app.services.gerencia_service import gerencia_svc
from app.services.organizacion_service import organizacion_svc

router = APIRouter()


@router.get("/export.csv")
async def export_organizacions_csv(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.VIEW)),
):
    items = await organizacion_svc.list(db, filters={"user_id": current_user.id})
    buf = StringIO()
    writer = csv.writer(buf)
    writer.writerow(["id", "nombre", "codigo", "descripcion", "gerencia_id", "plataforma", "url_base", "responsable"])
    for r in items:
        writer.writerow(
            [
                str(r.id),
                r.nombre,
                r.codigo,
                r.descripcion or "",
                str(r.gerencia_id),
                r.plataforma,
                r.url_base or "",
                r.responsable or "",
            ]
        )
    body = buf.getvalue()
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    await audit_record(
        db,
        action="organizacion.export_csv",
        entity_type="organizacion",
        entity_id=current_user.id,
        metadata={"rows": len(items), "sha256": digest, "format": "csv"},
    )
    return Response(
        content=body,
        media_type="text/csv; charset=utf-8",
        headers={"Content-Disposition": 'attachment; filename="organizaciones.csv"'},
    )


@router.get("/import-template.csv")
async def download_organizacion_import_template(
    _db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.CREATE)),
):
    body = organizacion_template_body()
    return Response(
        content=body,
        media_type="text/csv; charset=utf-8",
        headers={"Content-Disposition": 'attachment; filename="organizaciones_import_template.csv"'},
    )


@router.post("/import")
async def import_organizacions_csv(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.CREATE)),
    file: UploadFile = File(..., description="CSV con cabecera (ver import-template)"),
):
    raw = await file.read()
    digest = hashlib.sha256(raw).hexdigest()
    text = raw.decode("utf-8-sig")
    rows = read_csv_dict_rows(text)
    err_list: list[dict] = []
    created = 0
    seen_codes: set[str] = set()
    existing = {x.codigo for x in await organizacion_svc.list(db, filters={"user_id": current_user.id})}

    for line_no, d in enumerate(rows, start=2):
        parsed, perr = organizacion_row(d, row=line_no)
        if perr is not None:
            err_list.append({"row": line_no, "message": perr})
            continue
        assert parsed is not None
        g = await gerencia_svc.get(db, parsed.gerencia_id, scope={"user_id": current_user.id})
        if not g:
            err_list.append({"row": line_no, "message": "gerencia_id inexistente o sin acceso"})
            continue
        if parsed.codigo in seen_codes:
            err_list.append({"row": line_no, "message": "codigo duplicado en el archivo"})
            continue
        if parsed.codigo in existing:
            err_list.append({"row": line_no, "message": "codigo ya existe en tu catálogo"})
            continue
        if not parsed.nombre.strip():
            err_list.append({"row": line_no, "message": "nombre obligatorio"})
            continue
        await organizacion_svc.create(db, parsed, extra={"user_id": current_user.id})
        created += 1
        seen_codes.add(parsed.codigo)
        existing.add(parsed.codigo)

    await audit_record(
        db,
        action="organizacion.import_csv",
        entity_type="organizacion",
        entity_id=current_user.id,
        metadata={
            "rows_in_file": len(rows),
            "created": created,
            "row_errors": len(err_list),
            "sha256": digest,
            "format": "csv",
        },
    )
    meta: dict = {"import_row_errors": len(err_list), "sha256": digest}
    if err_list:
        meta["import_errors"] = err_list
    return success({"created": created, "errors": err_list}, meta=meta)


@router.get("")
async def list_organizacions(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.VIEW)),
):
    """List organizacions owned by the current user."""
    items = await organizacion_svc.list(db, filters={"user_id": current_user.id})
    return success([OrganizacionRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_organizacion(
    _: User = Depends(require_permission(P.CATALOGS.VIEW)),
    entity: Organizacion = Depends(require_ownership(organizacion_svc)),
):
    """Get a single owned organizacion by ID (404 if not owned)."""
    return success(OrganizacionRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_organizacion(
    entity_in: OrganizacionCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.CREATE)),
):
    """Create a new organizacion for the current user."""
    entity = await organizacion_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(OrganizacionRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_organizacion(
    entity_in: OrganizacionUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.EDIT)),
    entity: Organizacion = Depends(require_ownership(organizacion_svc)),
):
    """Partially update an owned organizacion (404 if not owned)."""
    updated = await organizacion_svc.update(db, entity.id, entity_in, scope={"user_id": current_user.id})
    return success(OrganizacionRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_organizacion(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.DELETE)),
    entity: Organizacion = Depends(require_ownership(organizacion_svc)),
):
    """Delete an owned organizacion (404 if not owned)."""
    await organizacion_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "Organizacion deleted"})
