"""ProgramaSourceCode CRUD endpoints — generated by scripts/new_entity.py."""

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db
from app.api.deps_ownership import require_ownership
from app.core.response import success
from app.models.programa_source_code import ProgramaSourceCode
from app.models.user import User
from app.schemas.programa_source_code import ProgramaSourceCodeCreate, ProgramaSourceCodeRead, ProgramaSourceCodeUpdate
from app.services.programa_source_code_service import programa_source_code_svc

router = APIRouter()


@router.get("")
async def list_programa_source_codes(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List programa_source_codes owned by the current user."""
    items = await programa_source_code_svc.list(db, filters={"user_id": current_user.id})
    return success([ProgramaSourceCodeRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_programa_source_code(
    entity: ProgramaSourceCode = Depends(require_ownership(programa_source_code_svc)),
):
    """Get a single owned programa_source_code by ID (404 if not owned)."""
    return success(ProgramaSourceCodeRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_programa_source_code(
    entity_in: ProgramaSourceCodeCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new programa_source_code for the current user."""
    entity = await programa_source_code_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(ProgramaSourceCodeRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_programa_source_code(
    entity_in: ProgramaSourceCodeUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: ProgramaSourceCode = Depends(require_ownership(programa_source_code_svc)),
):
    """Partially update an owned programa_source_code (404 if not owned)."""
    updated = await programa_source_code_svc.update(
        db, entity.id, entity_in, scope={"user_id": current_user.id}
    )
    return success(ProgramaSourceCodeRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_programa_source_code(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: ProgramaSourceCode = Depends(require_ownership(programa_source_code_svc)),
):
    """Delete an owned programa_source_code (404 if not owned)."""
    await programa_source_code_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "ProgramaSourceCode deleted"})
