"""ProgramaThreatModeling CRUD endpoints — generated by scripts/new_entity.py."""

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db
from app.api.deps_ownership import require_ownership
from app.core.response import success
from app.models.programa_threat_modeling import ProgramaThreatModeling
from app.models.user import User
from app.schemas.programa_threat_modeling import (
    ProgramaThreatModelingCreate,
    ProgramaThreatModelingRead,
    ProgramaThreatModelingUpdate,
)
from app.services.audit_service import record as audit_record
from app.services.programa_threat_modeling_service import programa_threat_modeling_svc

router = APIRouter()


@router.get("")
async def list_programa_threat_modelings(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List programa_threat_modelings owned by the current user."""
    items = await programa_threat_modeling_svc.list(db, filters={"user_id": current_user.id})
    return success([ProgramaThreatModelingRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_programa_threat_modeling(
    entity: ProgramaThreatModeling = Depends(require_ownership(programa_threat_modeling_svc)),
):
    """Get a single owned programa_threat_modeling by ID (404 if not owned)."""
    return success(ProgramaThreatModelingRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_programa_threat_modeling(
    entity_in: ProgramaThreatModelingCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new programa_threat_modeling for the current user."""
    entity = await programa_threat_modeling_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(ProgramaThreatModelingRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_programa_threat_modeling(
    entity_in: ProgramaThreatModelingUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: ProgramaThreatModeling = Depends(require_ownership(programa_threat_modeling_svc)),
):
    """Partially update an owned programa_threat_modeling (404 if not owned)."""
    updated = await programa_threat_modeling_svc.update(db, entity.id, entity_in, scope={"user_id": current_user.id})
    return success(ProgramaThreatModelingRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_programa_threat_modeling(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: ProgramaThreatModeling = Depends(require_ownership(programa_threat_modeling_svc)),
):
    """Delete an owned programa_threat_modeling (404 if not owned)."""
    await programa_threat_modeling_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "ProgramaThreatModeling deleted"})


@router.post("/{id}/clonar", status_code=201)
async def clonar_programa_threat_modeling(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: ProgramaThreatModeling = Depends(require_ownership(programa_threat_modeling_svc)),
):
    """Clona un programa Threat Modeling existente con sus metadatos (sin sesiones).

    El clon se crea con el mismo activo/servicio, descripción y estado,
    incrementando el año en 1 y marcando el nombre con '(Copia)'.
    """
    clone_in = ProgramaThreatModelingCreate(
        activo_web_id=entity.activo_web_id,
        servicio_id=entity.servicio_id,
        nombre=f"{entity.nombre} (Copia)",
        ano=entity.ano + 1,
        descripcion=entity.descripcion,
        estado="Activo",
    )
    clone = await programa_threat_modeling_svc.create(db, clone_in, extra={"user_id": current_user.id})
    await audit_record(
        db,
        action="programa_threat_modeling.clonar",
        entity_type="programa_threat_modeling",
        entity_id=clone.id,
        metadata={"fuente_id": str(entity.id), "nombre_clon": clone.nombre},
    )
    return success(ProgramaThreatModelingRead.model_validate(clone).model_dump(mode="json"))
