"""ProgramaSast CRUD endpoints — generated by scripts/new_entity.py."""

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db
from app.api.deps_ownership import require_ownership
from app.core.response import success
from app.models.user import User
from app.models.programa_sast import ProgramaSast
from app.schemas.programa_sast import ProgramaSastCreate, ProgramaSastRead, ProgramaSastUpdate
from app.services.programa_sast_service import programa_sast_svc

router = APIRouter()


@router.get("")
async def list_programa_sasts(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List programa_sasts owned by the current user."""
    items = await programa_sast_svc.list(db, filters={"user_id": current_user.id})
    return success([ProgramaSastRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_programa_sast(
    entity: ProgramaSast = Depends(require_ownership(programa_sast_svc)),
):
    """Get a single owned programa_sast by ID (404 if not owned)."""
    return success(ProgramaSastRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_programa_sast(
    entity_in: ProgramaSastCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new programa_sast for the current user."""
    entity = await programa_sast_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(ProgramaSastRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_programa_sast(
    entity_in: ProgramaSastUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: ProgramaSast = Depends(require_ownership(programa_sast_svc)),
):
    """Partially update an owned programa_sast (404 if not owned)."""
    updated = await programa_sast_svc.update(
        db, entity.id, entity_in, scope={"user_id": current_user.id}
    )
    return success(ProgramaSastRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_programa_sast(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: ProgramaSast = Depends(require_ownership(programa_sast_svc)),
):
    """Delete an owned programa_sast (404 if not owned)."""
    await programa_sast_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "ProgramaSast deleted"})
