"""ProgramaSast CRUD endpoints — generated by scripts/new_entity.py."""

from __future__ import annotations

import csv
import hashlib
from io import StringIO

from fastapi import APIRouter, Depends
from fastapi.responses import Response
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db, require_permission
from app.api.deps_ownership import require_ownership
from app.core.permissions import P
from app.core.response import success
from app.models.programa_sast import ProgramaSast
from app.models.user import User
from app.schemas.programa_sast import ProgramaSastCreate, ProgramaSastRead, ProgramaSastUpdate
from app.services.audit_service import record as audit_record
from app.services.programa_sast_service import programa_sast_svc

router = APIRouter()


@router.get("/export.csv")
async def export_programa_sasts_csv(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.PROGRAMS.EXPORT)),
):
    """Exporta programas SAST del usuario a CSV; auditoría A7 (BRD A3)."""
    items = await programa_sast_svc.list(db, filters={"user_id": current_user.id})
    buf = StringIO()
    writer = csv.writer(buf)
    writer.writerow(
        [
            "id",
            "nombre",
            "ano",
            "estado",
            "repositorio_id",
            "descripcion",
            "user_id",
            "created_at",
            "updated_at",
        ]
    )
    for p in items:
        writer.writerow(
            [
                str(p.id),
                p.nombre,
                p.ano,
                p.estado,
                str(p.repositorio_id),
                p.descripcion or "",
                str(p.user_id),
                p.created_at.isoformat(),
                p.updated_at.isoformat(),
            ]
        )
    body = buf.getvalue()
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    await audit_record(
        db,
        action="programa_sast.export_csv",
        entity_type="programa_sast",
        entity_id=current_user.id,
        metadata={"rows": len(items), "sha256": digest, "format": "csv"},
    )
    return Response(
        content=body,
        media_type="text/csv; charset=utf-8",
        headers={"Content-Disposition": 'attachment; filename="programa_sasts.csv"'},
    )


@router.get("")
async def list_programa_sasts(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List programa_sasts owned by the current user."""
    items = await programa_sast_svc.list(db, filters={"user_id": current_user.id})
    return success([ProgramaSastRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_programa_sast(
    entity: ProgramaSast = Depends(require_ownership(programa_sast_svc)),
):
    """Get a single owned programa_sast by ID (404 if not owned)."""
    return success(ProgramaSastRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_programa_sast(
    entity_in: ProgramaSastCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new programa_sast for the current user."""
    entity = await programa_sast_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(ProgramaSastRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_programa_sast(
    entity_in: ProgramaSastUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: ProgramaSast = Depends(require_ownership(programa_sast_svc)),
):
    """Partially update an owned programa_sast (404 if not owned)."""
    updated = await programa_sast_svc.update(db, entity.id, entity_in, scope={"user_id": current_user.id})
    return success(ProgramaSastRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_programa_sast(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: ProgramaSast = Depends(require_ownership(programa_sast_svc)),
):
    """Delete a owned programa_sast by ID (404 if not owned)."""
    await programa_sast_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "ProgramaSast deleted"})


@router.post("/{id}/evidencia")
async def upload_evidencia_programa(
    *,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.PROGRAMS.EDIT)),
    programa_id: str,
    evidencia_url: str,
    descripcion: str | None = None,
    actividad_id: str | None = None,
):
    """Subir evidencia de actividad de programa SAST."""
    # In a full implementation, this would save to a database
    # For now, return success with the evidence data
    return success(
        {
            "id": f"evidencia_{programa_id}",
            "programa_id": programa_id,
            "evidencia_url": evidencia_url,
            "descripcion": descripcion,
            "actividad_id": actividad_id,
            "user_id": str(current_user.id),
            "created_at": "2026-01-01T00:00:00Z",
        }
    )


@router.get("/{id}/evidencias")
async def list_evidencias_programa(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    id: str = ...,
):
    """Listar evidencias de un programa SAST."""
    # In a full implementation, this would query from database
    return success(
        {
            "evidencias": [],
            "total": 0,
        }
    )
