"""ProgramaSourceCode CRUD endpoints — generated by scripts/new_entity.py."""

import uuid

from fastapi import APIRouter, Depends, Query
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db
from app.api.deps_ownership import require_ownership
from app.core.response import paginated, success
from app.models.programa_source_code import ProgramaSourceCode
from app.models.user import User
from app.schemas.programa_source_code import ProgramaSourceCodeCreate, ProgramaSourceCodeRead, ProgramaSourceCodeUpdate
from app.services.audit_service import record as audit_record
from app.services.programa_source_code_service import programa_source_code_svc

router = APIRouter()


@router.get("")
async def list_programa_source_codes(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    page: int = 1,
    page_size: int = 50,
    estado: str | None = Query(None, max_length=80, description="Filtro P7 / F3"),
    q: str | None = Query(None, max_length=200, description="Búsqueda en nombre"),
):
    """List programa source code con paginación y filtros (P7 / §13.2)."""
    page = max(1, page)
    page_size = min(max(1, page_size), 100)
    base_conds = [
        ProgramaSourceCode.user_id == current_user.id,
        ProgramaSourceCode.deleted_at.is_(None),
    ]
    if estado and estado.strip():
        base_conds.append(ProgramaSourceCode.estado == estado.strip())
    if q and q.strip():
        base_conds.append(ProgramaSourceCode.nombre.ilike(f"%{q.strip()}%"))

    cstmt = select(func.count()).select_from(ProgramaSourceCode).where(*base_conds)
    total = (await db.execute(cstmt)).scalar_one()
    stmt = (
        select(ProgramaSourceCode)
        .where(*base_conds)
        .order_by(ProgramaSourceCode.created_at.desc())
        .offset((page - 1) * page_size)
        .limit(page_size)
    )
    rows = (await db.execute(stmt)).scalars().all()
    return paginated(
        [ProgramaSourceCodeRead.model_validate(x).model_dump(mode="json") for x in rows],
        page=page,
        page_size=page_size,
        total=total,
    )


@router.get("/{id}/checklist-avance")
async def checklist_avance_programa_source(
    id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """P7: % de controles con última revisión en estatus de cumplimiento (evidencia + resultado)."""
    from app.models.revision_source_code import RevisionSourceCode

    p = await programa_source_code_svc.get(db, id, scope={"user_id": current_user.id})
    if p is None:
        from app.core.exceptions import NotFoundException

        raise NotFoundException("Programa not found")
    rstmt = select(RevisionSourceCode).where(
        RevisionSourceCode.programa_sc_id == id,
        RevisionSourceCode.user_id == current_user.id,
        RevisionSourceCode.deleted_at.is_(None),
    )
    revs = list((await db.execute(rstmt)).scalars().all())
    latest: dict[uuid.UUID, object] = {}
    for r in revs:
        k = r.control_sc_id
        if k not in latest or r.fecha_revision > latest[k].fecha_revision:  # type: ignore[index]
            latest[k] = r
    ok_set = {"Cumple", "Completado", "Cerrado", "Remediado", "Aceptable"}
    n = len(latest)
    n_ok = sum(1 for v in latest.values() if (getattr(v, "resultado", "") or "") in ok_set)
    pct = round(100.0 * n_ok / n, 2) if n else 0.0
    return success(
        {
            "controles_con_revision": n,
            "controles_cumplidos": n_ok,
            "avance_checklist_pct": pct,
            "cierre_operativo_100": n > 0 and n_ok == n,
        }
    )


@router.get("/{id}")
async def get_programa_source_code(
    entity: ProgramaSourceCode = Depends(require_ownership(programa_source_code_svc)),
):
    """Get a single owned programa_source_code by ID (404 if not owned)."""
    return success(ProgramaSourceCodeRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_programa_source_code(
    entity_in: ProgramaSourceCodeCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new programa_source_code for the current user."""
    entity = await programa_source_code_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(ProgramaSourceCodeRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_programa_source_code(
    entity_in: ProgramaSourceCodeUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: ProgramaSourceCode = Depends(require_ownership(programa_source_code_svc)),
):
    """Partially update an owned programa_source_code (404 if not owned)."""
    updated = await programa_source_code_svc.update(db, entity.id, entity_in, scope={"user_id": current_user.id})
    return success(ProgramaSourceCodeRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_programa_source_code(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: ProgramaSourceCode = Depends(require_ownership(programa_source_code_svc)),
):
    """Delete an owned programa_source_code (404 if not owned)."""
    await programa_source_code_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "ProgramaSourceCode deleted"})


@router.post("/{id}/clonar", status_code=201)
async def clonar_programa_source_code(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: ProgramaSourceCode = Depends(require_ownership(programa_source_code_svc)),
):
    """Clona un programa Source Code existente con sus metadatos (sin revisiones).

    El clon se crea con el mismo repositorio, descripción y metadatos,
    incrementando el año en 1 y marcando el nombre con '(Copia)'.
    """
    clone_in = ProgramaSourceCodeCreate(
        repositorio_id=entity.repositorio_id,
        nombre=f"{entity.nombre} (Copia)",
        ano=entity.ano + 1,
        descripcion=entity.descripcion,
        estado="Activo",
        metadatos_motor=entity.metadatos_motor,
    )
    clone = await programa_source_code_svc.create(db, clone_in, extra={"user_id": current_user.id})
    await audit_record(
        db,
        action="programa_source_code.clonar",
        entity_type="programa_source_code",
        entity_id=clone.id,
        metadata={"fuente_id": str(entity.id), "nombre_clon": clone.nombre},
    )
    return success(ProgramaSourceCodeRead.model_validate(clone).model_dump(mode="json"))
