"""ProgramaDast CRUD endpoints — generated by scripts/new_entity.py."""

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db
from app.api.deps_ownership import require_ownership
from app.core.response import success
from app.models.user import User
from app.models.programa_dast import ProgramaDast
from app.schemas.programa_dast import ProgramaDastCreate, ProgramaDastRead, ProgramaDastUpdate
from app.services.programa_dast_service import programa_dast_svc

router = APIRouter()


@router.get("")
async def list_programa_dasts(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List programa_dasts owned by the current user."""
    items = await programa_dast_svc.list(db, filters={"user_id": current_user.id})
    return success([ProgramaDastRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_programa_dast(
    entity: ProgramaDast = Depends(require_ownership(programa_dast_svc)),
):
    """Get a single owned programa_dast by ID (404 if not owned)."""
    return success(ProgramaDastRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_programa_dast(
    entity_in: ProgramaDastCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new programa_dast for the current user."""
    entity = await programa_dast_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(ProgramaDastRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_programa_dast(
    entity_in: ProgramaDastUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: ProgramaDast = Depends(require_ownership(programa_dast_svc)),
):
    """Partially update an owned programa_dast (404 if not owned)."""
    updated = await programa_dast_svc.update(
        db, entity.id, entity_in, scope={"user_id": current_user.id}
    )
    return success(ProgramaDastRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_programa_dast(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: ProgramaDast = Depends(require_ownership(programa_dast_svc)),
):
    """Delete an owned programa_dast (404 if not owned)."""
    await programa_dast_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "ProgramaDast deleted"})
