"""RegulacionControl CRUD endpoints — generated by scripts/new_entity.py."""

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db
from app.api.deps_ownership import require_ownership
from app.core.response import success
from app.models.regulacion_control import RegulacionControl
from app.models.user import User
from app.schemas.regulacion_control import RegulacionControlCreate, RegulacionControlRead, RegulacionControlUpdate
from app.services.regulacion_control_service import regulacion_control_svc

router = APIRouter()


@router.get("")
async def list_regulacion_controls(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List regulacion_controls owned by the current user."""
    items = await regulacion_control_svc.list(db, filters={"user_id": current_user.id})
    return success([RegulacionControlRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_regulacion_control(
    entity: RegulacionControl = Depends(require_ownership(regulacion_control_svc)),
):
    """Get a single owned regulacion_control by ID (404 if not owned)."""
    return success(RegulacionControlRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_regulacion_control(
    entity_in: RegulacionControlCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new regulacion_control for the current user."""
    entity = await regulacion_control_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(RegulacionControlRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_regulacion_control(
    entity_in: RegulacionControlUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: RegulacionControl = Depends(require_ownership(regulacion_control_svc)),
):
    """Partially update an owned regulacion_control (404 if not owned)."""
    updated = await regulacion_control_svc.update(db, entity.id, entity_in, scope={"user_id": current_user.id})
    return success(RegulacionControlRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_regulacion_control(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: RegulacionControl = Depends(require_ownership(regulacion_control_svc)),
):
    """Delete an owned regulacion_control (404 if not owned)."""
    await regulacion_control_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "RegulacionControl deleted"})
