"""Repositorio CRUD endpoints — generated by scripts/new_entity.py."""

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db
from app.api.deps_ownership import require_ownership
from app.core.response import success
from app.models.repositorio import Repositorio
from app.models.user import User
from app.schemas.repositorio import RepositorioCreate, RepositorioRead, RepositorioUpdate
from app.services.repositorio_service import repositorio_svc

router = APIRouter()


@router.get("")
async def list_repositorios(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List repositorios owned by the current user."""
    items = await repositorio_svc.list(db, filters={"user_id": current_user.id})
    return success([RepositorioRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_repositorio(
    entity: Repositorio = Depends(require_ownership(repositorio_svc)),
):
    """Get a single owned repositorio by ID (404 if not owned)."""
    return success(RepositorioRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_repositorio(
    entity_in: RepositorioCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new repositorio for the current user."""
    entity = await repositorio_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(RepositorioRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_repositorio(
    entity_in: RepositorioUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: Repositorio = Depends(require_ownership(repositorio_svc)),
):
    """Partially update an owned repositorio (404 if not owned)."""
    updated = await repositorio_svc.update(
        db, entity.id, entity_in, scope={"user_id": current_user.id}
    )
    return success(RepositorioRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_repositorio(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: Repositorio = Depends(require_ownership(repositorio_svc)),
):
    """Delete an owned repositorio (404 if not owned)."""
    await repositorio_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "Repositorio deleted"})
