"""Repositorio CRUD endpoints — generated by scripts/new_entity.py."""

from __future__ import annotations

import csv
import hashlib
from io import StringIO

from fastapi import APIRouter, Depends, File, HTTPException, UploadFile
from fastapi.responses import Response
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db, require_permission, validate_fk_exists
from app.api.deps_ownership import require_ownership
from app.core.csv_duplicate_detector import detect_duplicates
from app.core.inventory_csv import (
    read_csv_dict_rows,
    repositorio_row_to_create,
    repositorio_template_body,
)
from app.core.permissions import P
from app.core.response import success
from app.models.celula import Celula
from app.models.organizacion import Organizacion
from app.models.repositorio import Repositorio
from app.models.subdireccion import Subdireccion
from app.models.user import User
from app.schemas.repositorio import RepositorioCreate, RepositorioRead, RepositorioUpdate
from app.services.audit_service import record as audit_record
from app.services.repositorio_service import repositorio_svc

router = APIRouter()


@router.get("/export.csv")
async def export_repositorios_csv(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.INVENTORY.REPOS_EXPORT)),
):
    """Exporta repositorios del usuario a CSV; auditoría A7 (BRD A3)."""
    items = await repositorio_svc.list(db, filters={"user_id": current_user.id})
    buf = StringIO()
    writer = csv.writer(buf)
    writer.writerow(
        [
            "id",
            "nombre",
            "url",
            "plataforma",
            "rama_default",
            "activo",
            "organizacion_id",
            "celula_id",
            "subdireccion_responsable_id",
            "responsable_nombre",
            "responsable_contacto",
        ]
    )
    for r in items:
        writer.writerow(
            [
                str(r.id),
                r.nombre,
                r.url,
                r.plataforma,
                r.rama_default,
                r.activo,
                str(r.organizacion_id),
                str(r.celula_id) if r.celula_id else "",
                str(r.subdireccion_responsable_id) if r.subdireccion_responsable_id else "",
                r.responsable_nombre or "",
                r.responsable_contacto or "",
            ]
        )
    body = buf.getvalue()
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    await audit_record(
        db,
        action="repositorio.export_csv",
        entity_type="repositorio",
        entity_id=current_user.id,
        metadata={"rows": len(items), "sha256": digest, "format": "csv"},
    )
    return Response(
        content=body,
        media_type="text/csv; charset=utf-8",
        headers={"Content-Disposition": 'attachment; filename="repositorios.csv"'},
    )


@router.get("/import-template.csv")
async def download_repositorio_import_template(
    _db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.INVENTORY.REPOS_IMPORT)),
):
    """Plantilla CSV para import masivo (BRD A2)."""
    body = repositorio_template_body()
    return Response(
        content=body,
        media_type="text/csv; charset=utf-8",
        headers={"Content-Disposition": 'attachment; filename="repositorios_import_template.csv"'},
    )


@router.post("/import")
async def import_repositorios_csv(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.INVENTORY.REPOS_IMPORT)),
    file: UploadFile = File(..., description="CSV con cabecera (ver import-template)"),
):
    """Importa repositorios desde CSV; filas con error se omiten; auditoría A7."""
    raw = await file.read()
    digest = hashlib.sha256(raw).hexdigest()
    text = raw.decode("utf-8-sig")
    rows = read_csv_dict_rows(text)
    err_list: list[dict] = []
    warnings: list[str] = []
    created = 0
    seen_urls: dict[str, int] = {}
    existing_repos = await repositorio_svc.list(db, filters={"user_id": current_user.id})
    existing = {str(x.url) for x in existing_repos}

    # Semantic duplicate detection against both the batch and existing DB records
    dup_report = detect_duplicates(
        rows,
        key_fields=["nombre", "url"],
        threshold=0.85,
        existing_values={"nombre": [r.nombre for r in existing_repos], "url": [str(r.url) for r in existing_repos]},
    )
    warnings.extend(dup_report.to_warnings())

    for line_no, d in enumerate(rows, start=2):
        parsed, perr = repositorio_row_to_create(d, row=line_no)
        if perr is not None:
            err_list.append({"row": line_no, "message": perr})
            continue
        assert parsed is not None
        ukey = str(parsed.url)
        if ukey in seen_urls:
            err_list.append(
                {
                    "row": line_no,
                    "message": f"url duplicada en el archivo (primera en fila {seen_urls[ukey]})",
                }
            )
            continue
        if ukey in existing:
            err_list.append({"row": line_no, "message": "url ya existe en tu inventario"})
            continue
        try:
            if parsed.celula_id is not None:
                await validate_fk_exists(db, Celula, parsed.celula_id, "Célula")
                celula = await db.get(Celula, parsed.celula_id)
                if celula is None:
                    raise HTTPException(status_code=422, detail="Célula no encontrada")
                if parsed.organizacion_id is not None and parsed.organizacion_id != celula.organizacion_id:
                    raise HTTPException(
                        status_code=422,
                        detail="organizacion_id debe coincidir con la organización de la célula",
                    )
                parsed.organizacion_id = celula.organizacion_id
            elif parsed.organizacion_id is not None:
                await validate_fk_exists(db, Organizacion, parsed.organizacion_id, "Organización")
            else:
                raise HTTPException(
                    status_code=422,
                    detail="organizacion_id es obligatorio cuando no se envía celula_id",
                )
            if parsed.subdireccion_responsable_id is not None:
                await validate_fk_exists(
                    db,
                    Subdireccion,
                    parsed.subdireccion_responsable_id,
                    "Subdirección responsable",
                )
        except HTTPException as exc:
            if exc.status_code == 422:
                d = exc.detail
                msg = d if isinstance(d, str) else str(d)
                err_list.append({"row": line_no, "message": msg})
                continue
            raise
        await repositorio_svc.create(db, parsed, extra={"user_id": current_user.id})
        created += 1
        seen_urls[ukey] = line_no
        existing.add(ukey)

    await audit_record(
        db,
        action="repositorio.import_csv",
        entity_type="repositorio",
        entity_id=current_user.id,
        metadata={
            "rows_in_file": len(rows),
            "created": created,
            "row_errors": len(err_list),
            "sha256": digest,
            "format": "csv",
        },
    )
    meta = {
        "import_row_errors": len(err_list),
        "sha256": digest,
        "duplicate_warnings": len(warnings),
    }
    if err_list:
        meta["import_errors"] = err_list
    if warnings:
        meta["duplicate_warnings_detail"] = warnings
    return success(
        {"created": created, "errors": err_list, "warnings": warnings},
        meta=meta,
    )


@router.get("")
async def list_repositorios(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List repositorios owned by the current user."""
    items = await repositorio_svc.list(db, filters={"user_id": current_user.id})
    return success([RepositorioRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_repositorio(
    entity: Repositorio = Depends(require_ownership(repositorio_svc)),
):
    """Get a single owned repositorio by ID (404 if not owned)."""
    return success(RepositorioRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_repositorio(
    entity_in: RepositorioCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new repositorio for the current user."""
    if entity_in.organizacion_id is not None:
        await validate_fk_exists(db, Organizacion, entity_in.organizacion_id, "Organización")
    if entity_in.celula_id is not None:
        await validate_fk_exists(db, Celula, entity_in.celula_id, "Célula")
    if entity_in.subdireccion_responsable_id is not None:
        await validate_fk_exists(
            db,
            Subdireccion,
            entity_in.subdireccion_responsable_id,
            "Subdirección responsable",
        )
    payload = entity_in.model_copy()
    if payload.celula_id is not None:
        celula = await db.get(Celula, payload.celula_id)
        if celula is None:
            raise HTTPException(status_code=422, detail="Célula no encontrada")
        if payload.organizacion_id is not None and payload.organizacion_id != celula.organizacion_id:
            raise HTTPException(
                status_code=422,
                detail="organizacion_id debe coincidir con la organización de la célula",
            )
        payload.organizacion_id = celula.organizacion_id
    elif payload.organizacion_id is None:
        raise HTTPException(status_code=422, detail="organizacion_id es obligatorio cuando no se envía celula_id")

    entity = await repositorio_svc.create(db, payload, extra={"user_id": current_user.id})
    return success(RepositorioRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_repositorio(
    entity_in: RepositorioUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: Repositorio = Depends(require_ownership(repositorio_svc)),
):
    """Partially update an owned repositorio (404 if not owned)."""
    if entity_in.organizacion_id is not None:
        await validate_fk_exists(db, Organizacion, entity_in.organizacion_id, "Organización")
    if entity_in.celula_id is not None:
        await validate_fk_exists(db, Celula, entity_in.celula_id, "Célula")
    if entity_in.subdireccion_responsable_id is not None:
        await validate_fk_exists(
            db,
            Subdireccion,
            entity_in.subdireccion_responsable_id,
            "Subdirección responsable",
        )
    updated = await repositorio_svc.update(db, entity.id, entity_in, scope={"user_id": current_user.id})
    return success(RepositorioRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_repositorio(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: Repositorio = Depends(require_ownership(repositorio_svc)),
):
    """Delete an owned repositorio (404 if not owned)."""
    await repositorio_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "Repositorio deleted"})
