"""Servicio CRUD endpoints — generated by scripts/new_entity.py."""

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db
from app.api.deps_ownership import require_ownership
from app.core.response import success
from app.models.servicio import Servicio
from app.models.user import User
from app.schemas.servicio import ServicioCreate, ServicioRead, ServicioUpdate
from app.services.servicio_service import servicio_svc

router = APIRouter()


@router.get("")
async def list_servicios(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List servicios owned by the current user."""
    items = await servicio_svc.list(db, filters={"user_id": current_user.id})
    return success([ServicioRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_servicio(
    entity: Servicio = Depends(require_ownership(servicio_svc)),
):
    """Get a single owned servicio by ID (404 if not owned)."""
    return success(ServicioRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_servicio(
    entity_in: ServicioCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new servicio for the current user."""
    entity = await servicio_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(ServicioRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_servicio(
    entity_in: ServicioUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: Servicio = Depends(require_ownership(servicio_svc)),
):
    """Partially update an owned servicio (404 if not owned)."""
    updated = await servicio_svc.update(
        db, entity.id, entity_in, scope={"user_id": current_user.id}
    )
    return success(ServicioRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_servicio(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: Servicio = Depends(require_ownership(servicio_svc)),
):
    """Delete an owned servicio (404 if not owned)."""
    await servicio_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "Servicio deleted"})
