"""ServicioReguladoRegistro CRUD endpoints — generated by scripts/new_entity.py."""

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db
from app.api.deps_ownership import require_ownership
from app.core.response import success
from app.models.user import User
from app.models.servicio_regulado_registro import ServicioReguladoRegistro
from app.schemas.servicio_regulado_registro import ServicioReguladoRegistroCreate, ServicioReguladoRegistroRead, ServicioReguladoRegistroUpdate
from app.services.servicio_regulado_registro_service import servicio_regulado_registro_svc

router = APIRouter()


@router.get("")
async def list_servicio_regulado_registros(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List servicio_regulado_registros owned by the current user."""
    items = await servicio_regulado_registro_svc.list(db, filters={"user_id": current_user.id})
    return success([ServicioReguladoRegistroRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_servicio_regulado_registro(
    entity: ServicioReguladoRegistro = Depends(require_ownership(servicio_regulado_registro_svc)),
):
    """Get a single owned servicio_regulado_registro by ID (404 if not owned)."""
    return success(ServicioReguladoRegistroRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_servicio_regulado_registro(
    entity_in: ServicioReguladoRegistroCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new servicio_regulado_registro for the current user."""
    entity = await servicio_regulado_registro_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(ServicioReguladoRegistroRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_servicio_regulado_registro(
    entity_in: ServicioReguladoRegistroUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: ServicioReguladoRegistro = Depends(require_ownership(servicio_regulado_registro_svc)),
):
    """Partially update an owned servicio_regulado_registro (404 if not owned)."""
    updated = await servicio_regulado_registro_svc.update(
        db, entity.id, entity_in, scope={"user_id": current_user.id}
    )
    return success(ServicioReguladoRegistroRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_servicio_regulado_registro(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: ServicioReguladoRegistro = Depends(require_ownership(servicio_regulado_registro_svc)),
):
    """Delete an owned servicio_regulado_registro (404 if not owned)."""
    await servicio_regulado_registro_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "ServicioReguladoRegistro deleted"})
