"""Subdireccion CRUD endpoints — generated by scripts/new_entity.py."""

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db
from app.api.deps_ownership import require_ownership
from app.core.response import success
from app.models.user import User
from app.models.subdireccion import Subdireccion
from app.schemas.subdireccion import SubdireccionCreate, SubdireccionRead, SubdireccionUpdate
from app.services.subdireccion_service import subdireccion_svc

router = APIRouter()


@router.get("")
async def list_subdireccions(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List subdireccions owned by the current user."""
    items = await subdireccion_svc.list(db, filters={"user_id": current_user.id})
    return success([SubdireccionRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_subdireccion(
    entity: Subdireccion = Depends(require_ownership(subdireccion_svc)),
):
    """Get a single owned subdireccion by ID (404 if not owned)."""
    return success(SubdireccionRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_subdireccion(
    entity_in: SubdireccionCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new subdireccion for the current user."""
    entity = await subdireccion_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(SubdireccionRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_subdireccion(
    entity_in: SubdireccionUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: Subdireccion = Depends(require_ownership(subdireccion_svc)),
):
    """Partially update an owned subdireccion (404 if not owned)."""
    updated = await subdireccion_svc.update(
        db, entity.id, entity_in, scope={"user_id": current_user.id}
    )
    return success(SubdireccionRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_subdireccion(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: Subdireccion = Depends(require_ownership(subdireccion_svc)),
):
    """Delete an owned subdireccion (404 if not owned)."""
    await subdireccion_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "Subdireccion deleted"})
