"""Subdireccion CRUD endpoints — generated by scripts/new_entity.py."""

from __future__ import annotations

import csv
import hashlib
from io import StringIO

from fastapi import APIRouter, Depends, File, UploadFile
from fastapi.responses import Response
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_db, require_permission
from app.api.deps_ownership import require_ownership
from app.core.catalog_csv import (
    read_csv_dict_rows,
    subdireccion_row,
    subdireccion_template_body,
)
from app.core.exceptions import NotFoundException
from app.core.permissions import P
from app.core.response import success
from app.models.subdireccion import Subdireccion
from app.models.user import User
from app.schemas.subdireccion import SubdireccionCreate, SubdireccionRead, SubdireccionUpdate
from app.services.audit_service import record as audit_record
from app.services.direccion_service import direccion_svc
from app.services.subdireccion_service import subdireccion_svc

router = APIRouter()


@router.get("/export.csv")
async def export_subdirecciones_csv(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.VIEW)),
):
    """Exporta subdirecciones a CSV (BRD A3)."""
    items = await subdireccion_svc.list(db, filters={"user_id": current_user.id})
    buf = StringIO()
    writer = csv.writer(buf)
    writer.writerow(["id", "nombre", "codigo", "descripcion", "director_nombre", "director_contacto"])
    for r in items:
        writer.writerow(
            [
                str(r.id),
                r.nombre,
                r.codigo,
                r.descripcion or "",
                r.director_nombre or "",
                r.director_contacto or "",
            ]
        )
    body = buf.getvalue()
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    await audit_record(
        db,
        action="subdireccion.export_csv",
        entity_type="subdireccion",
        entity_id=current_user.id,
        metadata={"rows": len(items), "sha256": digest, "format": "csv"},
    )
    return Response(
        content=body,
        media_type="text/csv; charset=utf-8",
        headers={"Content-Disposition": 'attachment; filename="subdirecciones.csv"'},
    )


@router.get("/import-template.csv")
async def download_subdireccion_import_template(
    _db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.CREATE)),
):
    """Plantilla CSV import masivo (BRD A2)."""
    body = subdireccion_template_body()
    return Response(
        content=body,
        media_type="text/csv; charset=utf-8",
        headers={"Content-Disposition": 'attachment; filename="subdirecciones_import_template.csv"'},
    )


@router.post("/import")
async def import_subdirecciones_csv(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.CREATE)),
    file: UploadFile = File(..., description="CSV con cabecera (ver import-template)"),
):
    """Importa subdirecciones; filas erróneas se reportan (BRD A2)."""
    raw = await file.read()
    digest = hashlib.sha256(raw).hexdigest()
    text = raw.decode("utf-8-sig")
    rows = read_csv_dict_rows(text)
    err_list: list[dict] = []
    created = 0
    seen_codigo: dict[str, int] = {}
    existing = {x.codigo for x in await subdireccion_svc.list(db, filters={"user_id": current_user.id})}

    for line_no, d in enumerate(rows, start=2):
        parsed, perr = subdireccion_row(d, row=line_no)
        if perr is not None:
            err_list.append({"row": line_no, "message": perr})
            continue
        assert parsed is not None
        if parsed.direccion_id:
            direccion = await direccion_svc.get(db, parsed.direccion_id, scope={"user_id": current_user.id})
            if not direccion:
                err_list.append({"row": line_no, "message": "direccion_id inexistente o sin acceso"})
                continue
        ck = parsed.codigo
        if ck in seen_codigo:
            err_list.append(
                {
                    "row": line_no,
                    "message": f"codigo duplicado en archivo (primera fila {seen_codigo[ck]})",
                }
            )
            continue
        if ck in existing:
            err_list.append({"row": line_no, "message": "codigo ya existe en tu catálogo"})
            continue
        if not parsed.nombre.strip():
            err_list.append({"row": line_no, "message": "nombre obligatorio"})
            continue
        await subdireccion_svc.create(db, parsed, extra={"user_id": current_user.id})
        created += 1
        seen_codigo[ck] = line_no
        existing.add(ck)

    await audit_record(
        db,
        action="subdireccion.import_csv",
        entity_type="subdireccion",
        entity_id=current_user.id,
        metadata={
            "rows_in_file": len(rows),
            "created": created,
            "row_errors": len(err_list),
            "sha256": digest,
            "format": "csv",
        },
    )
    meta: dict = {"import_row_errors": len(err_list), "sha256": digest}
    if err_list:
        meta["import_errors"] = err_list
    return success({"created": created, "errors": err_list}, meta=meta)


@router.get("")
async def list_subdireccions(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.VIEW)),
):
    """List subdireccions owned by the current user."""
    items = await subdireccion_svc.list(db, filters={"user_id": current_user.id})
    return success([SubdireccionRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_subdireccion(
    _: User = Depends(require_permission(P.CATALOGS.VIEW)),
    entity: Subdireccion = Depends(require_ownership(subdireccion_svc)),
):
    """Get a single owned subdireccion by ID (404 if not owned)."""
    return success(SubdireccionRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_subdireccion(
    entity_in: SubdireccionCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.CREATE)),
):
    """Create a new subdireccion for the current user."""
    if entity_in.direccion_id:
        direccion = await direccion_svc.get(db, entity_in.direccion_id, scope={"user_id": current_user.id})
        if not direccion:
            raise NotFoundException("direccion_id inexistente o sin acceso")
    entity = await subdireccion_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(SubdireccionRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_subdireccion(
    entity_in: SubdireccionUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.EDIT)),
    entity: Subdireccion = Depends(require_ownership(subdireccion_svc)),
):
    """Partially update an owned subdireccion (404 if not owned)."""
    if entity_in.direccion_id:
        direccion = await direccion_svc.get(db, entity_in.direccion_id, scope={"user_id": current_user.id})
        if not direccion:
            raise NotFoundException("direccion_id inexistente o sin acceso")
    updated = await subdireccion_svc.update(db, entity.id, entity_in, scope={"user_id": current_user.id})
    return success(SubdireccionRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_subdireccion(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.DELETE)),
    entity: Subdireccion = Depends(require_ownership(subdireccion_svc)),
):
    """Delete an owned subdireccion (404 if not owned)."""
    await subdireccion_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "Subdireccion deleted"})
