"""TipoPrueba CRUD endpoints — generated by scripts/new_entity.py."""

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db
from app.api.deps_ownership import require_ownership
from app.core.response import success
from app.models.tipo_prueba import TipoPrueba
from app.models.user import User
from app.schemas.tipo_prueba import TipoPruebaCreate, TipoPruebaRead, TipoPruebaUpdate
from app.services.tipo_prueba_service import tipo_prueba_svc

router = APIRouter()


@router.get("")
async def list_tipo_pruebas(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List tipo_pruebas owned by the current user."""
    items = await tipo_prueba_svc.list(db, filters={"user_id": current_user.id})
    return success([TipoPruebaRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_tipo_prueba(
    entity: TipoPrueba = Depends(require_ownership(tipo_prueba_svc)),
):
    """Get a single owned tipo_prueba by ID (404 if not owned)."""
    return success(TipoPruebaRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_tipo_prueba(
    entity_in: TipoPruebaCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new tipo_prueba for the current user."""
    entity = await tipo_prueba_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(TipoPruebaRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_tipo_prueba(
    entity_in: TipoPruebaUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: TipoPrueba = Depends(require_ownership(tipo_prueba_svc)),
):
    """Partially update an owned tipo_prueba (404 if not owned)."""
    updated = await tipo_prueba_svc.update(
        db, entity.id, entity_in, scope={"user_id": current_user.id}
    )
    return success(TipoPruebaRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_tipo_prueba(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: TipoPrueba = Depends(require_ownership(tipo_prueba_svc)),
):
    """Delete an owned tipo_prueba (404 if not owned)."""
    await tipo_prueba_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "TipoPrueba deleted"})
