"""TipoPrueba CRUD endpoints — generated by scripts/new_entity.py."""

from __future__ import annotations

import csv
import hashlib
from io import StringIO

from fastapi import APIRouter, Depends, File, UploadFile
from fastapi.responses import Response
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db, require_permission
from app.api.deps_ownership import require_ownership
from app.core.catalog_csv import read_csv_dict_rows, tipo_prueba_row, tipo_prueba_template_body
from app.core.permissions import P
from app.core.response import success
from app.models.tipo_prueba import TipoPrueba
from app.models.user import User
from app.schemas.tipo_prueba import TipoPruebaCreate, TipoPruebaRead, TipoPruebaUpdate
from app.services.audit_service import record as audit_record
from app.services.tipo_prueba_service import tipo_prueba_svc

router = APIRouter()


@router.get("/export.csv")
async def export_tipo_pruebas_csv(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.VIEW)),
):
    items = await tipo_prueba_svc.list(db, filters={"user_id": current_user.id})
    buf = StringIO()
    writer = csv.writer(buf)
    writer.writerow(["id", "nombre", "categoria", "descripcion"])
    for r in items:
        writer.writerow([str(r.id), r.nombre, r.categoria, r.descripcion or ""])
    body = buf.getvalue()
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    await audit_record(
        db,
        action="tipo_prueba.export_csv",
        entity_type="tipo_prueba",
        entity_id=current_user.id,
        metadata={"rows": len(items), "sha256": digest, "format": "csv"},
    )
    return Response(
        content=body,
        media_type="text/csv; charset=utf-8",
        headers={"Content-Disposition": 'attachment; filename="tipo_pruebas.csv"'},
    )


@router.get("/import-template.csv")
async def download_tipo_prueba_import_template(
    _db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.CREATE)),
):
    body = tipo_prueba_template_body()
    return Response(
        content=body,
        media_type="text/csv; charset=utf-8",
        headers={"Content-Disposition": 'attachment; filename="tipo_pruebas_import_template.csv"'},
    )


@router.post("/import")
async def import_tipo_pruebas_csv(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.CATALOGS.CREATE)),
    file: UploadFile = File(..., description="CSV con cabecera (ver import-template)"),
):
    raw = await file.read()
    digest = hashlib.sha256(raw).hexdigest()
    text = raw.decode("utf-8-sig")
    rows = read_csv_dict_rows(text)
    err_list: list[dict] = []
    created = 0

    for line_no, d in enumerate(rows, start=2):
        parsed, perr = tipo_prueba_row(d, row=line_no)
        if perr is not None:
            err_list.append({"row": line_no, "message": perr})
            continue
        assert parsed is not None
        if not parsed.nombre.strip():
            err_list.append({"row": line_no, "message": "nombre obligatorio"})
            continue
        await tipo_prueba_svc.create(db, parsed, extra={"user_id": current_user.id})
        created += 1

    await audit_record(
        db,
        action="tipo_prueba.import_csv",
        entity_type="tipo_prueba",
        entity_id=current_user.id,
        metadata={
            "rows_in_file": len(rows),
            "created": created,
            "row_errors": len(err_list),
            "sha256": digest,
            "format": "csv",
        },
    )
    meta: dict = {"import_row_errors": len(err_list), "sha256": digest}
    if err_list:
        meta["import_errors"] = err_list
    return success({"created": created, "errors": err_list}, meta=meta)


@router.get("")
async def list_tipo_pruebas(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List tipo_pruebas owned by the current user."""
    items = await tipo_prueba_svc.list(db, filters={"user_id": current_user.id})
    return success([TipoPruebaRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_tipo_prueba(
    entity: TipoPrueba = Depends(require_ownership(tipo_prueba_svc)),
):
    """Get a single owned tipo_prueba by ID (404 if not owned)."""
    return success(TipoPruebaRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_tipo_prueba(
    entity_in: TipoPruebaCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new tipo_prueba for the current user."""
    entity = await tipo_prueba_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(TipoPruebaRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_tipo_prueba(
    entity_in: TipoPruebaUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: TipoPrueba = Depends(require_ownership(tipo_prueba_svc)),
):
    """Partially update an owned tipo_prueba (404 if not owned)."""
    updated = await tipo_prueba_svc.update(db, entity.id, entity_in, scope={"user_id": current_user.id})
    return success(TipoPruebaRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_tipo_prueba(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: TipoPrueba = Depends(require_ownership(tipo_prueba_svc)),
):
    """Delete an owned tipo_prueba (404 if not owned)."""
    await tipo_prueba_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "TipoPrueba deleted"})
