"""Vulnerabilidad CRUD endpoints — generated by scripts/new_entity.py."""

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user, get_db
from app.api.deps_ownership import require_ownership
from app.core.response import success
from app.models.user import User
from app.models.vulnerabilidad import Vulnerabilidad
from app.schemas.vulnerabilidad import VulnerabilidadCreate, VulnerabilidadRead, VulnerabilidadUpdate
from app.services.vulnerabilidad_service import vulnerabilidad_svc

router = APIRouter()


@router.get("")
async def list_vulnerabilidads(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """List vulnerabilidads owned by the current user."""
    items = await vulnerabilidad_svc.list(db, filters={"user_id": current_user.id})
    return success([VulnerabilidadRead.model_validate(x).model_dump(mode="json") for x in items])


@router.get("/{id}")
async def get_vulnerabilidad(
    entity: Vulnerabilidad = Depends(require_ownership(vulnerabilidad_svc)),
):
    """Get a single owned vulnerabilidad by ID (404 if not owned)."""
    return success(VulnerabilidadRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_vulnerabilidad(
    entity_in: VulnerabilidadCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new vulnerabilidad for the current user."""
    entity = await vulnerabilidad_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(VulnerabilidadRead.model_validate(entity).model_dump(mode="json"))


@router.patch("/{id}")
async def update_vulnerabilidad(
    entity_in: VulnerabilidadUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: Vulnerabilidad = Depends(require_ownership(vulnerabilidad_svc)),
):
    """Partially update an owned vulnerabilidad (404 if not owned)."""
    updated = await vulnerabilidad_svc.update(
        db, entity.id, entity_in, scope={"user_id": current_user.id}
    )
    return success(VulnerabilidadRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_vulnerabilidad(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: Vulnerabilidad = Depends(require_ownership(vulnerabilidad_svc)),
):
    """Delete an owned vulnerabilidad (404 if not owned)."""
    await vulnerabilidad_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "Vulnerabilidad deleted"})
