"""Vulnerabilidad CRUD endpoints — generated by scripts/new_entity.py."""

from __future__ import annotations

import csv
import hashlib
import json
from datetime import UTC, datetime
from io import StringIO
from typing import Literal
from uuid import UUID

from fastapi import APIRouter, Depends, File, Query, UploadFile
from fastapi.responses import Response
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import ensure_user_permissions, get_current_user, get_db, require_permission
from app.api.deps_ownership import require_ownership
from app.core.exceptions import NotFoundException, ValidationException
from app.core.logging import logger
from app.core.permissions import P
from app.core.response import success
from app.models.historial_vulnerabilidad import HistorialVulnerabilidad
from app.models.user import User
from app.models.vulnerabilidad import Vulnerabilidad
from app.schemas.historial_vulnerabilidad import HistorialVulnerabilidadRead
from app.schemas.vulnerabilidad import (
    VulnerabilidadBulkActionRequest,
    VulnerabilidadBulkActionResult,
    VulnerabilidadCreate,
    VulnerabilidadIATriageRead,
    VulnerabilidadIATriageRequest,
    VulnerabilidadRead,
    VulnerabilidadUpdate,
)
from app.services.audit_service import record as audit_record
from app.services.ia_provider import run_prompt
from app.services.vulnerabilidad_ia_triage_hints import get_motor_triage_hints
from app.services.vulnerabilidad_service import vulnerabilidad_svc

router = APIRouter()


@router.get("/config/flujo")
async def get_vulnerabilidad_flujo_config(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """BRD D1: catálogo y transiciones (lectura) para alinear UI y validaciones server-side."""
    from app.services.json_setting import get_json_setting
    from app.services.vulnerabilidad_flujo import parse_estatus_catalog

    raw = await get_json_setting(db, "catalogo.estatus_vulnerabilidad", [])
    return success({"estatus": parse_estatus_catalog(raw)})


def _parse_triage_output(
    content: str,
) -> tuple[Literal["false_positive", "likely_real", "needs_review"], float, str, str | None]:
    """Parse model output into normalized triage fields."""
    verdict = "needs_review"
    confidence = 0.5
    rationale = content.strip()[:1200] or "Sin detalle."
    suggested_state: str | None = None

    try:
        data = json.loads(content)
        if isinstance(data, dict):
            raw_verdict = str(data.get("verdict", "")).strip().lower()
            if raw_verdict in {"false_positive", "likely_real", "needs_review"}:
                verdict = raw_verdict
            raw_conf = data.get("confidence")
            if isinstance(raw_conf, (int, float)):
                confidence = max(0.0, min(1.0, float(raw_conf)))
            raw_rationale = data.get("rationale")
            if isinstance(raw_rationale, str) and raw_rationale.strip():
                rationale = raw_rationale.strip()[:1200]
            raw_state = data.get("suggested_state")
            if isinstance(raw_state, str) and raw_state.strip():
                suggested_state = raw_state.strip()[:128]
            return verdict, confidence, rationale, suggested_state
    except json.JSONDecodeError:
        pass

    lowered = content.lower()
    if "false_positive" in lowered or "falso positivo" in lowered:
        verdict = "false_positive"
    elif "likely_real" in lowered or "real vulnerability" in lowered:
        verdict = "likely_real"
    return verdict, confidence, rationale, suggested_state


@router.get("/export.csv")
async def export_vulnerabilidades_csv(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.VULNERABILITIES.EXPORT)),
):
    """Exporta hallazgos del usuario a CSV; deja huella en auditoría (A7)."""
    items = await vulnerabilidad_svc.list(db, filters={"user_id": current_user.id})
    buf = StringIO()
    writer = csv.writer(buf)
    writer.writerow(
        [
            "id",
            "titulo",
            "fuente",
            "severidad",
            "estado",
            "cwe_id",
            "owasp_categoria",
            "fecha_limite_sla",
        ]
    )
    for v in items:
        writer.writerow(
            [
                str(v.id),
                v.titulo,
                v.fuente,
                v.severidad,
                v.estado,
                v.cwe_id or "",
                v.owasp_categoria or "",
                v.fecha_limite_sla.isoformat() if v.fecha_limite_sla else "",
            ]
        )
    body = buf.getvalue()
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    await audit_record(
        db,
        action="vulnerabilidad.export_csv",
        entity_type="vulnerabilidad",
        entity_id=current_user.id,
        metadata={
            "rows": len(items),
            "sha256": digest,
            "format": "csv",
        },
    )
    return Response(
        content=body,
        media_type="text/csv; charset=utf-8",
        headers={
            "Content-Disposition": 'attachment; filename="vulnerabilidades.csv"',
        },
    )


@router.get("/import/template/{motor}")
async def download_vulnerabilidad_import_template(
    motor: str,
    current_user: User = Depends(get_current_user),
):
    """Descarga CSV vacío con cabeceras esperadas para importación por motor (spec 23)."""
    from app.services.vulnerabilidad_bulk_import import resolve_fuente

    resolve_fuente(motor)
    headers = [
        "titulo",
        "severidad",
        "estado",
        "descripcion",
        "repositorio_id",
        "activo_web_id",
        "servicio_id",
        "aplicacion_movil_id",
        "cwe_id",
        "owasp_categoria",
        "cvss_score",
        "responsable_id",
    ]
    buf = StringIO()
    writer = csv.writer(buf)
    writer.writerow(headers)
    body = buf.getvalue()
    safe_motor = motor.strip().lower().replace("/", "_")
    return Response(
        content=body,
        media_type="text/csv; charset=utf-8",
        headers={
            "Content-Disposition": f'attachment; filename="template_import_{safe_motor}.csv"',
        },
    )


@router.post("/import/{motor}")
async def import_vulnerabilidades_bulk(
    motor: str,
    file: UploadFile = File(..., description="CSV UTF-8 con cabecera"),
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.VULNERABILITIES.IMPORT)),
    default_repositorio_id: UUID | None = Query(None),
    default_activo_web_id: UUID | None = Query(None),
    default_servicio_id: UUID | None = Query(None),
    default_aplicacion_movil_id: UUID | None = Query(None),
):
    """Importación masiva por motor (SAST, DAST, …). Una fila por hallazgo; activo por columnas o defaults."""
    from app.services.vulnerabilidad_bulk_import import import_vulnerabilidades_from_csv

    raw = await file.read()
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        text = raw.decode("latin-1", errors="replace")

    out = await import_vulnerabilidades_from_csv(
        db,
        user_id=current_user.id,
        motor_key=motor,
        csv_text=text,
        default_repositorio_id=default_repositorio_id,
        default_activo_web_id=default_activo_web_id,
        default_servicio_id=default_servicio_id,
        default_aplicacion_movil_id=default_aplicacion_movil_id,
    )
    await audit_record(
        db,
        action="vulnerabilidad.import_bulk",
        entity_type="vulnerabilidad",
        entity_id=current_user.id,
        metadata={"motor": motor.lower(), "created": out.get("created", 0), "error_rows": len(out.get("errors", []))},
    )
    return success(out)


def _parse_created_after(s: str | None) -> datetime | None:
    if not s or not str(s).strip():
        return None
    t = str(s).strip()
    try:
        return datetime.fromisoformat(t.replace("Z", "+00:00"))
    except ValueError:
        return None


@router.get("")
async def list_vulnerabilidads(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    page: int = 1,
    page_size: int = 50,
    sort: Literal["created_at", "titulo", "fuente", "severidad", "sla_dias", "updated_at"] = "created_at",
    order: Literal["asc", "desc"] = "desc",
    q: str | None = None,
    search: str | None = None,
    severidad: str | None = None,
    estado: str | None = None,
    fuente: str | None = None,
    sla: str | None = None,
    reincidencia: bool = False,
    created_after: str | None = Query(default=None, description="ISO-8601: filtra created_at >="),
    celula_id: UUID | None = Query(default=None, description="Activo (repo/web) asignado a esta célula."),
    organizacion_id: UUID | None = Query(
        default=None,
        description="Activo cuya célula pertenece a esta organización.",
    ),
):
    """List vulnerabilidads del usuario: paginación, búsqueda, filtros y orden (BRD §13.2 P20)."""
    from sqlalchemy import and_, case, func, or_, select

    from app.core.response import paginated
    from app.models.activo_web import ActivoWeb
    from app.models.celula import Celula
    from app.models.repositorio import Repositorio

    page = max(1, page)
    page_size = min(max(1, page_size), 100)

    base_where = [
        Vulnerabilidad.user_id == current_user.id,
        Vulnerabilidad.deleted_at.is_(None),
    ]
    term = (q or search or "").strip()
    if term:
        like = f"%{term}%"
        base_where.append(
            or_(
                Vulnerabilidad.titulo.ilike(like),
                Vulnerabilidad.descripcion.ilike(like),
                Vulnerabilidad.fuente.ilike(like),
            )
        )
    if severidad:
        base_where.append(Vulnerabilidad.severidad == severidad)
    if estado:
        base_where.append(Vulnerabilidad.estado == estado)
    if fuente:
        base_where.append(Vulnerabilidad.fuente == fuente)
    ca = _parse_created_after(created_after)
    if ca is not None:
        base_where.append(Vulnerabilidad.created_at >= ca)

    if celula_id is not None:
        repo_sub = select(Repositorio.id).where(
            Repositorio.celula_id == celula_id,
            Repositorio.user_id == current_user.id,
            Repositorio.deleted_at.is_(None),
        )
        aw_sub = select(ActivoWeb.id).where(
            ActivoWeb.celula_id == celula_id,
            ActivoWeb.user_id == current_user.id,
            ActivoWeb.deleted_at.is_(None),
        )
        base_where.append(
            or_(
                Vulnerabilidad.repositorio_id.in_(repo_sub),
                Vulnerabilidad.activo_web_id.in_(aw_sub),
            )
        )
    elif organizacion_id is not None:
        repo_sub = (
            select(Repositorio.id)
            .join(Celula, Celula.id == Repositorio.celula_id)
            .where(
                Celula.organizacion_id == organizacion_id,
                Repositorio.user_id == current_user.id,
                Repositorio.deleted_at.is_(None),
                Celula.deleted_at.is_(None),
            )
        )
        aw_sub = (
            select(ActivoWeb.id)
            .join(Celula, Celula.id == ActivoWeb.celula_id)
            .where(
                Celula.organizacion_id == organizacion_id,
                ActivoWeb.user_id == current_user.id,
                ActivoWeb.deleted_at.is_(None),
                Celula.deleted_at.is_(None),
            )
        )
        base_where.append(
            or_(
                Vulnerabilidad.repositorio_id.in_(repo_sub),
                Vulnerabilidad.activo_web_id.in_(aw_sub),
            )
        )

    if sla == "vencida":
        now = datetime.now(UTC)
        base_where.extend(
            [
                Vulnerabilidad.fecha_limite_sla.isnot(None),
                Vulnerabilidad.fecha_limite_sla < now,
            ]
        )

    if reincidencia:
        dup_cwe = (
            select(Vulnerabilidad.cwe_id)
            .where(
                Vulnerabilidad.user_id == current_user.id,
                Vulnerabilidad.deleted_at.is_(None),
                Vulnerabilidad.cwe_id.isnot(None),
            )
            .group_by(Vulnerabilidad.cwe_id)
            .having(func.count() > 1)
        )
        base_where.append(Vulnerabilidad.cwe_id.in_(dup_cwe))

    where_all = and_(*base_where)

    sev_rank = case(
        (Vulnerabilidad.severidad == "Critica", 4),
        (Vulnerabilidad.severidad == "Alta", 3),
        (Vulnerabilidad.severidad == "Media", 2),
        (Vulnerabilidad.severidad == "Baja", 1),
        else_=0,
    )
    # severidad: order desc => Crítica > Alta > … (rank 4 → 1)
    order_cols: list = []
    if sort == "titulo":
        order_cols = [Vulnerabilidad.titulo.asc() if order == "asc" else Vulnerabilidad.titulo.desc()]
    elif sort == "fuente":
        order_cols = [Vulnerabilidad.fuente.asc() if order == "asc" else Vulnerabilidad.fuente.desc()]
    elif sort == "severidad":
        order_cols = [sev_rank.desc() if order == "desc" else sev_rank.asc()]
    elif sort == "sla_dias":
        fl = Vulnerabilidad.fecha_limite_sla
        order_cols = [fl.asc().nulls_last()] if order == "asc" else [fl.desc().nulls_last()]
    elif sort == "updated_at":
        order_cols = [Vulnerabilidad.updated_at.asc() if order == "asc" else Vulnerabilidad.updated_at.desc()]
    else:
        order_cols = [Vulnerabilidad.created_at.asc() if order == "asc" else Vulnerabilidad.created_at.desc()]

    stmt = select(Vulnerabilidad).where(where_all).order_by(*order_cols)
    stmt = stmt.offset((page - 1) * page_size).limit(page_size)
    result = await db.execute(stmt)
    items = result.scalars().all()

    count_stmt = select(func.count(Vulnerabilidad.id)).where(where_all)
    total_result = await db.execute(count_stmt)
    total = int(total_result.scalar_one_or_none() or 0)

    return paginated(
        [VulnerabilidadRead.model_validate(x).model_dump(mode="json") for x in items],
        page=page,
        page_size=page_size,
        total=total,
    )


@router.post("/bulk-action")
async def bulk_action_vulnerabilidades(
    body: VulnerabilidadBulkActionRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Acciones masivas sobre hallazgos propios: estado, responsable o borrado lógico (spec 37)."""
    scope = {"user_id": current_user.id}
    processed = 0
    errors: list[str] = []

    if body.action == "delete":
        await ensure_user_permissions(db, current_user, P.VULNERABILITIES.DELETE)
    else:
        await ensure_user_permissions(db, current_user, P.VULNERABILITIES.EDIT)

    for vid in body.ids:
        try:
            if body.action == "delete":
                ok = await vulnerabilidad_svc.delete(
                    db, vid, scope=scope, actor_id=current_user.id
                )
                if ok:
                    processed += 1
                else:
                    errors.append(f"{vid}: no encontrado")
            elif body.action == "estado":
                await vulnerabilidad_svc.update(
                    db,
                    vid,
                    VulnerabilidadUpdate(estado=body.estado),
                    scope=scope,
                )
                processed += 1
            else:
                await vulnerabilidad_svc.update(
                    db,
                    vid,
                    VulnerabilidadUpdate(responsable_id=body.responsable_id),
                    scope=scope,
                )
                processed += 1
        except ValidationException as e:
            errors.append(f"{vid}: {e.detail}")
        except Exception as e:
            logger.warning(
                "vulnerabilidad.bulk_action.item_failed",
                extra={"event": "vulnerabilidad.bulk_action.item_failed", "id": str(vid), "error": str(e)},
            )
            errors.append(f"{vid}: error")

    logger.info(
        "vulnerabilidad.bulk_action",
        extra={
            "event": "vulnerabilidad.bulk_action",
            "user_id": str(current_user.id),
            "action": body.action,
            "processed": processed,
            "failed": len(errors),
        },
    )
    out = VulnerabilidadBulkActionResult(processed=processed, failed=len(errors), errors=errors[:50])
    return success(out.model_dump())


@router.get("/{id}/historial")
async def list_vulnerabilidad_historial(
    id: str,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Bitácora de cambios de estado/responsable para una vulnerabilidad propia (spec 30)."""
    try:
        entity_id = UUID(id)
    except (ValueError, TypeError) as e:
        raise NotFoundException(f"Invalid ID format: {id}") from e

    vuln = await vulnerabilidad_svc.get(db, entity_id, scope={"user_id": current_user.id})
    if not vuln:
        raise NotFoundException(f"Vulnerabilidad {id} not found")

    result = await db.execute(
        select(HistorialVulnerabilidad)
        .where(HistorialVulnerabilidad.vulnerabilidad_id == entity_id)
        .order_by(HistorialVulnerabilidad.created_at.desc())
    )
    rows = result.scalars().all()
    return success([HistorialVulnerabilidadRead.model_validate(x).model_dump(mode="json") for x in rows])


@router.get("/{id}")
async def get_vulnerabilidad(
    id: str,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Get a single owned vulnerabilidad by ID (404 if not owned)."""
    # Validate UUID format
    try:
        entity_id = UUID(id)
    except (ValueError, TypeError) as e:
        raise NotFoundException(f"Invalid ID format: {id}") from e

    # Fetch entity
    entity = await vulnerabilidad_svc.get(db, entity_id, scope={"user_id": current_user.id})
    if not entity or entity.user_id != current_user.id:
        raise NotFoundException(f"Vulnerabilidad {id} not found")

    return success(VulnerabilidadRead.model_validate(entity).model_dump(mode="json"))


@router.post("", status_code=201)
async def create_vulnerabilidad(
    entity_in: VulnerabilidadCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Create a new vulnerabilidad for the current user."""
    entity = await vulnerabilidad_svc.create(db, entity_in, extra={"user_id": current_user.id})
    return success(VulnerabilidadRead.model_validate(entity).model_dump(mode="json"))


@router.post("/{id}/ia/triage-fp")
async def triage_vulnerabilidad_false_positive(
    id: UUID,
    payload: VulnerabilidadIATriageRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(require_permission(P.IA.EXECUTE)),
):
    """IA-assisted triage for potential false positives."""
    vuln = await vulnerabilidad_svc.get(db, id, scope={"user_id": current_user.id})
    if vuln is None:
        raise NotFoundException("Vulnerabilidad not found")

    motor_hints = get_motor_triage_hints(vuln.fuente)
    prompt = (
        "Eres un analista AppSec. Evalúa si el hallazgo podría ser falso positivo.\n"
        f"Titulo: {vuln.titulo}\n"
        f"Descripcion: {vuln.descripcion or 'N/A'}\n"
        f"Fuente (motor): {vuln.fuente}\n"
        f"Guía específica para este motor: {motor_hints}\n"
        f"Severidad: {vuln.severidad}\n"
        f"Estado: {vuln.estado}\n"
        f"CVSS: {vuln.cvss_score if vuln.cvss_score is not None else 'N/A'}\n"
        f"CWE: {vuln.cwe_id or 'N/A'}\n"
        f"OWASP: {vuln.owasp_categoria or 'N/A'}\n"
        f"Contexto adicional: {payload.contexto_adicional or 'N/A'}\n\n"
        "Responde SOLO JSON con campos: "
        '{"verdict":"false_positive|likely_real|needs_review","confidence":0.0,"rationale":"...","suggested_state":"..."}'
    )
    result = await run_prompt(db, prompt=prompt, dry_run=payload.dry_run)
    verdict, confidence, rationale, suggested_state = _parse_triage_output(result.content)

    await audit_record(
        db,
        action="vulnerabilidad.ia_triage_fp",
        entity_type="vulnerabilidad",
        entity_id=vuln.id,
        metadata={
            "provider": result.provider,
            "model": result.model,
            "dry_run": payload.dry_run,
            "fuente": vuln.fuente,
            "verdict": verdict,
            "confidence": confidence,
        },
    )
    response = VulnerabilidadIATriageRead(
        provider=result.provider,
        model=result.model,
        dry_run=payload.dry_run,
        verdict=verdict,
        confidence=confidence,
        rationale=rationale,
        suggested_state=suggested_state,
        raw_content=result.content,
    )
    return success(response.model_dump())


@router.patch("/{id}")
async def update_vulnerabilidad(
    entity_in: VulnerabilidadUpdate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: Vulnerabilidad = Depends(require_ownership(vulnerabilidad_svc)),
):
    """Partially update an owned vulnerabilidad (404 if not owned)."""
    updated = await vulnerabilidad_svc.update(db, entity.id, entity_in, scope={"user_id": current_user.id})
    return success(VulnerabilidadRead.model_validate(updated).model_dump(mode="json"))


@router.delete("/{id}")
async def delete_vulnerabilidad(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
    entity: Vulnerabilidad = Depends(require_ownership(vulnerabilidad_svc)),
):
    """Delete an owned vulnerabilidad (404 if not owned)."""
    await vulnerabilidad_svc.delete(db, entity.id, scope={"user_id": current_user.id})
    return success(None, meta={"message": "Vulnerabilidad deleted"})
