"""add_regla_sods

Revision ID: 1d85900047c8
Revises: 7b3e094c6ad9
Create Date: 2026-04-23 02:23:00.896028
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d85900047c8'
down_revision: Union[str, None] = '7b3e094c6ad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regla_sods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('alcance', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accion', name='uq_regla_sods_accion')
    )
    op.create_index(op.f('ix_regla_sods_deleted_at'), 'regla_sods', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_regla_sods_deleted_by'), 'regla_sods', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_regla_sods_user_id'), 'regla_sods', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_regla_sods_user_id'), table_name='regla_sods')
    op.drop_index(op.f('ix_regla_sods_deleted_by'), table_name='regla_sods')
    op.drop_index(op.f('ix_regla_sods_deleted_at'), table_name='regla_sods')
    op.drop_table('regla_sods')
    # ### end Alembic commands ###
