"""Phase 13 M5-7 CRUD complete

Revision ID: 269422a07547
Revises: 4091bd339fa9
Create Date: 2026-04-24 12:43:34.265530
"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '269422a07547'
down_revision: Union[str, None] = '4091bd339fa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
