"""Add_modulo8_operacion_releases

Revision ID: 32877222a822
Revises: 8b1531171b7b
Create Date: 2026-04-23 12:58:33.486584
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32877222a822"
down_revision: Union[str, None] = "8b1531171b7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "revision_terceros",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("nombre_empresa", sa.String(length=255), nullable=False),
        sa.Column("tipo", sa.String(length=100), nullable=False),
        sa.Column("servicio_id", sa.UUID(), nullable=True),
        sa.Column("activo_web_id", sa.UUID(), nullable=True),
        sa.Column("fecha_inicio", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fecha_fin", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column("informe_filename", sa.String(length=500), nullable=True),
        sa.Column("informe_sha256", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["activo_web_id"], ["activo_webs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["servicio_id"], ["servicios.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_revision_terceros_activo_web_id"), "revision_terceros", ["activo_web_id"], unique=False)
    op.create_index(op.f("ix_revision_terceros_deleted_at"), "revision_terceros", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_revision_terceros_deleted_by"), "revision_terceros", ["deleted_by"], unique=False)
    op.create_index(op.f("ix_revision_terceros_informe_sha256"), "revision_terceros", ["informe_sha256"], unique=False)
    op.create_index(op.f("ix_revision_terceros_servicio_id"), "revision_terceros", ["servicio_id"], unique=False)
    op.create_index(op.f("ix_revision_terceros_user_id"), "revision_terceros", ["user_id"], unique=False)
    op.create_table(
        "service_releases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("servicio_id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("estado_actual", sa.String(length=100), nullable=False),
        sa.Column("jira_referencia", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["servicio_id"], ["servicios.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_service_releases_deleted_at"), "service_releases", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_service_releases_deleted_by"), "service_releases", ["deleted_by"], unique=False)
    op.create_index(op.f("ix_service_releases_servicio_id"), "service_releases", ["servicio_id"], unique=False)
    op.create_index(op.f("ix_service_releases_user_id"), "service_releases", ["user_id"], unique=False)
    op.create_table(
        "etapa_releases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("service_release_id", sa.UUID(), nullable=False),
        sa.Column("etapa", sa.String(length=100), nullable=False),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column("aprobador_id", sa.UUID(), nullable=True),
        sa.Column("justificacion", sa.Text(), nullable=True),
        sa.Column("notas", sa.Text(), nullable=True),
        sa.Column("fecha_completada", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["aprobador_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["service_release_id"], ["service_releases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_etapa_releases_aprobador_id"), "etapa_releases", ["aprobador_id"], unique=False)
    op.create_index(op.f("ix_etapa_releases_deleted_at"), "etapa_releases", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_etapa_releases_deleted_by"), "etapa_releases", ["deleted_by"], unique=False)
    op.create_index(
        op.f("ix_etapa_releases_service_release_id"), "etapa_releases", ["service_release_id"], unique=False
    )
    op.create_index(op.f("ix_etapa_releases_user_id"), "etapa_releases", ["user_id"], unique=False)
    op.create_table(
        "hallazgo_terceros",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("revision_tercero_id", sa.UUID(), nullable=False),
        sa.Column("vulnerabilidad_id", sa.UUID(), nullable=True),
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("severidad", sa.String(length=50), nullable=False),
        sa.Column("cvss_score", sa.Float(), nullable=True),
        sa.Column("cwe_id", sa.String(length=50), nullable=True),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["revision_tercero_id"], ["revision_terceros.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vulnerabilidad_id"], ["vulnerabilidads.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hallazgo_terceros_deleted_at"), "hallazgo_terceros", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_hallazgo_terceros_deleted_by"), "hallazgo_terceros", ["deleted_by"], unique=False)
    op.create_index(
        op.f("ix_hallazgo_terceros_revision_tercero_id"), "hallazgo_terceros", ["revision_tercero_id"], unique=False
    )
    op.create_index(op.f("ix_hallazgo_terceros_user_id"), "hallazgo_terceros", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_hallazgo_terceros_vulnerabilidad_id"), "hallazgo_terceros", ["vulnerabilidad_id"], unique=False
    )
    op.create_table(
        "pipeline_releases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("service_release_id", sa.UUID(), nullable=True),
        sa.Column("repositorio_id", sa.UUID(), nullable=False),
        sa.Column("rama", sa.String(length=255), nullable=False),
        sa.Column("commit_sha", sa.String(length=255), nullable=True),
        sa.Column("tipo", sa.String(length=50), nullable=False),
        sa.Column("resultado", sa.String(length=50), nullable=False),
        sa.Column("herramienta", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["repositorio_id"], ["repositorios.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["service_release_id"], ["service_releases.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pipeline_releases_deleted_at"), "pipeline_releases", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_pipeline_releases_deleted_by"), "pipeline_releases", ["deleted_by"], unique=False)
    op.create_index(op.f("ix_pipeline_releases_repositorio_id"), "pipeline_releases", ["repositorio_id"], unique=False)
    op.create_index(
        op.f("ix_pipeline_releases_service_release_id"), "pipeline_releases", ["service_release_id"], unique=False
    )
    op.create_index(op.f("ix_pipeline_releases_user_id"), "pipeline_releases", ["user_id"], unique=False)
    op.create_table(
        "hallazgo_pipelines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("pipeline_release_id", sa.UUID(), nullable=False),
        sa.Column("vulnerabilidad_id", sa.UUID(), nullable=True),
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("severidad", sa.String(length=50), nullable=False),
        sa.Column("archivo", sa.String(length=500), nullable=True),
        sa.Column("linea", sa.Integer(), nullable=True),
        sa.Column("regla", sa.String(length=255), nullable=True),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["pipeline_release_id"], ["pipeline_releases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vulnerabilidad_id"], ["vulnerabilidads.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hallazgo_pipelines_deleted_at"), "hallazgo_pipelines", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_hallazgo_pipelines_deleted_by"), "hallazgo_pipelines", ["deleted_by"], unique=False)
    op.create_index(
        op.f("ix_hallazgo_pipelines_pipeline_release_id"), "hallazgo_pipelines", ["pipeline_release_id"], unique=False
    )
    op.create_index(op.f("ix_hallazgo_pipelines_user_id"), "hallazgo_pipelines", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_hallazgo_pipelines_vulnerabilidad_id"), "hallazgo_pipelines", ["vulnerabilidad_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_hallazgo_pipelines_vulnerabilidad_id"), table_name="hallazgo_pipelines")
    op.drop_index(op.f("ix_hallazgo_pipelines_user_id"), table_name="hallazgo_pipelines")
    op.drop_index(op.f("ix_hallazgo_pipelines_pipeline_release_id"), table_name="hallazgo_pipelines")
    op.drop_index(op.f("ix_hallazgo_pipelines_deleted_by"), table_name="hallazgo_pipelines")
    op.drop_index(op.f("ix_hallazgo_pipelines_deleted_at"), table_name="hallazgo_pipelines")
    op.drop_table("hallazgo_pipelines")
    op.drop_index(op.f("ix_pipeline_releases_user_id"), table_name="pipeline_releases")
    op.drop_index(op.f("ix_pipeline_releases_service_release_id"), table_name="pipeline_releases")
    op.drop_index(op.f("ix_pipeline_releases_repositorio_id"), table_name="pipeline_releases")
    op.drop_index(op.f("ix_pipeline_releases_deleted_by"), table_name="pipeline_releases")
    op.drop_index(op.f("ix_pipeline_releases_deleted_at"), table_name="pipeline_releases")
    op.drop_table("pipeline_releases")
    op.drop_index(op.f("ix_hallazgo_terceros_vulnerabilidad_id"), table_name="hallazgo_terceros")
    op.drop_index(op.f("ix_hallazgo_terceros_user_id"), table_name="hallazgo_terceros")
    op.drop_index(op.f("ix_hallazgo_terceros_revision_tercero_id"), table_name="hallazgo_terceros")
    op.drop_index(op.f("ix_hallazgo_terceros_deleted_by"), table_name="hallazgo_terceros")
    op.drop_index(op.f("ix_hallazgo_terceros_deleted_at"), table_name="hallazgo_terceros")
    op.drop_table("hallazgo_terceros")
    op.drop_index(op.f("ix_etapa_releases_user_id"), table_name="etapa_releases")
    op.drop_index(op.f("ix_etapa_releases_service_release_id"), table_name="etapa_releases")
    op.drop_index(op.f("ix_etapa_releases_deleted_by"), table_name="etapa_releases")
    op.drop_index(op.f("ix_etapa_releases_deleted_at"), table_name="etapa_releases")
    op.drop_index(op.f("ix_etapa_releases_aprobador_id"), table_name="etapa_releases")
    op.drop_table("etapa_releases")
    op.drop_index(op.f("ix_service_releases_user_id"), table_name="service_releases")
    op.drop_index(op.f("ix_service_releases_servicio_id"), table_name="service_releases")
    op.drop_index(op.f("ix_service_releases_deleted_by"), table_name="service_releases")
    op.drop_index(op.f("ix_service_releases_deleted_at"), table_name="service_releases")
    op.drop_table("service_releases")
    op.drop_index(op.f("ix_revision_terceros_user_id"), table_name="revision_terceros")
    op.drop_index(op.f("ix_revision_terceros_servicio_id"), table_name="revision_terceros")
    op.drop_index(op.f("ix_revision_terceros_informe_sha256"), table_name="revision_terceros")
    op.drop_index(op.f("ix_revision_terceros_deleted_by"), table_name="revision_terceros")
    op.drop_index(op.f("ix_revision_terceros_deleted_at"), table_name="revision_terceros")
    op.drop_index(op.f("ix_revision_terceros_activo_web_id"), table_name="revision_terceros")
    op.drop_table("revision_terceros")
    # ### end Alembic commands ###
