"""Add Module 3 - Programas Anuales (17 entities)

Revision ID: 3e098057fd97
Revises: 32877222a822
Create Date: 2026-04-24 04:55:29.189230
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3e098057fd97"
down_revision: Union[str, None] = "32877222a822"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "control_source_codes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("tipo", sa.String(length=100), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("obligatorio", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_control_source_codes_deleted_at"), "control_source_codes", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_control_source_codes_deleted_by"), "control_source_codes", ["deleted_by"], unique=False)
    op.create_index(op.f("ix_control_source_codes_tipo"), "control_source_codes", ["tipo"], unique=False)
    op.create_index(op.f("ix_control_source_codes_user_id"), "control_source_codes", ["user_id"], unique=False)
    op.create_table(
        "regulacion_controls",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("nombre_regulacion", sa.String(length=255), nullable=False),
        sa.Column("nombre_control", sa.String(length=255), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("obligatorio", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_regulacion_controls_deleted_at"), "regulacion_controls", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_regulacion_controls_deleted_by"), "regulacion_controls", ["deleted_by"], unique=False)
    op.create_index(
        op.f("ix_regulacion_controls_nombre_regulacion"), "regulacion_controls", ["nombre_regulacion"], unique=False
    )
    op.create_index(op.f("ix_regulacion_controls_user_id"), "regulacion_controls", ["user_id"], unique=False)
    op.create_table(
        "programa_dasts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("activo_web_id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["activo_web_id"], ["activo_webs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_programa_dasts_activo_web_id"), "programa_dasts", ["activo_web_id"], unique=False)
    op.create_index(op.f("ix_programa_dasts_ano"), "programa_dasts", ["ano"], unique=False)
    op.create_index(op.f("ix_programa_dasts_deleted_at"), "programa_dasts", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_programa_dasts_deleted_by"), "programa_dasts", ["deleted_by"], unique=False)
    op.create_index(op.f("ix_programa_dasts_user_id"), "programa_dasts", ["user_id"], unique=False)
    op.create_table(
        "programa_sasts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("repositorio_id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["repositorio_id"], ["repositorios.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_programa_sasts_ano"), "programa_sasts", ["ano"], unique=False)
    op.create_index(op.f("ix_programa_sasts_deleted_at"), "programa_sasts", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_programa_sasts_deleted_by"), "programa_sasts", ["deleted_by"], unique=False)
    op.create_index(op.f("ix_programa_sasts_repositorio_id"), "programa_sasts", ["repositorio_id"], unique=False)
    op.create_index(op.f("ix_programa_sasts_user_id"), "programa_sasts", ["user_id"], unique=False)
    op.create_table(
        "programa_source_codes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("repositorio_id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["repositorio_id"], ["repositorios.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_programa_source_codes_ano"), "programa_source_codes", ["ano"], unique=False)
    op.create_index(op.f("ix_programa_source_codes_deleted_at"), "programa_source_codes", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_programa_source_codes_deleted_by"), "programa_source_codes", ["deleted_by"], unique=False)
    op.create_index(
        op.f("ix_programa_source_codes_repositorio_id"), "programa_source_codes", ["repositorio_id"], unique=False
    )
    op.create_index(op.f("ix_programa_source_codes_user_id"), "programa_source_codes", ["user_id"], unique=False)
    op.create_table(
        "programa_threat_modelings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("activo_web_id", sa.UUID(), nullable=True),
        sa.Column("servicio_id", sa.UUID(), nullable=True),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["activo_web_id"], ["activo_webs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["servicio_id"], ["servicios.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_programa_threat_modelings_activo_web_id"), "programa_threat_modelings", ["activo_web_id"], unique=False
    )
    op.create_index(op.f("ix_programa_threat_modelings_ano"), "programa_threat_modelings", ["ano"], unique=False)
    op.create_index(
        op.f("ix_programa_threat_modelings_deleted_at"), "programa_threat_modelings", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_programa_threat_modelings_deleted_by"), "programa_threat_modelings", ["deleted_by"], unique=False
    )
    op.create_index(
        op.f("ix_programa_threat_modelings_servicio_id"), "programa_threat_modelings", ["servicio_id"], unique=False
    )
    op.create_index(
        op.f("ix_programa_threat_modelings_user_id"), "programa_threat_modelings", ["user_id"], unique=False
    )
    op.create_table(
        "servicio_regulado_registros",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("servicio_id", sa.UUID(), nullable=False),
        sa.Column("nombre_regulacion", sa.String(length=255), nullable=False),
        sa.Column("ciclo", sa.String(length=20), nullable=False),
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["servicio_id"], ["servicios.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_servicio_regulado_registros_ano"), "servicio_regulado_registros", ["ano"], unique=False)
    op.create_index(
        op.f("ix_servicio_regulado_registros_deleted_at"), "servicio_regulado_registros", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_servicio_regulado_registros_deleted_by"), "servicio_regulado_registros", ["deleted_by"], unique=False
    )
    op.create_index(
        op.f("ix_servicio_regulado_registros_servicio_id"), "servicio_regulado_registros", ["servicio_id"], unique=False
    )
    op.create_index(
        op.f("ix_servicio_regulado_registros_user_id"), "servicio_regulado_registros", ["user_id"], unique=False
    )
    op.create_table(
        "actividad_mensual_sasts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("programa_sast_id", sa.UUID(), nullable=False),
        sa.Column("mes", sa.Integer(), nullable=False),
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("total_hallazgos", sa.Integer(), nullable=True),
        sa.Column("criticos", sa.Integer(), nullable=True),
        sa.Column("altos", sa.Integer(), nullable=True),
        sa.Column("medios", sa.Integer(), nullable=True),
        sa.Column("bajos", sa.Integer(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("notas", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["programa_sast_id"], ["programa_sasts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_actividad_mensual_sasts_ano"), "actividad_mensual_sasts", ["ano"], unique=False)
    op.create_index(
        op.f("ix_actividad_mensual_sasts_deleted_at"), "actividad_mensual_sasts", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_actividad_mensual_sasts_deleted_by"), "actividad_mensual_sasts", ["deleted_by"], unique=False
    )
    op.create_index(
        op.f("ix_actividad_mensual_sasts_programa_sast_id"),
        "actividad_mensual_sasts",
        ["programa_sast_id"],
        unique=False,
    )
    op.create_index(op.f("ix_actividad_mensual_sasts_user_id"), "actividad_mensual_sasts", ["user_id"], unique=False)
    op.create_table(
        "ejecucion_dasts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("programa_dast_id", sa.UUID(), nullable=False),
        sa.Column("fecha_inicio", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fecha_fin", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ambiente", sa.String(length=50), nullable=False),
        sa.Column("herramienta", sa.String(length=255), nullable=True),
        sa.Column("resultado", sa.String(length=50), nullable=False),
        sa.Column("notas", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["programa_dast_id"], ["programa_dasts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ejecucion_dasts_deleted_at"), "ejecucion_dasts", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_ejecucion_dasts_deleted_by"), "ejecucion_dasts", ["deleted_by"], unique=False)
    op.create_index(op.f("ix_ejecucion_dasts_programa_dast_id"), "ejecucion_dasts", ["programa_dast_id"], unique=False)
    op.create_index(op.f("ix_ejecucion_dasts_user_id"), "ejecucion_dasts", ["user_id"], unique=False)
    op.create_table(
        "estado_cumplimientos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("registro_id", sa.UUID(), nullable=False),
        sa.Column("control_id", sa.UUID(), nullable=True),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column("porcentaje", sa.Float(), nullable=True),
        sa.Column("notas", sa.Text(), nullable=True),
        sa.Column("fecha_evaluacion", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["control_id"], ["regulacion_controls.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["registro_id"], ["servicio_regulado_registros.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_estado_cumplimientos_control_id"), "estado_cumplimientos", ["control_id"], unique=False)
    op.create_index(op.f("ix_estado_cumplimientos_deleted_at"), "estado_cumplimientos", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_estado_cumplimientos_deleted_by"), "estado_cumplimientos", ["deleted_by"], unique=False)
    op.create_index(op.f("ix_estado_cumplimientos_estado"), "estado_cumplimientos", ["estado"], unique=False)
    op.create_index(op.f("ix_estado_cumplimientos_registro_id"), "estado_cumplimientos", ["registro_id"], unique=False)
    op.create_index(op.f("ix_estado_cumplimientos_user_id"), "estado_cumplimientos", ["user_id"], unique=False)
    op.create_table(
        "evidencia_regulacions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("registro_id", sa.UUID(), nullable=False),
        sa.Column("control_id", sa.UUID(), nullable=True),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("fecha", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["control_id"], ["regulacion_controls.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["registro_id"], ["servicio_regulado_registros.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evidencia_regulacions_control_id"), "evidencia_regulacions", ["control_id"], unique=False)
    op.create_index(op.f("ix_evidencia_regulacions_deleted_at"), "evidencia_regulacions", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_evidencia_regulacions_deleted_by"), "evidencia_regulacions", ["deleted_by"], unique=False)
    op.create_index(
        op.f("ix_evidencia_regulacions_registro_id"), "evidencia_regulacions", ["registro_id"], unique=False
    )
    op.create_index(op.f("ix_evidencia_regulacions_sha256"), "evidencia_regulacions", ["sha256"], unique=False)
    op.create_index(op.f("ix_evidencia_regulacions_user_id"), "evidencia_regulacions", ["user_id"], unique=False)
    op.create_table(
        "revision_source_codes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("programa_sc_id", sa.UUID(), nullable=False),
        sa.Column("control_sc_id", sa.UUID(), nullable=False),
        sa.Column("fecha_revision", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resultado", sa.String(length=50), nullable=False),
        sa.Column("evidencia_filename", sa.String(length=500), nullable=True),
        sa.Column("evidencia_sha256", sa.String(length=64), nullable=True),
        sa.Column("notas", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["control_sc_id"], ["control_source_codes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["programa_sc_id"], ["programa_source_codes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_revision_source_codes_control_sc_id"), "revision_source_codes", ["control_sc_id"], unique=False
    )
    op.create_index(op.f("ix_revision_source_codes_deleted_at"), "revision_source_codes", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_revision_source_codes_deleted_by"), "revision_source_codes", ["deleted_by"], unique=False)
    op.create_index(
        op.f("ix_revision_source_codes_evidencia_sha256"), "revision_source_codes", ["evidencia_sha256"], unique=False
    )
    op.create_index(
        op.f("ix_revision_source_codes_programa_sc_id"), "revision_source_codes", ["programa_sc_id"], unique=False
    )
    op.create_index(op.f("ix_revision_source_codes_user_id"), "revision_source_codes", ["user_id"], unique=False)
    op.create_table(
        "sesion_threat_modelings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("programa_tm_id", sa.UUID(), nullable=False),
        sa.Column("fecha", sa.DateTime(timezone=True), nullable=False),
        sa.Column("participantes", sa.Text(), nullable=True),
        sa.Column("contexto", sa.Text(), nullable=True),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column("ia_utilizada", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["programa_tm_id"], ["programa_threat_modelings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sesion_threat_modelings_deleted_at"), "sesion_threat_modelings", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_sesion_threat_modelings_deleted_by"), "sesion_threat_modelings", ["deleted_by"], unique=False
    )
    op.create_index(
        op.f("ix_sesion_threat_modelings_programa_tm_id"), "sesion_threat_modelings", ["programa_tm_id"], unique=False
    )
    op.create_index(op.f("ix_sesion_threat_modelings_user_id"), "sesion_threat_modelings", ["user_id"], unique=False)
    op.create_table(
        "amenazas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("sesion_id", sa.UUID(), nullable=False),
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("categoria_stride", sa.String(length=50), nullable=False),
        sa.Column("dread_damage", sa.Integer(), nullable=False),
        sa.Column("dread_reproducibility", sa.Integer(), nullable=False),
        sa.Column("dread_exploitability", sa.Integer(), nullable=False),
        sa.Column("dread_affected_users", sa.Integer(), nullable=False),
        sa.Column("dread_discoverability", sa.Integer(), nullable=False),
        sa.Column("score_total", sa.Float(), nullable=True),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["sesion_id"], ["sesion_threat_modelings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_amenazas_categoria_stride"), "amenazas", ["categoria_stride"], unique=False)
    op.create_index(op.f("ix_amenazas_deleted_at"), "amenazas", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_amenazas_deleted_by"), "amenazas", ["deleted_by"], unique=False)
    op.create_index(op.f("ix_amenazas_sesion_id"), "amenazas", ["sesion_id"], unique=False)
    op.create_index(op.f("ix_amenazas_user_id"), "amenazas", ["user_id"], unique=False)
    op.create_table(
        "hallazgo_dasts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("ejecucion_dast_id", sa.UUID(), nullable=False),
        sa.Column("vulnerabilidad_id", sa.UUID(), nullable=True),
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("severidad", sa.String(length=50), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("parametro", sa.String(length=255), nullable=True),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["ejecucion_dast_id"], ["ejecucion_dasts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vulnerabilidad_id"], ["vulnerabilidads.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hallazgo_dasts_deleted_at"), "hallazgo_dasts", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_hallazgo_dasts_deleted_by"), "hallazgo_dasts", ["deleted_by"], unique=False)
    op.create_index(op.f("ix_hallazgo_dasts_ejecucion_dast_id"), "hallazgo_dasts", ["ejecucion_dast_id"], unique=False)
    op.create_index(op.f("ix_hallazgo_dasts_severidad"), "hallazgo_dasts", ["severidad"], unique=False)
    op.create_index(op.f("ix_hallazgo_dasts_user_id"), "hallazgo_dasts", ["user_id"], unique=False)
    op.create_index(op.f("ix_hallazgo_dasts_vulnerabilidad_id"), "hallazgo_dasts", ["vulnerabilidad_id"], unique=False)
    op.create_table(
        "hallazgo_sasts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("actividad_sast_id", sa.UUID(), nullable=False),
        sa.Column("vulnerabilidad_id", sa.UUID(), nullable=True),
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("severidad", sa.String(length=50), nullable=False),
        sa.Column("herramienta", sa.String(length=255), nullable=True),
        sa.Column("regla", sa.String(length=255), nullable=True),
        sa.Column("archivo", sa.String(length=500), nullable=True),
        sa.Column("linea", sa.Integer(), nullable=True),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["actividad_sast_id"], ["actividad_mensual_sasts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vulnerabilidad_id"], ["vulnerabilidads.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hallazgo_sasts_actividad_sast_id"), "hallazgo_sasts", ["actividad_sast_id"], unique=False)
    op.create_index(op.f("ix_hallazgo_sasts_deleted_at"), "hallazgo_sasts", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_hallazgo_sasts_deleted_by"), "hallazgo_sasts", ["deleted_by"], unique=False)
    op.create_index(op.f("ix_hallazgo_sasts_severidad"), "hallazgo_sasts", ["severidad"], unique=False)
    op.create_index(op.f("ix_hallazgo_sasts_user_id"), "hallazgo_sasts", ["user_id"], unique=False)
    op.create_index(op.f("ix_hallazgo_sasts_vulnerabilidad_id"), "hallazgo_sasts", ["vulnerabilidad_id"], unique=False)
    op.create_table(
        "control_mitigacions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("amenaza_id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("tipo", sa.String(length=50), nullable=False),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column("responsable_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["amenaza_id"], ["amenazas.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["responsable_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_control_mitigacions_amenaza_id"), "control_mitigacions", ["amenaza_id"], unique=False)
    op.create_index(op.f("ix_control_mitigacions_deleted_at"), "control_mitigacions", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_control_mitigacions_deleted_by"), "control_mitigacions", ["deleted_by"], unique=False)
    op.create_index(
        op.f("ix_control_mitigacions_responsable_id"), "control_mitigacions", ["responsable_id"], unique=False
    )
    op.create_index(op.f("ix_control_mitigacions_user_id"), "control_mitigacions", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_control_mitigacions_user_id"), table_name="control_mitigacions")
    op.drop_index(op.f("ix_control_mitigacions_responsable_id"), table_name="control_mitigacions")
    op.drop_index(op.f("ix_control_mitigacions_deleted_by"), table_name="control_mitigacions")
    op.drop_index(op.f("ix_control_mitigacions_deleted_at"), table_name="control_mitigacions")
    op.drop_index(op.f("ix_control_mitigacions_amenaza_id"), table_name="control_mitigacions")
    op.drop_table("control_mitigacions")
    op.drop_index(op.f("ix_hallazgo_sasts_vulnerabilidad_id"), table_name="hallazgo_sasts")
    op.drop_index(op.f("ix_hallazgo_sasts_user_id"), table_name="hallazgo_sasts")
    op.drop_index(op.f("ix_hallazgo_sasts_severidad"), table_name="hallazgo_sasts")
    op.drop_index(op.f("ix_hallazgo_sasts_deleted_by"), table_name="hallazgo_sasts")
    op.drop_index(op.f("ix_hallazgo_sasts_deleted_at"), table_name="hallazgo_sasts")
    op.drop_index(op.f("ix_hallazgo_sasts_actividad_sast_id"), table_name="hallazgo_sasts")
    op.drop_table("hallazgo_sasts")
    op.drop_index(op.f("ix_hallazgo_dasts_vulnerabilidad_id"), table_name="hallazgo_dasts")
    op.drop_index(op.f("ix_hallazgo_dasts_user_id"), table_name="hallazgo_dasts")
    op.drop_index(op.f("ix_hallazgo_dasts_severidad"), table_name="hallazgo_dasts")
    op.drop_index(op.f("ix_hallazgo_dasts_ejecucion_dast_id"), table_name="hallazgo_dasts")
    op.drop_index(op.f("ix_hallazgo_dasts_deleted_by"), table_name="hallazgo_dasts")
    op.drop_index(op.f("ix_hallazgo_dasts_deleted_at"), table_name="hallazgo_dasts")
    op.drop_table("hallazgo_dasts")
    op.drop_index(op.f("ix_amenazas_user_id"), table_name="amenazas")
    op.drop_index(op.f("ix_amenazas_sesion_id"), table_name="amenazas")
    op.drop_index(op.f("ix_amenazas_deleted_by"), table_name="amenazas")
    op.drop_index(op.f("ix_amenazas_deleted_at"), table_name="amenazas")
    op.drop_index(op.f("ix_amenazas_categoria_stride"), table_name="amenazas")
    op.drop_table("amenazas")
    op.drop_index(op.f("ix_sesion_threat_modelings_user_id"), table_name="sesion_threat_modelings")
    op.drop_index(op.f("ix_sesion_threat_modelings_programa_tm_id"), table_name="sesion_threat_modelings")
    op.drop_index(op.f("ix_sesion_threat_modelings_deleted_by"), table_name="sesion_threat_modelings")
    op.drop_index(op.f("ix_sesion_threat_modelings_deleted_at"), table_name="sesion_threat_modelings")
    op.drop_table("sesion_threat_modelings")
    op.drop_index(op.f("ix_revision_source_codes_user_id"), table_name="revision_source_codes")
    op.drop_index(op.f("ix_revision_source_codes_programa_sc_id"), table_name="revision_source_codes")
    op.drop_index(op.f("ix_revision_source_codes_evidencia_sha256"), table_name="revision_source_codes")
    op.drop_index(op.f("ix_revision_source_codes_deleted_by"), table_name="revision_source_codes")
    op.drop_index(op.f("ix_revision_source_codes_deleted_at"), table_name="revision_source_codes")
    op.drop_index(op.f("ix_revision_source_codes_control_sc_id"), table_name="revision_source_codes")
    op.drop_table("revision_source_codes")
    op.drop_index(op.f("ix_evidencia_regulacions_user_id"), table_name="evidencia_regulacions")
    op.drop_index(op.f("ix_evidencia_regulacions_sha256"), table_name="evidencia_regulacions")
    op.drop_index(op.f("ix_evidencia_regulacions_registro_id"), table_name="evidencia_regulacions")
    op.drop_index(op.f("ix_evidencia_regulacions_deleted_by"), table_name="evidencia_regulacions")
    op.drop_index(op.f("ix_evidencia_regulacions_deleted_at"), table_name="evidencia_regulacions")
    op.drop_index(op.f("ix_evidencia_regulacions_control_id"), table_name="evidencia_regulacions")
    op.drop_table("evidencia_regulacions")
    op.drop_index(op.f("ix_estado_cumplimientos_user_id"), table_name="estado_cumplimientos")
    op.drop_index(op.f("ix_estado_cumplimientos_registro_id"), table_name="estado_cumplimientos")
    op.drop_index(op.f("ix_estado_cumplimientos_estado"), table_name="estado_cumplimientos")
    op.drop_index(op.f("ix_estado_cumplimientos_deleted_by"), table_name="estado_cumplimientos")
    op.drop_index(op.f("ix_estado_cumplimientos_deleted_at"), table_name="estado_cumplimientos")
    op.drop_index(op.f("ix_estado_cumplimientos_control_id"), table_name="estado_cumplimientos")
    op.drop_table("estado_cumplimientos")
    op.drop_index(op.f("ix_ejecucion_dasts_user_id"), table_name="ejecucion_dasts")
    op.drop_index(op.f("ix_ejecucion_dasts_programa_dast_id"), table_name="ejecucion_dasts")
    op.drop_index(op.f("ix_ejecucion_dasts_deleted_by"), table_name="ejecucion_dasts")
    op.drop_index(op.f("ix_ejecucion_dasts_deleted_at"), table_name="ejecucion_dasts")
    op.drop_table("ejecucion_dasts")
    op.drop_index(op.f("ix_actividad_mensual_sasts_user_id"), table_name="actividad_mensual_sasts")
    op.drop_index(op.f("ix_actividad_mensual_sasts_programa_sast_id"), table_name="actividad_mensual_sasts")
    op.drop_index(op.f("ix_actividad_mensual_sasts_deleted_by"), table_name="actividad_mensual_sasts")
    op.drop_index(op.f("ix_actividad_mensual_sasts_deleted_at"), table_name="actividad_mensual_sasts")
    op.drop_index(op.f("ix_actividad_mensual_sasts_ano"), table_name="actividad_mensual_sasts")
    op.drop_table("actividad_mensual_sasts")
    op.drop_index(op.f("ix_servicio_regulado_registros_user_id"), table_name="servicio_regulado_registros")
    op.drop_index(op.f("ix_servicio_regulado_registros_servicio_id"), table_name="servicio_regulado_registros")
    op.drop_index(op.f("ix_servicio_regulado_registros_deleted_by"), table_name="servicio_regulado_registros")
    op.drop_index(op.f("ix_servicio_regulado_registros_deleted_at"), table_name="servicio_regulado_registros")
    op.drop_index(op.f("ix_servicio_regulado_registros_ano"), table_name="servicio_regulado_registros")
    op.drop_table("servicio_regulado_registros")
    op.drop_index(op.f("ix_programa_threat_modelings_user_id"), table_name="programa_threat_modelings")
    op.drop_index(op.f("ix_programa_threat_modelings_servicio_id"), table_name="programa_threat_modelings")
    op.drop_index(op.f("ix_programa_threat_modelings_deleted_by"), table_name="programa_threat_modelings")
    op.drop_index(op.f("ix_programa_threat_modelings_deleted_at"), table_name="programa_threat_modelings")
    op.drop_index(op.f("ix_programa_threat_modelings_ano"), table_name="programa_threat_modelings")
    op.drop_index(op.f("ix_programa_threat_modelings_activo_web_id"), table_name="programa_threat_modelings")
    op.drop_table("programa_threat_modelings")
    op.drop_index(op.f("ix_programa_source_codes_user_id"), table_name="programa_source_codes")
    op.drop_index(op.f("ix_programa_source_codes_repositorio_id"), table_name="programa_source_codes")
    op.drop_index(op.f("ix_programa_source_codes_deleted_by"), table_name="programa_source_codes")
    op.drop_index(op.f("ix_programa_source_codes_deleted_at"), table_name="programa_source_codes")
    op.drop_index(op.f("ix_programa_source_codes_ano"), table_name="programa_source_codes")
    op.drop_table("programa_source_codes")
    op.drop_index(op.f("ix_programa_sasts_user_id"), table_name="programa_sasts")
    op.drop_index(op.f("ix_programa_sasts_repositorio_id"), table_name="programa_sasts")
    op.drop_index(op.f("ix_programa_sasts_deleted_by"), table_name="programa_sasts")
    op.drop_index(op.f("ix_programa_sasts_deleted_at"), table_name="programa_sasts")
    op.drop_index(op.f("ix_programa_sasts_ano"), table_name="programa_sasts")
    op.drop_table("programa_sasts")
    op.drop_index(op.f("ix_programa_dasts_user_id"), table_name="programa_dasts")
    op.drop_index(op.f("ix_programa_dasts_deleted_by"), table_name="programa_dasts")
    op.drop_index(op.f("ix_programa_dasts_deleted_at"), table_name="programa_dasts")
    op.drop_index(op.f("ix_programa_dasts_ano"), table_name="programa_dasts")
    op.drop_index(op.f("ix_programa_dasts_activo_web_id"), table_name="programa_dasts")
    op.drop_table("programa_dasts")
    op.drop_index(op.f("ix_regulacion_controls_user_id"), table_name="regulacion_controls")
    op.drop_index(op.f("ix_regulacion_controls_nombre_regulacion"), table_name="regulacion_controls")
    op.drop_index(op.f("ix_regulacion_controls_deleted_by"), table_name="regulacion_controls")
    op.drop_index(op.f("ix_regulacion_controls_deleted_at"), table_name="regulacion_controls")
    op.drop_table("regulacion_controls")
    op.drop_index(op.f("ix_control_source_codes_user_id"), table_name="control_source_codes")
    op.drop_index(op.f("ix_control_source_codes_tipo"), table_name="control_source_codes")
    op.drop_index(op.f("ix_control_source_codes_deleted_by"), table_name="control_source_codes")
    op.drop_index(op.f("ix_control_source_codes_deleted_at"), table_name="control_source_codes")
    op.drop_table("control_source_codes")
    # ### end Alembic commands ###
