"""add agent configuration models and endpoints

Revision ID: 3f3ce64e75f1
Revises: p0q1r2s3t4u5
Create Date: 2026-04-29 14:39:51.553559
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f3ce64e75f1'
down_revision: Union[str, None] = 'p0q1r2s3t4u5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_logs_destinatario', table_name='email_logs')
    op.drop_index('ix_email_logs_estado', table_name='email_logs')
    op.drop_index('ix_email_logs_notificacion_id', table_name='email_logs')
    op.drop_index('ix_email_logs_user_id', table_name='email_logs')
    op.drop_table('email_logs')
    op.drop_index('ix_dashboard_configs_dashboard_id', table_name='dashboard_configs')
    op.drop_index('ix_dashboard_configs_deleted_at', table_name='dashboard_configs')
    op.drop_index('ix_dashboard_configs_deleted_by', table_name='dashboard_configs')
    op.drop_index('ix_dashboard_configs_role_id', table_name='dashboard_configs')
    op.drop_index('ix_dashboard_configs_widget_id', table_name='dashboard_configs')
    op.drop_table('dashboard_configs')
    op.drop_index('ix_formulas_deleted_at', table_name='formulas')
    op.drop_index('ix_formulas_nombre', table_name='formulas')
    op.drop_table('formulas')
    op.drop_index('ix_email_templates_nombre', table_name='email_templates')
    op.drop_table('email_templates')
    op.create_index(op.f('ix_actividad_mensual_dasts_deleted_at'), 'actividad_mensual_dasts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_actividad_mensual_servicios_regulados_deleted_at'), 'actividad_mensual_servicios_regulados', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_actividad_mensual_source_codes_deleted_at'), 'actividad_mensual_source_codes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ai_automation_rules_deleted_by'), 'ai_automation_rules', ['deleted_by'], unique=False)
    op.alter_column('ai_rules', 'trigger_type',
               existing_type=sa.VARCHAR(length=128),
               comment='on_vulnerability_created, on_vulnerability_status_changed, on_release_created, on_theme_created, on_sla_at_risk, cron',
               existing_nullable=False,
               existing_server_default=sa.text("'on_vulnerability_created'::character varying"))
    op.alter_column('ai_rules', 'trigger_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Trigger-specific config (e.g., cron schedule, severity filter)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('ai_rules', 'action_type',
               existing_type=sa.VARCHAR(length=128),
               comment='send_notification, create_ticket, assign_to_user, tag_entity, generate_summary, enrich_data, suggest_fix',
               existing_nullable=False,
               existing_server_default=sa.text("'send_notification'::character varying"))
    op.alter_column('ai_rules', 'action_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Action-specific config (e.g., template, user_id, tags)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('ix_ai_rule_action_enabled', table_name='ai_rules', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('ix_ai_rule_trigger_enabled', table_name='ai_rules', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_ai_rules_deleted_by'), 'ai_rules', ['deleted_by'], unique=False)
    op.drop_index('ix_audit_logs_actor_ts', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_ts', table_name='audit_logs')
    op.drop_index('ix_auditorias_titulo_gin', table_name='auditorias', postgresql_using='gin')
    op.drop_constraint('uq_catalogs_type', 'catalogs', type_='unique')
    op.drop_index('ix_catalogs_type', table_name='catalogs')
    op.create_index(op.f('ix_catalogs_type'), 'catalogs', ['type'], unique=True)
    op.create_index(op.f('ix_code_security_findings_fingerprint'), 'code_security_findings', ['fingerprint'], unique=False)
    op.drop_constraint('code_security_reports_review_id_key', 'code_security_reports', type_='unique')
    op.drop_index('ix_code_security_reports_review_id', table_name='code_security_reports')
    op.create_index(op.f('ix_code_security_reports_review_id'), 'code_security_reports', ['review_id'], unique=True)
    op.create_index('ix_configuracion_ia_provider_enabled', 'configuracion_ia', ['provider', 'enabled'], unique=False)
    op.drop_index('ix_control_seguridads_nombre_gin', table_name='control_seguridads', postgresql_using='gin')
    op.create_index(op.f('ix_custom_dashboards_deleted_at'), 'custom_dashboards', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_custom_dashboards_deleted_by'), 'custom_dashboards', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_custom_field_values_deleted_at'), 'custom_field_values', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_custom_fields_deleted_by'), 'custom_fields', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_custom_fields_order'), 'custom_fields', ['order'], unique=False)
    op.drop_index('ix_hallazgo_dasts_descripcion_gin', table_name='hallazgo_dasts', postgresql_using='gin')
    op.drop_index('ix_hallazgo_dasts_titulo_gin', table_name='hallazgo_dasts', postgresql_using='gin')
    op.drop_index('ix_hallazgo_masts_descripcion_gin', table_name='hallazgo_masts', postgresql_using='gin')
    op.drop_index('ix_hallazgo_masts_nombre_gin', table_name='hallazgo_masts', postgresql_using='gin')
    op.drop_index('ix_hallazgo_pipelines_scan_id', table_name='hallazgo_pipelines')
    op.drop_index('ix_hallazgo_sasts_descripcion_gin', table_name='hallazgo_sasts', postgresql_using='gin')
    op.drop_index('ix_hallazgo_sasts_titulo_gin', table_name='hallazgo_sasts', postgresql_using='gin')
    op.drop_index('ix_iniciativas_descripcion_gin', table_name='iniciativas', postgresql_using='gin')
    op.drop_index('ix_iniciativas_titulo_gin', table_name='iniciativas', postgresql_using='gin')
    op.create_index(op.f('ix_kanban_columns_deleted_at'), 'kanban_columns', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_module_views_deleted_by'), 'module_views', ['deleted_by'], unique=False)
    op.drop_constraint('module_views_user_id_fkey', 'module_views', type_='foreignkey')
    op.create_foreign_key(None, 'module_views', 'users', ['user_id'], ['id'])
    op.alter_column('navigation_items', 'label',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('navigation_items', 'icon',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('navigation_items', 'href',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('navigation_items', 'required_role',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index('ix_navigation_items_orden', table_name='navigation_items')
    op.drop_index('ix_navigation_items_parent_id', table_name='navigation_items')
    op.drop_index('ix_navigation_items_visible', table_name='navigation_items')
    op.create_index(op.f('ix_navigation_items_deleted_by'), 'navigation_items', ['deleted_by'], unique=False)
    op.drop_constraint('permissions_code_key', 'permissions', type_='unique')
    op.create_index(op.f('ix_pipeline_releases_rama'), 'pipeline_releases', ['rama'], unique=False)
    op.drop_index('ix_planes_remediacion_acciones_gin', table_name='planes_remediacion', postgresql_using='gin')
    op.drop_index('ix_planes_remediacion_descripcion_gin', table_name='planes_remediacion', postgresql_using='gin')
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.create_index(op.f('ix_saved_widgets_deleted_at'), 'saved_widgets', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_saved_widgets_deleted_by'), 'saved_widgets', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_service_releases_fecha_entrada'), 'service_releases', ['fecha_entrada'], unique=False)
    op.drop_constraint('UQ_system_catalog_tipo_key', 'system_catalogs', type_='unique')
    op.create_unique_constraint('uq_system_catalog_tipo_key', 'system_catalogs', ['tipo', 'key'])
    op.drop_index('ix_temas_emergentes_descripcion_gin', table_name='temas_emergentes', postgresql_using='gin')
    op.drop_index('ix_temas_emergentes_titulo_gin', table_name='temas_emergentes', postgresql_using='gin')
    op.alter_column('validation_rules', 'entity_type',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('validation_rules', 'nombre',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('validation_rules', 'rule_type',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('validation_rules', 'condition',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('validation_rules', 'error_message',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('validation_rules', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_validation_rules_created_by', table_name='validation_rules')
    op.drop_index('ix_validation_rules_enabled', table_name='validation_rules')
    op.drop_index('ix_validation_rules_rule_type', table_name='validation_rules')
    op.drop_constraint('validation_rules_created_by_fkey', 'validation_rules', type_='foreignkey')
    op.create_foreign_key(None, 'validation_rules', 'users', ['created_by'], ['id'])
    op.drop_index('ix_vulnerabilidads_descripcion_gin', table_name='vulnerabilidads', postgresql_using='gin')
    op.drop_index('ix_vulnerabilidads_titulo_gin', table_name='vulnerabilidads', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_vulnerabilidads_titulo_gin', 'vulnerabilidads', ['titulo'], unique=False, postgresql_using='gin')
    op.create_index('ix_vulnerabilidads_descripcion_gin', 'vulnerabilidads', ['descripcion'], unique=False, postgresql_using='gin')
    op.drop_constraint(None, 'validation_rules', type_='foreignkey')
    op.create_foreign_key('validation_rules_created_by_fkey', 'validation_rules', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_index('ix_validation_rules_rule_type', 'validation_rules', ['rule_type'], unique=False)
    op.create_index('ix_validation_rules_enabled', 'validation_rules', ['enabled'], unique=False)
    op.create_index('ix_validation_rules_created_by', 'validation_rules', ['created_by'], unique=False)
    op.alter_column('validation_rules', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('validation_rules', 'error_message',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    op.alter_column('validation_rules', 'condition',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('validation_rules', 'rule_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('validation_rules', 'nombre',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('validation_rules', 'entity_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.create_index('ix_temas_emergentes_titulo_gin', 'temas_emergentes', ['titulo'], unique=False, postgresql_using='gin')
    op.create_index('ix_temas_emergentes_descripcion_gin', 'temas_emergentes', ['descripcion'], unique=False, postgresql_using='gin')
    op.drop_constraint('uq_system_catalog_tipo_key', 'system_catalogs', type_='unique')
    op.create_unique_constraint('UQ_system_catalog_tipo_key', 'system_catalogs', ['tipo', 'key'])
    op.drop_index(op.f('ix_service_releases_fecha_entrada'), table_name='service_releases')
    op.drop_index(op.f('ix_saved_widgets_deleted_by'), table_name='saved_widgets')
    op.drop_index(op.f('ix_saved_widgets_deleted_at'), table_name='saved_widgets')
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.create_index('ix_planes_remediacion_descripcion_gin', 'planes_remediacion', ['descripcion'], unique=False, postgresql_using='gin')
    op.create_index('ix_planes_remediacion_acciones_gin', 'planes_remediacion', ['acciones_recomendadas'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_pipeline_releases_rama'), table_name='pipeline_releases')
    op.create_unique_constraint('permissions_code_key', 'permissions', ['code'])
    op.drop_index(op.f('ix_navigation_items_deleted_by'), table_name='navigation_items')
    op.create_index('ix_navigation_items_visible', 'navigation_items', ['visible'], unique=False)
    op.create_index('ix_navigation_items_parent_id', 'navigation_items', ['parent_id'], unique=False)
    op.create_index('ix_navigation_items_orden', 'navigation_items', ['orden'], unique=False)
    op.alter_column('navigation_items', 'required_role',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('navigation_items', 'href',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    op.alter_column('navigation_items', 'icon',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('navigation_items', 'label',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.drop_constraint(None, 'module_views', type_='foreignkey')
    op.create_foreign_key('module_views_user_id_fkey', 'module_views', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_module_views_deleted_by'), table_name='module_views')
    op.drop_index(op.f('ix_kanban_columns_deleted_at'), table_name='kanban_columns')
    op.create_index('ix_iniciativas_titulo_gin', 'iniciativas', ['titulo'], unique=False, postgresql_using='gin')
    op.create_index('ix_iniciativas_descripcion_gin', 'iniciativas', ['descripcion'], unique=False, postgresql_using='gin')
    op.create_index('ix_hallazgo_sasts_titulo_gin', 'hallazgo_sasts', ['titulo'], unique=False, postgresql_using='gin')
    op.create_index('ix_hallazgo_sasts_descripcion_gin', 'hallazgo_sasts', ['descripcion'], unique=False, postgresql_using='gin')
    op.create_index('ix_hallazgo_pipelines_scan_id', 'hallazgo_pipelines', ['scan_id'], unique=False)
    op.create_index('ix_hallazgo_masts_nombre_gin', 'hallazgo_masts', ['nombre'], unique=False, postgresql_using='gin')
    op.create_index('ix_hallazgo_masts_descripcion_gin', 'hallazgo_masts', ['descripcion'], unique=False, postgresql_using='gin')
    op.create_index('ix_hallazgo_dasts_titulo_gin', 'hallazgo_dasts', ['titulo'], unique=False, postgresql_using='gin')
    op.create_index('ix_hallazgo_dasts_descripcion_gin', 'hallazgo_dasts', ['descripcion'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_custom_fields_order'), table_name='custom_fields')
    op.drop_index(op.f('ix_custom_fields_deleted_by'), table_name='custom_fields')
    op.drop_index(op.f('ix_custom_field_values_deleted_at'), table_name='custom_field_values')
    op.drop_index(op.f('ix_custom_dashboards_deleted_by'), table_name='custom_dashboards')
    op.drop_index(op.f('ix_custom_dashboards_deleted_at'), table_name='custom_dashboards')
    op.create_index('ix_control_seguridads_nombre_gin', 'control_seguridads', ['nombre'], unique=False, postgresql_using='gin')
    op.drop_index('ix_configuracion_ia_provider_enabled', table_name='configuracion_ia')
    op.drop_index(op.f('ix_code_security_reports_review_id'), table_name='code_security_reports')
    op.create_index('ix_code_security_reports_review_id', 'code_security_reports', ['review_id'], unique=False)
    op.create_unique_constraint('code_security_reports_review_id_key', 'code_security_reports', ['review_id'])
    op.drop_index(op.f('ix_code_security_findings_fingerprint'), table_name='code_security_findings')
    op.drop_index(op.f('ix_catalogs_type'), table_name='catalogs')
    op.create_index('ix_catalogs_type', 'catalogs', ['type'], unique=False)
    op.create_unique_constraint('uq_catalogs_type', 'catalogs', ['type'])
    op.create_index('ix_auditorias_titulo_gin', 'auditorias', ['titulo'], unique=False, postgresql_using='gin')
    op.create_index('ix_audit_logs_entity_ts', 'audit_logs', ['entity_type', 'entity_id', sa.text('ts DESC')], unique=False)
    op.create_index('ix_audit_logs_actor_ts', 'audit_logs', ['actor_user_id', sa.text('ts DESC')], unique=False)
    op.drop_index(op.f('ix_ai_rules_deleted_by'), table_name='ai_rules')
    op.create_index('ix_ai_rule_trigger_enabled', 'ai_rules', ['trigger_type', 'enabled'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('ix_ai_rule_action_enabled', 'ai_rules', ['action_type', 'enabled'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('ai_rules', 'action_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Action-specific config (e.g., template, user_id, tags)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('ai_rules', 'action_type',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='send_notification, create_ticket, assign_to_user, tag_entity, generate_summary, enrich_data, suggest_fix',
               existing_nullable=False,
               existing_server_default=sa.text("'send_notification'::character varying"))
    op.alter_column('ai_rules', 'trigger_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Trigger-specific config (e.g., cron schedule, severity filter)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('ai_rules', 'trigger_type',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='on_vulnerability_created, on_vulnerability_status_changed, on_release_created, on_theme_created, on_sla_at_risk, cron',
               existing_nullable=False,
               existing_server_default=sa.text("'on_vulnerability_created'::character varying"))
    op.drop_index(op.f('ix_ai_automation_rules_deleted_by'), table_name='ai_automation_rules')
    op.drop_index(op.f('ix_actividad_mensual_source_codes_deleted_at'), table_name='actividad_mensual_source_codes')
    op.drop_index(op.f('ix_actividad_mensual_servicios_regulados_deleted_at'), table_name='actividad_mensual_servicios_regulados')
    op.drop_index(op.f('ix_actividad_mensual_dasts_deleted_at'), table_name='actividad_mensual_dasts')
    op.create_table('email_templates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('asunto', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cuerpo_html', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='email_templates_pkey'),
    sa.UniqueConstraint('nombre', name='uq_email_templates_nombre'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_email_templates_nombre', 'email_templates', ['nombre'], unique=False)
    op.create_table('formulas',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('formula_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('motor', sa.VARCHAR(length=100), server_default=sa.text("'formula_engine'::character varying"), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='formulas_deleted_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='formulas_pkey')
    )
    op.create_index('ix_formulas_nombre', 'formulas', ['nombre'], unique=False)
    op.create_index('ix_formulas_deleted_at', 'formulas', ['deleted_at'], unique=False)
    op.create_table('dashboard_configs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dashboard_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('widget_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('visible', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('editable_by_role', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='dashboard_configs_deleted_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='dashboard_configs_role_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='dashboard_configs_pkey')
    )
    op.create_index('ix_dashboard_configs_widget_id', 'dashboard_configs', ['widget_id'], unique=False)
    op.create_index('ix_dashboard_configs_role_id', 'dashboard_configs', ['role_id'], unique=False)
    op.create_index('ix_dashboard_configs_deleted_by', 'dashboard_configs', ['deleted_by'], unique=False)
    op.create_index('ix_dashboard_configs_deleted_at', 'dashboard_configs', ['deleted_at'], unique=False)
    op.create_index('ix_dashboard_configs_dashboard_id', 'dashboard_configs', ['dashboard_id'], unique=False)
    op.create_table('email_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('notificacion_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('email_template_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('destinatario', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('asunto', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('estado', postgresql.ENUM('pendiente', 'enviado', 'fallido', name='email_log_estado'), server_default=sa.text("'pendiente'::email_log_estado"), autoincrement=False, nullable=False),
    sa.Column('reintentos', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('error_mensaje', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ultimo_intento_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('enviado_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['email_template_id'], ['email_templates.id'], name='email_logs_email_template_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['notificacion_id'], ['notificacions.id'], name='email_logs_notificacion_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='email_logs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='email_logs_pkey')
    )
    op.create_index('ix_email_logs_user_id', 'email_logs', ['user_id'], unique=False)
    op.create_index('ix_email_logs_notificacion_id', 'email_logs', ['notificacion_id'], unique=False)
    op.create_index('ix_email_logs_estado', 'email_logs', ['estado'], unique=False)
    op.create_index('ix_email_logs_destinatario', 'email_logs', ['destinatario'], unique=False)
    # ### end Alembic commands ###
