"""Phase 10: Add Organizacion + Gerencia hierarchy

Revision ID: 4091bd339fa9
Revises: 9d6b18a64700
Create Date: 2026-04-24 05:38:52.755506
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4091bd339fa9"
down_revision: Union[str, None] = "9d6b18a64700"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizacions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("codigo", sa.String(length=255), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizacions_deleted_at"), "organizacions", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_organizacions_deleted_by"), "organizacions", ["deleted_by"], unique=False)
    op.create_index(op.f("ix_organizacions_user_id"), "organizacions", ["user_id"], unique=False)
    op.create_table(
        "gerencias",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("subdireccion_id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["subdireccion_id"], ["subdireccions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gerencias_deleted_at"), "gerencias", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_gerencias_deleted_by"), "gerencias", ["deleted_by"], unique=False)
    op.create_index(op.f("ix_gerencias_subdireccion_id"), "gerencias", ["subdireccion_id"], unique=False)
    op.create_index(op.f("ix_gerencias_user_id"), "gerencias", ["user_id"], unique=False)
    op.add_column("celulas", sa.Column("gerencia_id", sa.UUID(), nullable=False))
    op.create_index(op.f("ix_celulas_gerencia_id"), "celulas", ["gerencia_id"], unique=False)
    op.create_foreign_key(None, "celulas", "gerencias", ["gerencia_id"], ["id"], ondelete="RESTRICT")
    op.add_column("subdireccions", sa.Column("organizacion_id", sa.UUID(), nullable=False))
    op.create_index(op.f("ix_subdireccions_organizacion_id"), "subdireccions", ["organizacion_id"], unique=False)
    op.create_foreign_key(None, "subdireccions", "organizacions", ["organizacion_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "subdireccions", type_="foreignkey")
    op.drop_index(op.f("ix_subdireccions_organizacion_id"), table_name="subdireccions")
    op.drop_column("subdireccions", "organizacion_id")
    op.drop_constraint(None, "celulas", type_="foreignkey")
    op.drop_index(op.f("ix_celulas_gerencia_id"), table_name="celulas")
    op.drop_column("celulas", "gerencia_id")
    op.drop_index(op.f("ix_gerencias_user_id"), table_name="gerencias")
    op.drop_index(op.f("ix_gerencias_subdireccion_id"), table_name="gerencias")
    op.drop_index(op.f("ix_gerencias_deleted_by"), table_name="gerencias")
    op.drop_index(op.f("ix_gerencias_deleted_at"), table_name="gerencias")
    op.drop_table("gerencias")
    op.drop_index(op.f("ix_organizacions_user_id"), table_name="organizacions")
    op.drop_index(op.f("ix_organizacions_deleted_by"), table_name="organizacions")
    op.drop_index(op.f("ix_organizacions_deleted_at"), table_name="organizacions")
    op.drop_table("organizacions")
    # ### end Alembic commands ###
