"""Phase 16 FiltroGuardado saved filters

Revision ID: 45e9065c32d2
Revises: d1dc9d87bb8d
Create Date: 2026-04-24 12:48:18.417837
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45e9065c32d2'
down_revision: Union[str, None] = 'd1dc9d87bb8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
