"""add changelog_entradas (Phase 20)

Revision ID: 539cb3a12276
Revises: 9c2eeb618484
Create Date: 2026-04-24 14:33:09.640812
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '539cb3a12276'
down_revision: Union[str, None] = '9c2eeb618484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('changelog_entradas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('fecha_publicacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('publicado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("tipo IN ('feature', 'bugfix', 'improvement', 'security', 'breaking')", name='ck_changelog_entrada_tipo'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_changelog_entradas_deleted_at'), 'changelog_entradas', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_changelog_entradas_deleted_by'), 'changelog_entradas', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_changelog_entradas_user_id'), 'changelog_entradas', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_changelog_entradas_user_id'), table_name='changelog_entradas')
    op.drop_index(op.f('ix_changelog_entradas_deleted_by'), table_name='changelog_entradas')
    op.drop_index(op.f('ix_changelog_entradas_deleted_at'), table_name='changelog_entradas')
    op.drop_table('changelog_entradas')
    # ### end Alembic commands ###
