"""Add module 4 MAST (ejecucion_mast, hallazgo_mast)

Revision ID: 54790102f946
Revises: 3e098057fd97
Create Date: 2026-04-24 05:10:06.412644
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54790102f946'
down_revision: Union[str, None] = '3e098057fd97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ejecucion_masts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('aplicacion_movil_id', sa.UUID(), nullable=False),
    sa.Column('ambiente', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resultado', sa.String(length=50), nullable=False),
    sa.Column('url_reporte', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['aplicacion_movil_id'], ['aplicacion_movils.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ejecucion_masts_ambiente'), 'ejecucion_masts', ['ambiente'], unique=False)
    op.create_index(op.f('ix_ejecucion_masts_aplicacion_movil_id'), 'ejecucion_masts', ['aplicacion_movil_id'], unique=False)
    op.create_index(op.f('ix_ejecucion_masts_deleted_at'), 'ejecucion_masts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ejecucion_masts_deleted_by'), 'ejecucion_masts', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_ejecucion_masts_user_id'), 'ejecucion_masts', ['user_id'], unique=False)
    op.create_table('hallazgo_masts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ejecucion_mast_id', sa.UUID(), nullable=False),
    sa.Column('vulnerabilidad_id', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=1024), nullable=True),
    sa.Column('severidad', sa.String(length=50), nullable=False),
    sa.Column('cwe', sa.String(length=50), nullable=True),
    sa.Column('owasp_categoria', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ejecucion_mast_id'], ['ejecucion_masts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hallazgo_masts_deleted_at'), 'hallazgo_masts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_hallazgo_masts_deleted_by'), 'hallazgo_masts', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_hallazgo_masts_ejecucion_mast_id'), 'hallazgo_masts', ['ejecucion_mast_id'], unique=False)
    op.create_index(op.f('ix_hallazgo_masts_severidad'), 'hallazgo_masts', ['severidad'], unique=False)
    op.create_index(op.f('ix_hallazgo_masts_user_id'), 'hallazgo_masts', ['user_id'], unique=False)
    op.create_index(op.f('ix_hallazgo_masts_vulnerabilidad_id'), 'hallazgo_masts', ['vulnerabilidad_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hallazgo_masts_vulnerabilidad_id'), table_name='hallazgo_masts')
    op.drop_index(op.f('ix_hallazgo_masts_user_id'), table_name='hallazgo_masts')
    op.drop_index(op.f('ix_hallazgo_masts_severidad'), table_name='hallazgo_masts')
    op.drop_index(op.f('ix_hallazgo_masts_ejecucion_mast_id'), table_name='hallazgo_masts')
    op.drop_index(op.f('ix_hallazgo_masts_deleted_by'), table_name='hallazgo_masts')
    op.drop_index(op.f('ix_hallazgo_masts_deleted_at'), table_name='hallazgo_masts')
    op.drop_table('hallazgo_masts')
    op.drop_index(op.f('ix_ejecucion_masts_user_id'), table_name='ejecucion_masts')
    op.drop_index(op.f('ix_ejecucion_masts_deleted_by'), table_name='ejecucion_masts')
    op.drop_index(op.f('ix_ejecucion_masts_deleted_at'), table_name='ejecucion_masts')
    op.drop_index(op.f('ix_ejecucion_masts_aplicacion_movil_id'), table_name='ejecucion_masts')
    op.drop_index(op.f('ix_ejecucion_masts_ambiente'), table_name='ejecucion_masts')
    op.drop_table('ejecucion_masts')
    # ### end Alembic commands ###
