"""add_servicios_aplicacion_movils_tipo_pruebas_control_seguridads

Revision ID: 7b3e094c6ad9
Revises: bf2ec55f0a0a
Create Date: 2026-04-23 02:14:12.647117
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7b3e094c6ad9"
down_revision: Union[str, None] = "bf2ec55f0a0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "control_seguridads",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("tipo", sa.String(length=100), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("obligatorio", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_control_seguridads_deleted_at"), "control_seguridads", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_control_seguridads_deleted_by"), "control_seguridads", ["deleted_by"], unique=False)
    op.create_index(op.f("ix_control_seguridads_user_id"), "control_seguridads", ["user_id"], unique=False)
    op.create_table(
        "tipo_pruebas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("categoria", sa.String(length=10), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.CheckConstraint("categoria IN ('SAST','DAST','SCA','TM','MAST')", name="ck_tipo_pruebas_categoria"),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tipo_pruebas_deleted_at"), "tipo_pruebas", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_tipo_pruebas_deleted_by"), "tipo_pruebas", ["deleted_by"], unique=False)
    op.create_index(op.f("ix_tipo_pruebas_user_id"), "tipo_pruebas", ["user_id"], unique=False)
    op.create_table(
        "aplicacion_movils",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("plataforma", sa.String(length=50), nullable=False),
        sa.Column("bundle_id", sa.String(length=255), nullable=False),
        sa.Column("celula_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["celula_id"], ["celulas.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_aplicacion_movils_celula_id"), "aplicacion_movils", ["celula_id"], unique=False)
    op.create_index(op.f("ix_aplicacion_movils_deleted_at"), "aplicacion_movils", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_aplicacion_movils_deleted_by"), "aplicacion_movils", ["deleted_by"], unique=False)
    op.create_index(op.f("ix_aplicacion_movils_user_id"), "aplicacion_movils", ["user_id"], unique=False)
    op.create_table(
        "servicios",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("criticidad", sa.String(length=50), nullable=False),
        sa.Column("tecnologia_stack", sa.Text(), nullable=True),
        sa.Column("celula_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["celula_id"], ["celulas.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_servicios_celula_id"), "servicios", ["celula_id"], unique=False)
    op.create_index(op.f("ix_servicios_deleted_at"), "servicios", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_servicios_deleted_by"), "servicios", ["deleted_by"], unique=False)
    op.create_index(op.f("ix_servicios_user_id"), "servicios", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f("ix_servicios_user_id"), table_name="servicios")
    op.drop_index(op.f("ix_servicios_deleted_by"), table_name="servicios")
    op.drop_index(op.f("ix_servicios_deleted_at"), table_name="servicios")
    op.drop_index(op.f("ix_servicios_celula_id"), table_name="servicios")
    op.drop_table("servicios")
    op.drop_index(op.f("ix_aplicacion_movils_user_id"), table_name="aplicacion_movils")
    op.drop_index(op.f("ix_aplicacion_movils_deleted_by"), table_name="aplicacion_movils")
    op.drop_index(op.f("ix_aplicacion_movils_deleted_at"), table_name="aplicacion_movils")
    op.drop_index(op.f("ix_aplicacion_movils_celula_id"), table_name="aplicacion_movils")
    op.drop_table("aplicacion_movils")
    op.drop_index(op.f("ix_tipo_pruebas_user_id"), table_name="tipo_pruebas")
    op.drop_index(op.f("ix_tipo_pruebas_deleted_by"), table_name="tipo_pruebas")
    op.drop_index(op.f("ix_tipo_pruebas_deleted_at"), table_name="tipo_pruebas")
    op.drop_table("tipo_pruebas")
    op.drop_index(op.f("ix_control_seguridads_user_id"), table_name="control_seguridads")
    op.drop_index(op.f("ix_control_seguridads_deleted_by"), table_name="control_seguridads")
    op.drop_index(op.f("ix_control_seguridads_deleted_at"), table_name="control_seguridads")
    op.drop_table("control_seguridads")
    # ### end Alembic commands ###
