"""add scr_config to code_security_reviews

Revision ID: 8a98da3cbaab
Revises: add_scr_advanced_v2
Create Date: 2026-05-01 19:03:08.161875
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a98da3cbaab'
down_revision: Union[str, None] = 'add_scr_advanced_v2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Idempotente: otra revisión (p. ej. 018_email_notifications) o un upgrade interrumpido
    # puede haber dejado el tipo ENUM en la BD sin marcar esta revisión como aplicada.
    op.execute(
        sa.text(
            """
            DO $$ BEGIN
                CREATE TYPE email_log_estado AS ENUM ('pendiente', 'enviado', 'fallido');
            EXCEPTION
                WHEN duplicate_object THEN NULL;
            END $$;
            """
        )
    )
    op.create_table('email_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('asunto', sa.String(length=255), nullable=False),
    sa.Column('cuerpo_html', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_templates_nombre'), 'email_templates', ['nombre'], unique=True)
    op.create_table('formulas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('formula_text', sa.Text(), nullable=False),
    sa.Column('motor', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formulas_deleted_at'), 'formulas', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_formulas_deleted_by'), 'formulas', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_formulas_nombre'), 'formulas', ['nombre'], unique=False)
    op.create_table('email_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notificacion_id', sa.UUID(), nullable=True),
    sa.Column('email_template_id', sa.UUID(), nullable=False),
    sa.Column('destinatario', sa.String(length=255), nullable=False),
    sa.Column('asunto', sa.String(length=255), nullable=False),
    sa.Column(
        'estado',
        postgresql.ENUM('pendiente', 'enviado', 'fallido', name='email_log_estado', create_type=False),
        server_default=sa.text("'pendiente'::email_log_estado"),
        nullable=False,
    ),
    sa.Column('reintentos', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_mensaje', sa.Text(), nullable=True),
    sa.Column('ultimo_intento_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enviado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_template_id'], ['email_templates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['notificacion_id'], ['notificacions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_logs_destinatario'), 'email_logs', ['destinatario'], unique=False)
    op.create_index(op.f('ix_email_logs_estado'), 'email_logs', ['estado'], unique=False)
    op.create_index(op.f('ix_email_logs_notificacion_id'), 'email_logs', ['notificacion_id'], unique=False)
    op.create_index(op.f('ix_email_logs_user_id'), 'email_logs', ['user_id'], unique=False)
    op.drop_index('ix_code_security_false_positives_finding_id', table_name='code_security_false_positives')
    op.drop_index('ix_code_security_false_positives_review_id', table_name='code_security_false_positives')
    op.drop_index('ix_code_security_false_positives_user_id', table_name='code_security_false_positives')
    op.drop_table('code_security_false_positives')
    op.drop_index('ix_risk_scoring_configs_user_id', table_name='risk_scoring_configs')
    op.drop_table('risk_scoring_configs')
    op.add_column('code_security_reviews', sa.Column('scr_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_security_reviews', 'scr_config')
    op.create_table('risk_scoring_configs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nombre_config', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('patron_peso', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('weight_hidden_commits', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False),
    sa.Column('weight_timing_anomalies', sa.INTEGER(), server_default=sa.text('15'), autoincrement=False, nullable=False),
    sa.Column('weight_critical_files', sa.INTEGER(), server_default=sa.text('20'), autoincrement=False, nullable=False),
    sa.Column('weight_mass_changes', sa.INTEGER(), server_default=sa.text('15'), autoincrement=False, nullable=False),
    sa.Column('weight_author_anomalies', sa.INTEGER(), server_default=sa.text('15'), autoincrement=False, nullable=False),
    sa.Column('weight_rapid_succession', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False),
    sa.Column('weight_force_push', sa.INTEGER(), server_default=sa.text('25'), autoincrement=False, nullable=False),
    sa.Column('weight_dependency_changes', sa.INTEGER(), server_default=sa.text('20'), autoincrement=False, nullable=False),
    sa.Column('weight_external_merges', sa.INTEGER(), server_default=sa.text('15'), autoincrement=False, nullable=False),
    sa.Column('activa', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='risk_scoring_configs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='risk_scoring_configs_pkey')
    )
    op.create_index('ix_risk_scoring_configs_user_id', 'risk_scoring_configs', ['user_id'], unique=False)
    op.create_table('code_security_false_positives',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('review_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('finding_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pattern_type', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['code_security_findings.id'], name='code_security_false_positives_finding_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['code_security_reviews.id'], name='code_security_false_positives_review_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='code_security_false_positives_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='code_security_false_positives_pkey')
    )
    op.create_index('ix_code_security_false_positives_user_id', 'code_security_false_positives', ['user_id'], unique=False)
    op.create_index('ix_code_security_false_positives_review_id', 'code_security_false_positives', ['review_id'], unique=False)
    op.create_index('ix_code_security_false_positives_finding_id', 'code_security_false_positives', ['finding_id'], unique=False)
    op.drop_index(op.f('ix_email_logs_user_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_notificacion_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_estado'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_destinatario'), table_name='email_logs')
    op.drop_table('email_logs')
    op.drop_index(op.f('ix_formulas_nombre'), table_name='formulas')
    op.drop_index(op.f('ix_formulas_deleted_by'), table_name='formulas')
    op.drop_index(op.f('ix_formulas_deleted_at'), table_name='formulas')
    op.drop_table('formulas')
    op.drop_index(op.f('ix_email_templates_nombre'), table_name='email_templates')
    op.drop_table('email_templates')
    # ### end Alembic commands ###
