"""Add Modulo9 vulnerabilidades entities

Revision ID: 8b1531171b7b
Revises: a203cbbe9b82
Create Date: 2026-04-23 05:18:57.156783
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b1531171b7b'
down_revision: Union[str, None] = 'a203cbbe9b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vulnerabilidads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fuente', sa.String(length=64), nullable=False),
    sa.Column('severidad', sa.String(length=32), nullable=False),
    sa.Column('estado', sa.String(length=64), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cwe_id', sa.String(length=16), nullable=True),
    sa.Column('owasp_categoria', sa.String(length=64), nullable=True),
    sa.Column('fecha_limite_sla', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responsable_id', sa.UUID(), nullable=True),
    sa.Column('repositorio_id', sa.UUID(), nullable=True),
    sa.Column('activo_web_id', sa.UUID(), nullable=True),
    sa.Column('servicio_id', sa.UUID(), nullable=True),
    sa.Column('aplicacion_movil_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['activo_web_id'], ['activo_webs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['aplicacion_movil_id'], ['aplicacion_movils.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repositorio_id'], ['repositorios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['responsable_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerabilidads_activo_web_id'), 'vulnerabilidads', ['activo_web_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilidads_aplicacion_movil_id'), 'vulnerabilidads', ['aplicacion_movil_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilidads_deleted_at'), 'vulnerabilidads', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_vulnerabilidads_deleted_by'), 'vulnerabilidads', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_vulnerabilidads_estado'), 'vulnerabilidads', ['estado'], unique=False)
    op.create_index(op.f('ix_vulnerabilidads_fecha_limite_sla'), 'vulnerabilidads', ['fecha_limite_sla'], unique=False)
    op.create_index(op.f('ix_vulnerabilidads_fuente'), 'vulnerabilidads', ['fuente'], unique=False)
    op.create_index(op.f('ix_vulnerabilidads_repositorio_id'), 'vulnerabilidads', ['repositorio_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilidads_responsable_id'), 'vulnerabilidads', ['responsable_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilidads_servicio_id'), 'vulnerabilidads', ['servicio_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilidads_severidad'), 'vulnerabilidads', ['severidad'], unique=False)
    op.create_index(op.f('ix_vulnerabilidads_user_id'), 'vulnerabilidads', ['user_id'], unique=False)
    op.create_table('aceptacion_riesgos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vulnerabilidad_id', sa.UUID(), nullable=False),
    sa.Column('justificacion_negocio', sa.Text(), nullable=False),
    sa.Column('propietario_riesgo_id', sa.UUID(), nullable=False),
    sa.Column('fecha_revision_obligatoria', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.String(length=32), nullable=False),
    sa.Column('aprobador_id', sa.UUID(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notas_aprobador', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['aprobador_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['propietario_riesgo_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vulnerabilidad_id'], ['vulnerabilidads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aceptacion_riesgos_aprobador_id'), 'aceptacion_riesgos', ['aprobador_id'], unique=False)
    op.create_index(op.f('ix_aceptacion_riesgos_deleted_at'), 'aceptacion_riesgos', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_aceptacion_riesgos_deleted_by'), 'aceptacion_riesgos', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_aceptacion_riesgos_estado'), 'aceptacion_riesgos', ['estado'], unique=False)
    op.create_index(op.f('ix_aceptacion_riesgos_fecha_revision_obligatoria'), 'aceptacion_riesgos', ['fecha_revision_obligatoria'], unique=False)
    op.create_index(op.f('ix_aceptacion_riesgos_propietario_riesgo_id'), 'aceptacion_riesgos', ['propietario_riesgo_id'], unique=False)
    op.create_index(op.f('ix_aceptacion_riesgos_user_id'), 'aceptacion_riesgos', ['user_id'], unique=False)
    op.create_index(op.f('ix_aceptacion_riesgos_vulnerabilidad_id'), 'aceptacion_riesgos', ['vulnerabilidad_id'], unique=False)
    op.create_table('evidencia_remediacions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vulnerabilidad_id', sa.UUID(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vulnerabilidad_id'], ['vulnerabilidads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidencia_remediacions_deleted_at'), 'evidencia_remediacions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_evidencia_remediacions_deleted_by'), 'evidencia_remediacions', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_evidencia_remediacions_sha256'), 'evidencia_remediacions', ['sha256'], unique=False)
    op.create_index(op.f('ix_evidencia_remediacions_user_id'), 'evidencia_remediacions', ['user_id'], unique=False)
    op.create_index(op.f('ix_evidencia_remediacions_vulnerabilidad_id'), 'evidencia_remediacions', ['vulnerabilidad_id'], unique=False)
    op.create_table('excepcion_vulnerabilidads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vulnerabilidad_id', sa.UUID(), nullable=False),
    sa.Column('justificacion', sa.Text(), nullable=False),
    sa.Column('fecha_limite', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.String(length=32), nullable=False),
    sa.Column('aprobador_id', sa.UUID(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notas_aprobador', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['aprobador_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vulnerabilidad_id'], ['vulnerabilidads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excepcion_vulnerabilidads_aprobador_id'), 'excepcion_vulnerabilidads', ['aprobador_id'], unique=False)
    op.create_index(op.f('ix_excepcion_vulnerabilidads_deleted_at'), 'excepcion_vulnerabilidads', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_excepcion_vulnerabilidads_deleted_by'), 'excepcion_vulnerabilidads', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_excepcion_vulnerabilidads_estado'), 'excepcion_vulnerabilidads', ['estado'], unique=False)
    op.create_index(op.f('ix_excepcion_vulnerabilidads_fecha_limite'), 'excepcion_vulnerabilidads', ['fecha_limite'], unique=False)
    op.create_index(op.f('ix_excepcion_vulnerabilidads_user_id'), 'excepcion_vulnerabilidads', ['user_id'], unique=False)
    op.create_index(op.f('ix_excepcion_vulnerabilidads_vulnerabilidad_id'), 'excepcion_vulnerabilidads', ['vulnerabilidad_id'], unique=False)
    op.create_table('historial_vulnerabilidads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vulnerabilidad_id', sa.UUID(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=64), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=64), nullable=True),
    sa.Column('responsable_id', sa.UUID(), nullable=True),
    sa.Column('justificacion', sa.Text(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['responsable_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vulnerabilidad_id'], ['vulnerabilidads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_vulnerabilidads_responsable_id'), 'historial_vulnerabilidads', ['responsable_id'], unique=False)
    op.create_index(op.f('ix_historial_vulnerabilidads_user_id'), 'historial_vulnerabilidads', ['user_id'], unique=False)
    op.create_index(op.f('ix_historial_vulnerabilidads_vulnerabilidad_id'), 'historial_vulnerabilidads', ['vulnerabilidad_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_vulnerabilidads_vulnerabilidad_id'), table_name='historial_vulnerabilidads')
    op.drop_index(op.f('ix_historial_vulnerabilidads_user_id'), table_name='historial_vulnerabilidads')
    op.drop_index(op.f('ix_historial_vulnerabilidads_responsable_id'), table_name='historial_vulnerabilidads')
    op.drop_table('historial_vulnerabilidads')
    op.drop_index(op.f('ix_excepcion_vulnerabilidads_vulnerabilidad_id'), table_name='excepcion_vulnerabilidads')
    op.drop_index(op.f('ix_excepcion_vulnerabilidads_user_id'), table_name='excepcion_vulnerabilidads')
    op.drop_index(op.f('ix_excepcion_vulnerabilidads_fecha_limite'), table_name='excepcion_vulnerabilidads')
    op.drop_index(op.f('ix_excepcion_vulnerabilidads_estado'), table_name='excepcion_vulnerabilidads')
    op.drop_index(op.f('ix_excepcion_vulnerabilidads_deleted_by'), table_name='excepcion_vulnerabilidads')
    op.drop_index(op.f('ix_excepcion_vulnerabilidads_deleted_at'), table_name='excepcion_vulnerabilidads')
    op.drop_index(op.f('ix_excepcion_vulnerabilidads_aprobador_id'), table_name='excepcion_vulnerabilidads')
    op.drop_table('excepcion_vulnerabilidads')
    op.drop_index(op.f('ix_evidencia_remediacions_vulnerabilidad_id'), table_name='evidencia_remediacions')
    op.drop_index(op.f('ix_evidencia_remediacions_user_id'), table_name='evidencia_remediacions')
    op.drop_index(op.f('ix_evidencia_remediacions_sha256'), table_name='evidencia_remediacions')
    op.drop_index(op.f('ix_evidencia_remediacions_deleted_by'), table_name='evidencia_remediacions')
    op.drop_index(op.f('ix_evidencia_remediacions_deleted_at'), table_name='evidencia_remediacions')
    op.drop_table('evidencia_remediacions')
    op.drop_index(op.f('ix_aceptacion_riesgos_vulnerabilidad_id'), table_name='aceptacion_riesgos')
    op.drop_index(op.f('ix_aceptacion_riesgos_user_id'), table_name='aceptacion_riesgos')
    op.drop_index(op.f('ix_aceptacion_riesgos_propietario_riesgo_id'), table_name='aceptacion_riesgos')
    op.drop_index(op.f('ix_aceptacion_riesgos_fecha_revision_obligatoria'), table_name='aceptacion_riesgos')
    op.drop_index(op.f('ix_aceptacion_riesgos_estado'), table_name='aceptacion_riesgos')
    op.drop_index(op.f('ix_aceptacion_riesgos_deleted_by'), table_name='aceptacion_riesgos')
    op.drop_index(op.f('ix_aceptacion_riesgos_deleted_at'), table_name='aceptacion_riesgos')
    op.drop_index(op.f('ix_aceptacion_riesgos_aprobador_id'), table_name='aceptacion_riesgos')
    op.drop_table('aceptacion_riesgos')
    op.drop_index(op.f('ix_vulnerabilidads_user_id'), table_name='vulnerabilidads')
    op.drop_index(op.f('ix_vulnerabilidads_severidad'), table_name='vulnerabilidads')
    op.drop_index(op.f('ix_vulnerabilidads_servicio_id'), table_name='vulnerabilidads')
    op.drop_index(op.f('ix_vulnerabilidads_responsable_id'), table_name='vulnerabilidads')
    op.drop_index(op.f('ix_vulnerabilidads_repositorio_id'), table_name='vulnerabilidads')
    op.drop_index(op.f('ix_vulnerabilidads_fuente'), table_name='vulnerabilidads')
    op.drop_index(op.f('ix_vulnerabilidads_fecha_limite_sla'), table_name='vulnerabilidads')
    op.drop_index(op.f('ix_vulnerabilidads_estado'), table_name='vulnerabilidads')
    op.drop_index(op.f('ix_vulnerabilidads_deleted_by'), table_name='vulnerabilidads')
    op.drop_index(op.f('ix_vulnerabilidads_deleted_at'), table_name='vulnerabilidads')
    op.drop_index(op.f('ix_vulnerabilidads_aplicacion_movil_id'), table_name='vulnerabilidads')
    op.drop_index(op.f('ix_vulnerabilidads_activo_web_id'), table_name='vulnerabilidads')
    op.drop_table('vulnerabilidads')
    # ### end Alembic commands ###
