"""soft delete + audit hash chain + attachment sha256

Revision ID: 9bb11b4121c0
Revises: 9c8d7e6f5a4b
Create Date: 2026-04-23 01:33:01.464490
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bb11b4121c0'
down_revision: Union[str, None] = '9c8d7e6f5a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('sha256', sa.String(length=64), nullable=True))
    op.add_column('attachments', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('attachments', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_attachments_deleted_at'), 'attachments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_attachments_deleted_by'), 'attachments', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_attachments_sha256'), 'attachments', ['sha256'], unique=False)
    op.create_foreign_key(None, 'attachments', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.add_column('audit_logs', sa.Column('prev_hash', sa.String(length=64), nullable=True))
    op.add_column('audit_logs', sa.Column('row_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_audit_logs_row_hash'), 'audit_logs', ['row_hash'], unique=False)
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_projects_deleted_at'), 'projects', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_projects_deleted_by'), 'projects', ['deleted_by'], unique=False)
    op.create_foreign_key(None, 'projects', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.add_column('tasks', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tasks_deleted_at'), 'tasks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tasks_deleted_by'), 'tasks', ['deleted_by'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_deleted_by'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_deleted_at'), table_name='tasks')
    op.drop_column('tasks', 'deleted_by')
    op.drop_column('tasks', 'deleted_at')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_deleted_by'), table_name='projects')
    op.drop_index(op.f('ix_projects_deleted_at'), table_name='projects')
    op.drop_column('projects', 'deleted_by')
    op.drop_column('projects', 'deleted_at')
    op.drop_index(op.f('ix_audit_logs_row_hash'), table_name='audit_logs')
    op.drop_column('audit_logs', 'row_hash')
    op.drop_column('audit_logs', 'prev_hash')
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_index(op.f('ix_attachments_sha256'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_deleted_by'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_deleted_at'), table_name='attachments')
    op.drop_column('attachments', 'deleted_by')
    op.drop_column('attachments', 'deleted_at')
    op.drop_column('attachments', 'sha256')
    # ### end Alembic commands ###
