"""Add DashboardConfig entity (Phase 18)

Revision ID: 9c2eeb618484
Revises: 92a31c675a40
Create Date: 2026-04-24 13:15:43.831700
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9c2eeb618484"
down_revision: Union[str, None] = "92a31c675a40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dashboard_configs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("dashboard_id", sa.String(length=100), nullable=False),
        sa.Column("widget_id", sa.String(length=255), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("visible", sa.Boolean(), nullable=False),
        sa.Column("editable_by_role", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dashboard_configs_dashboard_id"), "dashboard_configs", ["dashboard_id"], unique=False)
    op.create_index(op.f("ix_dashboard_configs_deleted_at"), "dashboard_configs", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_dashboard_configs_deleted_by"), "dashboard_configs", ["deleted_by"], unique=False)
    op.create_index(op.f("ix_dashboard_configs_role_id"), "dashboard_configs", ["role_id"], unique=False)
    op.create_index(op.f("ix_dashboard_configs_widget_id"), "dashboard_configs", ["widget_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dashboard_configs_widget_id"), table_name="dashboard_configs")
    op.drop_index(op.f("ix_dashboard_configs_role_id"), table_name="dashboard_configs")
    op.drop_index(op.f("ix_dashboard_configs_deleted_by"), table_name="dashboard_configs")
    op.drop_index(op.f("ix_dashboard_configs_deleted_at"), table_name="dashboard_configs")
    op.drop_index(op.f("ix_dashboard_configs_dashboard_id"), table_name="dashboard_configs")
    op.drop_table("dashboard_configs")
    # ### end Alembic commands ###
