"""Add modules 5-7: Iniciativas, Auditorias, Temas Emergentes (10 entities)

Revision ID: 9d6b18a64700
Revises: 54790102f946
Create Date: 2026-04-24 05:11:53.058975
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9d6b18a64700"
down_revision: Union[str, None] = "54790102f946"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "iniciativas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column("descripcion", sa.String(length=1024), nullable=True),
        sa.Column("tipo", sa.String(length=100), nullable=False),
        sa.Column("estado", sa.String(length=100), nullable=False),
        sa.Column("fecha_inicio", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fecha_fin_estimada", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_iniciativas_deleted_at"), "iniciativas", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_iniciativas_deleted_by"), "iniciativas", ["deleted_by"], unique=False)
    op.create_index(op.f("ix_iniciativas_estado"), "iniciativas", ["estado"], unique=False)
    op.create_index(op.f("ix_iniciativas_tipo"), "iniciativas", ["tipo"], unique=False)
    op.create_index(op.f("ix_iniciativas_user_id"), "iniciativas", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_iniciativas_user_id"), table_name="iniciativas")
    op.drop_index(op.f("ix_iniciativas_tipo"), table_name="iniciativas")
    op.drop_index(op.f("ix_iniciativas_estado"), table_name="iniciativas")
    op.drop_index(op.f("ix_iniciativas_deleted_by"), table_name="iniciativas")
    op.drop_index(op.f("ix_iniciativas_deleted_at"), table_name="iniciativas")
    op.drop_table("iniciativas")
    # ### end Alembic commands ###
