"""add_herramienta_externas

Revision ID: a203cbbe9b82
Revises: 1d85900047c8
Create Date: 2026-04-23 02:40:41.482733
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.encryption


# revision identifiers, used by Alembic.
revision: str = "a203cbbe9b82"
down_revision: Union[str, None] = "1d85900047c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "herramienta_externas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("tipo", sa.String(length=255), nullable=False),
        sa.Column("url_base", sa.String(length=255), nullable=True),
        sa.Column("api_token", app.core.encryption.EncryptedString(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "tipo IN ('SAST', 'DAST', 'SCA', 'TM', 'MAST', 'Terceros', 'CI/CD', 'BugBounty', 'VulnerabilityManager')",
            name="chk_herramienta_externa_tipo_valido",
        ),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_herramienta_externas_deleted_at"), "herramienta_externas", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_herramienta_externas_deleted_by"), "herramienta_externas", ["deleted_by"], unique=False)
    op.create_index(op.f("ix_herramienta_externas_user_id"), "herramienta_externas", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_herramienta_externas_user_id"), table_name="herramienta_externas")
    op.drop_index(op.f("ix_herramienta_externas_deleted_by"), table_name="herramienta_externas")
    op.drop_index(op.f("ix_herramienta_externas_deleted_at"), table_name="herramienta_externas")
    op.drop_table("herramienta_externas")
    # ### end Alembic commands ###
