"""add subdireccions and celulas

Revision ID: bee05e0b7b0a
Revises: c69d11e665e1
Create Date: 2026-04-23 02:00:56.855445
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bee05e0b7b0a'
down_revision: Union[str, None] = 'c69d11e665e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subdireccions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('codigo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subdireccions_deleted_at'), 'subdireccions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_subdireccions_deleted_by'), 'subdireccions', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_subdireccions_user_id'), 'subdireccions', ['user_id'], unique=False)
    op.create_table('celulas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('subdireccion_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subdireccion_id'], ['subdireccions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_celulas_deleted_at'), 'celulas', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_celulas_deleted_by'), 'celulas', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_celulas_subdireccion_id'), 'celulas', ['subdireccion_id'], unique=False)
    op.create_index(op.f('ix_celulas_user_id'), 'celulas', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_celulas_user_id'), table_name='celulas')
    op.drop_index(op.f('ix_celulas_subdireccion_id'), table_name='celulas')
    op.drop_index(op.f('ix_celulas_deleted_by'), table_name='celulas')
    op.drop_index(op.f('ix_celulas_deleted_at'), table_name='celulas')
    op.drop_table('celulas')
    op.drop_index(op.f('ix_subdireccions_user_id'), table_name='subdireccions')
    op.drop_index(op.f('ix_subdireccions_deleted_by'), table_name='subdireccions')
    op.drop_index(op.f('ix_subdireccions_deleted_at'), table_name='subdireccions')
    op.drop_table('subdireccions')
    # ### end Alembic commands ###
