"""add repositorios and activo_webs

Revision ID: bf2ec55f0a0a
Revises: bee05e0b7b0a
Create Date: 2026-04-23 02:04:11.665774
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf2ec55f0a0a'
down_revision: Union[str, None] = 'bee05e0b7b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activo_webs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('ambiente', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=255), nullable=False),
    sa.Column('celula_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['celula_id'], ['celulas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'url', name='uq_activo_webs_user_url')
    )
    op.create_index(op.f('ix_activo_webs_celula_id'), 'activo_webs', ['celula_id'], unique=False)
    op.create_index(op.f('ix_activo_webs_deleted_at'), 'activo_webs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_activo_webs_deleted_by'), 'activo_webs', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_activo_webs_user_id'), 'activo_webs', ['user_id'], unique=False)
    op.create_table('repositorios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('plataforma', sa.String(length=255), nullable=False),
    sa.Column('rama_default', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('celula_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['celula_id'], ['celulas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'url', name='uq_repositorios_user_url')
    )
    op.create_index(op.f('ix_repositorios_celula_id'), 'repositorios', ['celula_id'], unique=False)
    op.create_index(op.f('ix_repositorios_deleted_at'), 'repositorios', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_repositorios_deleted_by'), 'repositorios', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_repositorios_user_id'), 'repositorios', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repositorios_user_id'), table_name='repositorios')
    op.drop_index(op.f('ix_repositorios_deleted_by'), table_name='repositorios')
    op.drop_index(op.f('ix_repositorios_deleted_at'), table_name='repositorios')
    op.drop_index(op.f('ix_repositorios_celula_id'), table_name='repositorios')
    op.drop_table('repositorios')
    op.drop_index(op.f('ix_activo_webs_user_id'), table_name='activo_webs')
    op.drop_index(op.f('ix_activo_webs_deleted_by'), table_name='activo_webs')
    op.drop_index(op.f('ix_activo_webs_deleted_at'), table_name='activo_webs')
    op.drop_index(op.f('ix_activo_webs_celula_id'), table_name='activo_webs')
    op.drop_table('activo_webs')
    # ### end Alembic commands ###
