"""Phase 15 IndicadorFormula dynamic indicators

Revision ID: d1dc9d87bb8d
Revises: f8de3f84456a
Create Date: 2026-04-24 12:47:05.304372
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1dc9d87bb8d'
down_revision: Union[str, None] = 'f8de3f84456a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
